# data/edible_shrubs.py
# Auto-generated by split_plants.py
# 6 Coastal plants

EDIBLE_SHRUBS = [
    {
        "name": "Bilberry (Whortleberry)",
        "latin_name": "Vaccinium myrtillus",
        "category": "Shrub",
        "months": ['July', 'August'],
        "habitat": "Moorland, Acid Soils",
        "regions": ['North', 'Wales', 'Scotland'],
        "difficulty": 2,
        "parts": "Berries",
        "warnings": "Stains fingers/teeth blue! Difficult to wash out.",
        "description": "**Identification:** Small deciduous shrub, blue-black berries (solo, not in clusters).",
        "id_keys": {
            "Berries": "Blue-black, soft, bloom",
            "Leaves": "Small, oval, finely toothed",
            "Habitat": "High moors",
        },
        "foraging_tips": {
            "where": "High moors, acid soils.",
            "when": "Late Summer.",
            "sustainable": "Pick sparingly; birds rely on them.",
            "danger_zone": "CRITICAL: Do not confuse with Deadly Nightshade. Bilberry is a LOW shrub.",
        },
        "lookalikes": [
            {
                "name": "Deadly Nightshade",
                "danger": "POISONOUS",
                "diff": "Nightshade is a tall leafy plant with large shiny black berries. Bilberry is a low shrub with small berries.",
            },
        ],
        "confusion_notes": "Confused with Deadly Nightshade. **Key Diff:** Nightshade is a tall plant with large shiny black berries. Bilberry is a low shrub with small berries.",
    },
    {
        "name": "Sloe (Blackthorn)",
        "latin_name": "Prunus spinosa",
        "category": "Shrub",
        "months": ['September', 'October', 'November'],
        "habitat": "Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Very bitter raw! Best after frost or frozen.",
        "description": "**Identification:** Small blue-black berries with a white 'bloom'. Large thorns on black branches.",
        "id_keys": {
            "Fruit": "Small, blue-black, sour",
            "Stem": "Black bark, large sharp thorns",
            "Bush": "Dense, thicket-forming",
        },
        "foraging_tips": {
            "where": "Hedgerows.",
            "when": "Autumn (after frost).",
            "sustainable": "Leave plenty for birds.",
            "danger_zone": "Thorns are sharp and can cause infection.",
        },
        "lookalikes": [
            {
                "name": "Bullace",
                "danger": "EDIBLE",
                "diff": "Bullace is larger and less thorny.",
            },
            {
                "name": "Damson",
                "danger": "EDIBLE",
                "diff": "Damson is larger and less thorny.",
            },
        ],
        "confusion_notes": "Safe. Very sour raw but best after frost. Bullace and Damson are larger and less thorny. All are edible.",
    },
    {
        "name": "Blackberries",
        "latin_name": "Rubus fruticosus",
        "category": "Shrub",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Thorny! Watch out for ticks and leeches.",
        "description": "**Identification:** Bramble shrub with thorny stems. Aggregate fruit (many tiny drupelets) turning from red to black.",
        "id_keys": {
            "Fruit": "Black, aggregate berry",
            "Stem": "Thorny (prickles), arching",
            "Leaves": "Compound, 3-5 leaflets",
        },
        "foraging_tips": {
            "where": "Hedgerows, fields.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Very prolific. Pick freely.",
            "danger_zone": "Safe. Wash well.",
        },
        "lookalikes": [
            {
                "name": "None",
                "danger": "SAFE",
                "diff": "All blackberry-like fruits in the UK are edible.",
            },
        ],
        "confusion_notes": "Safe. No dangerous lookalikes in the UK. All blackberry-like fruits are edible.",
    },
    {
        "name": "Rosehips",
        "latin_name": "Rosa canina",
        "category": "Shrub",
        "months": ['September', 'October', 'November'],
        "habitat": "Hedgerows, Scrub",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Fruit (Hips)",
        "warnings": "Seeds inside have irritating hairs. Must be strained out!",
        "description": "**Identification:** Red, oval hips on thorny shrubs with compound leaves.",
        "id_keys": {
            "Fruit": "Red, oval hips",
            "Stem": "Thorny shrub",
            "Leaves": "Compound, serrated edges",
        },
        "foraging_tips": {
            "where": "Hedgerows.",
            "when": "Autumn (after frost).",
            "sustainable": "Leave some for birds.",
            "danger_zone": "CRITICAL: Do NOT eat the seeds inside (they are itchy).",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive red hips.",
            },
        ],
        "confusion_notes": "Safe. Distinctive red hips. Do NOT eat the seeds inside (they are itchy).",
    },
    {
        "name": "Hazelnut",
        "latin_name": "Corylus avellana",
        "category": "Shrub",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Nuts",
        "warnings": "Must be ripe. Green nuts are very astringent.",
        "description": "**Identification:** Shrub with rounded, toothed leaves. Nuts in leafy 'caps' (hats).",
        "id_keys": {
            "Leaves": "Rounded, double-toothed, soft",
            "Nut": "In a leafy, frilly 'hat'",
            "Shrub": "Bendy, multi-stemmed",
        },
        "foraging_tips": {
            "where": "Hedgerows, woods.",
            "when": "Early Autumn.",
            "sustainable": "Leave some for wildlife.",
            "danger_zone": "Safe. Identify by the leafy hat.",
        },
        "lookalikes": [
            {
                "name": "Horse Chestnut",
                "danger": "POISONOUS",
                "diff": "Conkers have a smooth/warty green case, not a leafy frilly hat.",
            },
        ],
        "confusion_notes": "Safe. Look for the leafy 'hat' on the nut. Horse Chestnut (conkers) has a smooth/warty case — NOT spiky.",
    },
    {
        "name": "Wild Raspberry",
        "latin_name": "Rubus idaeus",
        "category": "Shrub",
        "months": ['July', 'August'],
        "habitat": "Woodlands, Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Thorny canes.",
        "description": "**Identification:** Red/purple berries that pull easily from the plug. White flowers. Pale, prickly canes.",
        "id_keys": {
            "Fruit": "Red, hollow (leaves core behind)",
            "Stem": "Prickly, pale/grey",
            "Leaves": "Compound, white underneath",
        },
        "foraging_tips": {
            "where": "Woodland edges, clearings.",
            "when": "Summer.",
            "sustainable": "Leave plenty for wildlife.",
            "danger_zone": "Safe. Distinctive hollow berry.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "All raspberry-like fruits in the UK are edible.",
            },
        ],
        "confusion_notes": "Safe. All raspberry-like fruits in the UK are edible.",
    },
        {
        "name": "Bullace",
        "latin_name": "Prunus insititia",
        "category": "Shrub",
        "months": ["September", "October"],
        "habitat": "Hedgerows, Woodlands",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Fruit",
        "warnings": "Tart raw. Best after frost or cooked into jam.",
        "description": "**Identification:** Small round fruit, larger than sloe, purple-blue with a bloom. Fewer thorns than Blackthorn. Leaves are broader.",
        "id_keys": {
            "Fruit": "Purple-blue, larger than sloe, less tart",
            "Stem": "Fewer thorns than Blackthorn",
            "Leaves": "Broader than Sloe, slightly folded"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges.",
            "when": "Autumn.",
            "sustainable": "Leave some for wildlife.",
            "danger_zone": "Safe. Less tart than Sloe. Good for jam."
        },
        "lookalikes": [
            {"name": "Sloe (Blackthorn)", "danger": "EDIBLE", "diff": "Sloe is smaller, more tart, and has more/larger thorns. Bullace is larger and less thorny."},
            {"name": "Damson", "danger": "EDIBLE", "diff": "Damson is larger still, with a more distinct neck. All three are edible."}
        ],
        "confusion_notes": "Safe. All sloe/bullace/damson fruits are edible. Bullace is larger than Sloe and less thorny."
    },
    {
        "name": "Damson",
        "latin_name": "Prunus domestica subsp. insititia",
        "category": "Shrub",
        "months": ["August", "September", "October"],
        "habitat": "Hedgerows, Orchards, Gardens",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Fruit",
        "warnings": "Tart but edible raw when ripe. Excellent for jam and gin.",
        "description": "**Identification:** Small plum, oval shape, dark purple-blue skin with bloom. Less thorny than Blackthorn. Distinctive neck at the top of the fruit.",
        "id_keys": {
            "Fruit": "Oval plum, dark purple, distinct neck",
            "Stem": "Few or no thorns",
            "Leaves": "Oval, slightly folded, finely toothed"
        },
        "foraging_tips": {
            "where": "Hedgerows, old orchards, gardens.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Leave some for wildlife.",
            "danger_zone": "Safe. Excellent for jam, gin, and baking."
        },
        "lookalikes": [
            {"name": "Sloe", "danger": "EDIBLE", "diff": "Sloe is smaller and much more tart. Damson is larger and sweeter."},
            {"name": "Bullace", "danger": "EDIBLE", "diff": "Bullace is rounder. Damson has a more oval shape and distinct neck."}
        ],
        "confusion_notes": "Safe. All plum-like hedgerow fruits are edible. Damson is larger than Sloe and Bullace, with a distinctive oval shape."
    },
    {
        "name": "Guelder Rose",
        "latin_name": "Viburnum opulus",
        "category": "Shrub",
        "months": ["June", "July", "September", "October"],
        "habitat": "Hedgerows, Woodlands, Wet areas",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Berries (cooked only)",
        "warnings": "Raw berries are bitter and mildly toxic. MUST be cooked. Only the red berries, NOT the white flowers.",
        "description": "**Identification:** Large shrub with maple-like leaves. Flat clusters of white flowers in June (outer flowers large, inner small). Bright red, translucent berries in autumn.",
        "id_keys": {
            "Leaves": "Maple-like, 3-5 lobes, turn red in autumn",
            "Flowers": "Flat white clusters, outer flowers large, inner small",
            "Berries": "Bright red, translucent, slightly oval"
        },
        "foraging_tips": {
            "where": "Hedgerows, damp woods, wet areas.",
            "when": "Flowers in June, berries in September-October.",
            "sustainable": "Pick some berry clusters, leave plenty for birds.",
            "danger_zone": "CRITICAL: Raw berries are bitter and mildly toxic. Must be COOKED."
        },
        "lookalikes": [
            {"name": "Wayfaring Tree", "danger": "MILDLY TOXIC", "diff": "Wayfaring Tree has oval leaves (not maple-like) and red berries that turn black."}
        ],
        "confusion_notes": "CRITICAL: Guelder Rose berries MUST be cooked. Raw they are bitter and mildly toxic. The maple-like leaves and red translucent berries are distinctive."
    },
]
