# data/edible_seaweed.py
# Auto-generated by split_plants.py
# 1 Coastal plants

EDIBLE_SEAWEED = [
    {
        "name": "Dulse",
        "latin_name": "Palmaria palmata",
        "category": "Seaweed",
        "months": ['May', 'June', 'July', 'August', 'September'],
        "habitat": "Coastal Rocks",
        "regions": ['Coastal'],
        "difficulty": 2,
        "parts": "Fronds",
        "warnings": "Wash well. Eat raw or dried.",
        "description": "**Identification:** Dark red, hand-shaped (palmate) fronds. Leathery texture.",
        "id_keys": {
            "Colour": "Dark red / purplish",
            "Shape": "Hand-shaped (lobes)",
            "Texture": "Leathery, soft when wet",
        },
        "foraging_tips": {
            "where": "Rocky shores (attached to rocks).",
            "when": "Summer.",
            "sustainable": "Snip above holdfast.",
            "danger_zone": "Safe. Wash to remove sand.",
        },
        "lookalikes": [
            {
                "name": "Other Red Seaweeds",
                "danger": "EDIBLE",
                "diff": "Most red seaweeds are edible, but Dulse is distinct.",
            },
        ],
        "confusion_notes": "Safe. Very distinct — dark red, hand-shaped, leathery texture. Other seaweeds are mostly edible but check ID.",
    },
        {
        "name": "Bladderwrack",
        "latin_name": "Fucus vesiculosus",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Coastal Rocks, Sheltershores",
        "regions": ["Coastal"],
        "difficulty": 1,
        "parts": "Fronds",
        "warnings": "Contains iodine. Use in moderation. Can be made into tea.",
        "description": "**Identification:** Olive-brown, flat, branched fronds with distinctive paired air bladders (bubbles) along the edges. Found on mid-shore rocks.",
        "id_keys": {
            "Colour": "Olive-brown, darker when dry",
            "Shape": "Flat, branched, with paired air bladders",
            "Bladders": "Paired bubbles along the midrib (KEY ID)"
        },
        "foraging_tips": {
            "where": "Mid-shore rocks, sheltered coasts.",
            "when": "Year-round (best Spring).",
            "sustainable": "Snip above holdfast. Wash well.",
            "danger_zone": "Safe in moderation. Contains iodine. Do not eat large amounts."
        },
        "lookalikes": [
            {"name": "Knotted Wrack", "danger": "EDIBLE", "diff": "Knotted Wrack has single (not paired) air bladders. Both are edible."}
        ],
        "confusion_notes": "Safe in moderation. The PAIRED air bladders along the midrib are the key identifier. Contains iodine — do not eat large amounts."
    },
    {
        "name": "Sugar Kelp",
        "latin_name": "Saccharina latissima",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June"],
        "habitat": "Coastal Rocks, Shallow water",
        "regions": ["Coastal"],
        "difficulty": 2,
        "parts": "Fronds",
        "warnings": "Sweet taste when dried. Rich in minerals. Wash thoroughly.",
        "description": "**Identification:** Long, wavy, golden-brown frond with a wrinkled centre (like a crinkled ribbon). Sweet taste when dried. Holdfast at base.",
        "id_keys": {
            "Shape": "Long, wavy, ribbon-like with crinkled centre",
            "Colour": "Golden-brown, olive when wet",
            "Taste": "Sweet when dried (sugar kelp)"
        },
        "foraging_tips": {
            "where": "Rocks, shallow water, lower shore.",
            "when": "Winter to Spring (best quality).",
            "sustainable": "Snip above holdfast.",
            "danger_zone": "Safe. Wash thoroughly. Sweet when dried."
        },
        "lookalikes": [
            {"name": "Oarweed", "danger": "EDIBLE", "diff": "Oarweed has finger-like fronds from a single holdfast. Sugar Kelp is a single long ribbon."}
        ],
        "confusion_notes": "Safe. The long, wavy, crinkled ribbon shape and sweet taste when dried are distinctive."
    },
    {
        "name": "Laver (Nori)",
        "latin_name": "Porphyra umbilicalis",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Coastal Rocks",
        "regions": ["Coastal"],
        "difficulty": 2,
        "parts": "Fronds",
        "warnings": "Wash very thoroughly. Can be eaten raw or cooked. Used to make Welsh laverbread.",
        "description": "**Identification:** Thin, dark purple/black, sheet-like seaweed. Grows on rocks in the intertidal zone. Becomes greenish when cooked.",
        "id_keys": {
            "Colour": "Dark purple/black, thin sheets",
            "Shape": "Thin sheets growing from a central point on rocks",
            "Texture": "Thin, delicate when wet, papery when dry"
        },
        "foraging_tips": {
            "where": "Rocks in the intertidal zone.",
            "when": "Year-round (best in Winter/Spring).",
            "sustainable": "Snip from rocks. Leave holdfast.",
            "danger_zone": "Safe. Wash VERY thoroughly (traps sand). Traditional Welsh laverbread ingredient."
        },
        "lookalikes": [
            {"name": "Other Purple Seaweeds", "danger": "EDIBLE", "diff": "Most thin purple seaweeds in the UK are edible, but Laver is the most common."}
        ],
        "confusion_notes": "Safe. The thin, dark purple/black sheets on rocks are distinctive. Used to make Welsh laverbread and Japanese nori."
    },
        {
        "name": "Sea Spaghetti",
        "latin_name": "Himanthalia elongata",
        "category": "Seaweed",
        "months": ["May", "June", "July", "August", "September"],
        "habitat": "Lower rocky shores, rock pools, exposed coasts",
        "regions": ["Coastal", "All"],
        "difficulty": 2,
        "parts": "Thong-like reproductive fronds (strap-like strands)",
        "warnings": "Always wash thoroughly. Do not harvest from polluted waters. Cook before eating — do not eat raw in large quantities.",
        "description": "**Identification:** Long, strap-like, dark brown/green thongs hanging from a small button-like base. Each thong can reach 1-2m in length. The base is a small, olive-green, button-like disc (2-3cm). **Uses:** The thongs are cooked as a vegetable, added to pasta, or dried and reconstituted. Mild, slightly nutty flavour. Can be pickled.",
        "id_keys": {
            "Button base": "Small, olive-green, coin-shaped disc (2-3cm) attached to rock",
            "Long thongs": "Dark brown/green strap-like fronds, 1-2m long, branching from the base",
            "Texture": "Rubbery and flexible when fresh; becomes firmer when dried"
        },
        "foraging_tips": {
            "where": "Lower rocky shores on exposed coasts, attached to rocks in rock pools",
            "when": "May to September when thongs are long and healthy",
            "sustainable": "Cut thongs with scissors, leaving the button base attached so it regrows. Take only a few thongs per plant",
            "danger_zone": "⚠️ Do not eat raw in large quantities. Always check water quality — avoid areas near sewage outfalls or industrial discharge"
        },
        "lookalikes": [
            {
                "name": "Thongweed",
                "danger": "EDIBLE",
                "diff": "Thongweed (Himanthalia elongata) IS sea spaghetti — they are the same species. No dangerous lookalikes for the thongs themselves"
            }
        ],
        "confusion_notes": "Sea Spaghetti has a distinctive small button-like base with long strap fronds — unique among UK seaweeds and difficult to confuse with anything dangerous."
    },
    {
        "name": "Pepper Dulse",
        "latin_name": "Osmundea pinnatifida",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Rocky shores, mid to lower shore, rock pools",
        "regions": ["Coastal", "All"],
        "difficulty": 2,
        "parts": "Fronds (entire plant is edible)",
        "warnings": "Very peppery — use sparingly as a condiment rather than a bulk food. Rinse thoroughly. Do not harvest from polluted waters.",
        "description": "**Identification:** Small, finely branched, reddish-brown to dark red seaweed. Flattened fronds with pinnate branching (feather-like). Grows 5-15cm tall. Distinctive peppery flavour when chewed raw. **Uses:** Used as a pepper substitute and seasoning. Can be dried and crumbled as a condiment. Excellent in butter, with eggs, or over fish dishes.",
        "id_keys": {
            "Colour": "Dark red to reddish-brown, sometimes greenish in shaded pools",
            "Structure": "Flattened, pinnate (feather-like) branching, 5-15cm tall",
            "Taste": "Hot, peppery flavour — distinctive and unmistakable when tasted",
            "Habitat": "Mid to lower rocky shore, often in rock pools"
        },
        "foraging_tips": {
            "where": "Rock pools and rocky shores, mid to lower tidal zone",
            "when": "Year-round, but best in spring and summer when most accessible",
            "sustainable": "Snip small amounts with scissors. A little goes a long way as a condiment",
            "danger_zone": "⚠️ Check water quality. Use sparingly — the pepper heat can be intense"
        },
        "lookalikes": [
            {
                "name": "Other red seaweeds (e.g., Polysiphonia species)",
                "danger": "SAFE",
                "diff": "Most other fine red seaweeds are harmless but lack the distinctive pepper taste. Pepper dulse is identified by its peppery flavour test"
            }
        ],
        "confusion_notes": "Pepper Dulse is identified partly by its taste. Other fine red seaweeds on UK shores are generally harmless but not palatable."
    },
    {
        "name": "Carrageen Moss",
        "latin_name": "Chondrus crispus",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Rocky shores, lower shore, rock pools, exposed coasts",
        "regions": ["Coastal", "All"],
        "difficulty": 2,
        "parts": "Fronds (entire plant used)",
        "warnings": "Rinse thoroughly before use. Do not harvest from polluted waters. Contains carrageenan which is safe in food amounts but avoid excessive consumption. Not recommended for people with certain bowel conditions in large amounts.",
        "description": "**Identification:** Dark red to purple (sometimes greenish in bright light), fan-shaped, branching fronds growing 10-15cm tall. Fronds curl inward at edges when dried. Can appear iridescent blue-green underwater. Gelatinous texture when soaked. **Uses:** Traditionally used to set desserts and milky puddings (like a vegan gelatine). Also used in soups, stews, and to thicken drinks. Dried and powdered as a setting agent.",
        "id_keys": {
            "Colour": "Dark purple-red to greenish, sometimes with iridescent blue sheen underwater",
            "Shape": "Fan-shaped, forking branches, 10-15cm tall, edges curling when dry",
            "Texture": "Firm and slightly gelatinous when fresh; becomes jelly-like when boiled"
        },
        "foraging_tips": {
            "where": "Rock pools and lower rocky shore, especially on exposed coasts",
            "when": "Year-round, best in spring/summer when most accessible at low tide",
            "sustainable": "Cut with scissors, leaving holdfast attached. Take only what you need",
            "danger_zone": "⚠️ Do not harvest from polluted waters. Wash thoroughly before use"
        },
        "lookalikes": [
            {
                "name": "Grape Pip Weed (Mastocarpus stellatus)",
                "danger": "EDIBLE",
                "diff": "Grape Pip Weed has raised bumps (papillae) on its surface; Carrageen is smooth. Both are edible and traditionally collected together"
            }
        ],
        "confusion_notes": "Carrageen Moss is difficult to confuse with anything dangerous. Its close lookalike, Grape Pip Weed, is also edible and they are traditionally gathered together."
    },
    {
        "name": "Channelled Wrack",
        "latin_name": "Pelvetia canaliculata",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Upper rocky shore, highest zone of seaweed on the shore",
        "regions": ["Coastal", "All"],
        "difficulty": 1,
        "parts": "Fronds (entire plant is edible)",
        "warnings": "Rinse thoroughly. Boil well before eating. Do not eat raw in quantity. Avoid polluted areas.",
        "description": "**Identification:** Dark olive-brown to blackish, small (5-15cm), with a distinctive channel running along each frond. No midrib (unlike other wracks). Forks regularly. Found at the very top of the rocky shore — the highest seaweed zone. **Uses:** Can be boiled and eaten as a vegetable, or dried for tea. Has a mild, slightly salty flavour. Traditionally used in coastal communities.",
        "id_keys": {
            "Channel": "Distinct groove/channel running along the length of each frond — the key ID feature",
            "Colour": "Dark olive-brown to almost black when dry; olive-green when wet",
            "Size": "Small, 5-15cm, bushy compact fronds",
            "Position": "Found at the very top of the rocky shore — the highest seaweed zone"
        },
        "foraging_tips": {
            "where": "Upper rocky shore — the highest seaweed on the beach, only submerged at highest tides",
            "when": "Year-round, accessible at most tides since it grows so high on the shore",
            "sustainable": "Snip with scissors, leaving holdfast on rock. A small amount goes far",
            "danger_zone": "⚠️ Must be well-cooked. Do not eat raw in any quantity"
        },
        "lookalikes": [
            {
                "name": "Spiral Wrack (Fucus spiralis)",
                "danger": "EDIBLE",
                "diff": "Spiral Wrack has a visible midrib and no channel; Channelled Wrack has a channel but no midrib"
            }
        ],
        "confusion_notes": "The channel running along each frond is unique to this species. Other wracks are also edible so confusion is not dangerous."
    },
    {
        "name": "Serrated Wrack",
        "latin_name": "Fucus serratus",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Mid to lower rocky shores, commonly found on rocky coasts",
        "regions": ["Coastal", "All"],
        "difficulty": 1,
        "parts": "Fronds (entire plant edible)",
        "warnings": "Rinse thoroughly before use. Cook before eating — do not eat raw in quantity. Avoid polluted waters and areas near sewage outfalls.",
        "description": "**Identification:** Olive-brown, flat fronds with a distinct midrib and serrated (saw-toothed) edges. No air bladders. 15-60cm long. Serrated edges distinguish it from Bladderwrack (which has smooth edges and air bladders) and Spiral Wrack. **Uses:** Can be boiled as a vegetable, added to soups and stews, or dried. Contains alginates which thicken liquids. Mild, slightly salty ocean flavour.",
        "id_keys": {
            "Serrated edges": "Distinct saw-toothed margins on fronds — the key identification feature",
            "Midrib": "Clear central midrib running along each frond",
            "No bladders": "No air bladders present (unlike Bladderwrack)",
            "Size": "15-60cm long, branching fronds"
        },
        "foraging_tips": {
            "where": "Mid to lower rocky shore, very common on UK rocky coasts",
            "when": "Year-round, accessible at low tide",
            "sustainable": "Cut with scissors, leaving holdfast on rock. Take only what you need",
            "danger_zone": "⚠️ Always cook before eating. Do not harvest from polluted waters"
        },
        "lookalikes": [
            {
                "name": "Bladderwrack (Fucus vesiculosus)",
                "danger": "EDIBLE",
                "diff": "Bladderwrack has smooth edges and air bladders; Serrated Wrack has serrated edges and no bladders"
            },
            {
                "name": "Spiral Wrack (Fucus spiralis)",
                "danger": "EDIBLE",
                "diff": "Spiral Wrack has smooth edges and spirally twisted frond tips; Serrated Wrack has saw-toothed edges"
            }
        ],
        "confusion_notes": "The serrated edges make this wrack distinctive. All common UK wracks are edible so confusion between them is not dangerous, but correct identification ensures best flavour and texture."
    },
    {
        "name": "Gutweed",
        "latin_name": "Ulva intestinalis",
        "category": "Seaweed",
        "months": ["March", "April", "May", "June", "July", "August", "September", "October"],
        "habitat": "Upper shore, rock pools, brackish water, harbour walls, estuary edges",
        "regions": ["Coastal", "All"],
        "difficulty": 1,
        "parts": "Entire plant (tubular fronds)",
        "warnings": "Must rinse very thoroughly — often grows in areas with poor water quality (harbours, estuaries). Only harvest from clean water sites. Cook before eating.",
        "description": "**Identification:** Bright green, tubular, inflated fronds that look like small intestines or water-filled sausages. 5-30cm long. Often floats in clusters. Sometimes partially flattened. Found high on the shore and even in brackish pools. **Uses:** Can be eaten raw in small amounts if from clean water, but best cooked. Used in soups, stir-fries, and salads. Bright green colour makes it an attractive garnish. Mild, fresh, slightly salty taste.",
        "id_keys": {
            "Colour": "Bright, vivid green — one of the greenest seaweeds on the shore",
            "Shape": "Tubular, inflated, sausage-like fronds, sometimes bloated with gas",
            "Size": "5-30cm long, growing in dense tufts or clusters",
            "Habitat": "Upper shore, rock pools, brackish areas, harbour walls"
        },
        "foraging_tips": {
            "where": "Upper shore rock pools, harbour walls, brackish pools — but ONLY from clean water sites",
            "when": "Spring to autumn, best in May-July",
            "sustainable": "Snip with scissors, leaving base attached. Grows back quickly",
            "danger_zone": "⚠️ CRITICAL: Often grows near pollution sources. Only harvest from pristine water sites. Check local water quality advisories"
        },
        "lookalikes": [
            {
                "name": "Sea Lettuce (Ulva lactuca)",
                "danger": "EDIBLE",
                "diff": "Sea Lettuce is flat and leaf-like; Gutweed is tubular and inflated like a sausage. Both are edible"
            },
            {
                "name": "Flat Gutweed (Ulva compressa)",
                "danger": "EDIBLE",
                "diff": "Flat Gutweed is partially compressed/flattened but related and also edible"
            }
        ],
        "confusion_notes": "Gutweed is easy to identify by its bright green, tubular, sausage-like fronds. The main risk is not misidentification but water quality — it often grows in polluted areas."
    },
    {
        "name": "Oarweed",
        "latin_name": "Laminaria digitata",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Lower shore and subtidal, exposed rocky coasts, kelp forests",
        "regions": ["Coastal", "Northern"],
        "difficulty": 3,
        "parts": "Frond (blade) — the leathery leaf-like section",
        "warnings": "Only harvest on spring low tides — dangerous if cut off by incoming tide. Rinse thoroughly. Cook well before eating. Do not harvest from polluted waters.",
        "description": "**Identification:** Large brown kelp with a smooth, flexible stipe (stalk) and a wide frond divided into 5-20 finger-like straps. No midrib in the blade. Can grow 1-2m long. Thick leathery texture. Found on lower shore and subtidal zone. **Uses:** The frond can be cooked as a vegetable, dried for stocks, or used in soups and stews. Rich in iodine and minerals. Has a strong ocean flavour — best used sparingly.",
        "id_keys": {
            "Frond": "Wide blade divided into 5-20 finger-like straps — like an outstretched hand",
            "Stipe": "Smooth, flexible stalk with no wrinkles or ridges (unlike Dabberlocks)",
            "Size": "1-2m total length, large and leathery",
            "Holdfast": "Root-like holdfast gripping the rock, visible at extreme low tide"
        },
        "foraging_tips": {
            "where": "Lower rocky shore, exposed coasts — only accessible on the lowest spring tides",
            "when": "Year-round, but only accessible during spring low tides",
            "sustainable": "Cut only the top portion of the frond with scissors/knife, leaving stipe and base to regrow. Take only small amounts",
            "danger_zone": "⚠️ DANGER: Only forage on retreating tides. Being cut off by incoming tide is a real risk. Check tide times carefully"
        },
        "lookalikes": [
            {
                "name": "Sugar Kelp (Saccharina latissima)",
                "danger": "EDIBLE",
                "diff": "Sugar Kelp has a single undivided strap-like blade; Oarweed has finger-like divisions"
            },
            {
                "name": "Dabberlocks (Alaria esculenta)",
                "danger": "EDIBLE",
                "diff": "Dabberlocks has a distinct midrib in the blade and a wavy, wrinkled stipe; Oarweed has no midrib and a smooth stipe"
            }
        ],
        "confusion_notes": "Oarweed is distinctive with its hand-like divided fronds. Other large UK kelps are also edible so confusion is not dangerous, but tide safety is the primary concern."
    },
    {
        "name": "Dabberlocks",
        "latin_name": "Alaria esculenta",
        "category": "Seaweed",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Lower shore and subtidal on exposed, wave-battered coasts",
        "regions": ["Coastal", "Northern"],
        "difficulty": 3,
        "parts": "Frond blade and midrib",
        "warnings": "Only harvest on spring low tides — dangerous if cut off by incoming tide. Rinse thoroughly. Cook before eating. Very exposed locations can be hazardous.",
        "description": "**Identification:** Long brown kelp with a prominent midrib running through a wavy-edged blade. Stipe (stalk) is wavy/wrinkled with longitudinal ridges. Blade can reach 1-2m. Reproductive leaflets (sporophylls) grow from the stipe near the base. Found on very exposed coasts. **Uses:** The midrib is crisp and sweet — considered a delicacy. The blade can also be eaten. Cook as a vegetable, add to soups, or dry for stocks. One of the finest eating kelps.",
        "id_keys": {
            "Midrib": "Prominent thick midrib running through the blade — key feature",
            "Stipe": "Wavy, wrinkled stalk with longitudinal ridges (unlike Oarweed's smooth stipe)",
            "Blade": "Long, wavy-edged, with a distinct midrib — can reach 1-2m",
            "Sporophylls": "Small leaf-like growths near the base of the stipe"
        },
        "foraging_tips": {
            "where": "Very exposed, wave-battered rocky coasts — lower shore. Often the dominant kelp on Atlantic-facing shores",
            "when": "Year-round, but only accessible on the lowest spring tides",
            "sustainable": "Cut only the blade above the stipe, leaving the holdfast and stipe intact. The midrib is the prize — slice it out carefully",
            "danger_zone": "⚠️ DANGER: Exposed coasts and low tides are hazardous. Never turn your back on the sea. Check tides carefully"
        },
        "lookalikes": [
            {
                "name": "Oarweed (Laminaria digitata)",
                "danger": "EDIBLE",
                "diff": "Oarweed has a smooth stipe and no midrib in the blade; Dabberlocks has a wrinkled stipe and prominent midrib"
            },
            {
                "name": "Sugar Kelp (Saccharina latissima)",
                "danger": "EDIBLE",
                "diff": "Sugar Kelp has a single undivided blade with no midrib; Dabberlocks has a prominent midrib"
            }
        ],
        "confusion_notes": "Dabberlocks is distinguished by its prominent midrib and wrinkled stipe. All large UK kelps are edible so confusion between them is not dangerous, but tide safety is critical."
    }
]
