# data/edible_fungi.py
# Auto-generated by split_plants.py
# 11 Coastal plants

EDIBLE_FUNGI = [
    {
        "name": "Wood Blewit",
        "latin_name": "Clitocybe nuda",
        "category": "Fungi",
        "months": ['September', 'October', 'November', 'December'],
        "habitat": "Woodlands, Gardens",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "Must be cooked. Some people have allergic reaction.",
        "description": "**Identification:** Lilac/Purple cap fading to tan. Lilac gills. Bulbous stem.",
        "id_keys": {
            "Cap": "Lilac turning tan",
            "Gills": "Lilac, crowded",
            "Stem": "Thick, bulbous, lilac",
        },
        "foraging_tips": {
            "where": "Woodlands, gardens (leaf litter).",
            "when": "Autumn.",
            "sustainable": "Cut at base, leave mycelium.",
            "danger_zone": "Must be cooked. Can cause allergic reaction in some people.",
        },
        "lookalikes": [
            {
                "name": "Lilac Fibrecap",
                "danger": "POISONOUS",
                "diff": "Fibrecap grows in GRASS. Blewit grows on WOOD/LEAVES.",
            },
        ],
        "confusion_notes": "IMPORTANT: Wood Blewit is lilac and grows on wood/leaves. Lilac Fibrecap grows in grass and is POISONOUS. Check where it grows!",
    },
    {
        "name": "Oyster Mushroom",
        "latin_name": "Pleurotus ostreatus",
        "category": "Fungi",
        "months": ['September', 'October', 'November', 'December'],
        "habitat": "Woodlands (Dead hardwood)",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Whole mushroom",
        "warnings": "Check for bugs. Gills should be white/cream.",
        "description": "**Identification:** Fan-shaped, oyster-like cap. Gills run down the stem (if present). Grows in tiers on wood.",
        "id_keys": {
            "Cap": "Fan/Oyster shaped, grey/brown",
            "Gills": "White, running down stem",
            "Habitat": "On dead wood (stumps/trunks)",
        },
        "foraging_tips": {
            "where": "Dead deciduous trees, stumps.",
            "when": "Autumn/Winter.",
            "sustainable": "Cut stem. Leave small ones.",
            "danger_zone": "Check for bugs. Slice and check inside.",
        },
        "lookalikes": [
            {
                "name": "Angel's Wings",
                "danger": "POISONOUS",
                "diff": "Grows on conifers. White, very thin/fragile. Avoid white oysters on conifers.",
            },
        ],
        "confusion_notes": "IMPORTANT: Only eat oyster mushrooms growing on HARDWOOD. White, thin, fragile mushrooms on CONIFERS could be Angel's Wings (POISONOUS).",
    },
    {
        "name": "Giant Puffball",
        "latin_name": "Calvatia gigantea",
        "category": "Fungi",
        "months": ['August', 'September', 'October'],
        "habitat": "Grassland, Pastures",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Whole mushroom (young)",
        "warnings": "Must be WHITE inside. If yellow/purple, discard.",
        "description": "**Identification:** Huge white ball (football size or bigger). White skin, white flesh inside.",
        "id_keys": {
            "Shape": "Giant white ball",
            "Inside": "Solid white (like cheese)",
            "Size": "Can be huge",
        },
        "foraging_tips": {
            "where": "Fields, pastures.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Cut a slice. Leave small ones.",
            "danger_zone": "Slice open. Must be WHITE inside. If purple/yellow, it is old/spoiled.",
        },
        "lookalikes": [
            {
                "name": "Earthball",
                "danger": "POISONOUS",
                "diff": "Earthball has THICK skin and PURPLE/BROWN inside. Giant Puffball is white inside.",
            },
        ],
        "confusion_notes": "CRITICAL: Must be WHITE inside. If the inside is yellow, purple, or brown, it is too old or spoiled. Earthball is POISONOUS and has a THICK skin and PURPLE/BROWN inside.",
    },
    {
        "name": "St. George's Mushroom",
        "latin_name": "Calocybe gambosa",
        "category": "Fungi",
        "months": ['April', 'May'],
        "habitat": "Grassland, Lawns, Roadsides",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "EXPERT ID. Appears in Spring (St George's Day, April 23).",
        "description": "**Identification:** White cap, white gills, white stem. Mealy smell. Forms 'fairy rings' in grass.",
        "id_keys": {
            "Cap": "White, smooth",
            "Gills": "White, crowded",
            "Smell": "Mealy/floury",
            "Time": "Spring (Early)",
        },
        "foraging_tips": {
            "where": "Grassland, lawns.",
            "when": "April - May (Spring).",
            "sustainable": "Cut stem.",
            "danger_zone": "Must be confident. Poisonous Entoloma species look similar.",
        },
        "lookalikes": [
            {
                "name": "Entoloma (Poisonous)",
                "danger": "POISONOUS",
                "diff": "Entolomas have PINK spores (check gill colour). St. George's is white throughout.",
            },
        ],
        "confusion_notes": "CRITICAL: Appears in SPRING (April-May). Most poisonous lookalikes appear in AUTUMN. Still requires 100% confidence to eat.",
    },
    {
        "name": "Wood Ear (Jelly Ear)",
        "latin_name": "Auricularia auricula-judae",
        "category": "Fungi",
        "months": ['January', 'February', 'March', 'April', 'May', 'September', 'October', 'November', 'December'],
        "habitat": "Woodlands (Elder trees)",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Whole mushroom",
        "warnings": "Must be cooked. Texture is rubbery.",
        "description": "**Identification:** Brown, ear-shaped, gelatinous fungus. Grows on elder wood.",
        "id_keys": {
            "Shape": "Ear-shaped, cupped",
            "Texture": "Jelly-like, rubbery, gelatinous",
            "Habitat": "Grows on dead Elder wood",
        },
        "foraging_tips": {
            "where": "Elder trees.",
            "when": "Autumn to Spring.",
            "sustainable": "Cut off with a knife.",
            "danger_zone": "Safe. Distinctive texture and host tree.",
        },
        "lookalikes": [
            {
                "name": "Other Tree Ears",
                "danger": "EDIBLE",
                "diff": "Most similar-looking fungi on wood are edible, but Wood Ear is most common on Elder.",
            },
        ],
        "confusion_notes": "Safe. If it looks like an ear and feels like jelly, it is likely Wood Ear. Does NOT grow on the ground.",
    },
    {
        "name": "Chanterelle",
        "latin_name": "Cantharellus cibarius",
        "category": "Fungi",
        "months": ['July', 'August', 'September'],
        "habitat": "Woodlands (Birch, Oak, Beech)",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "Must be cooked. Do not wash, brush clean.",
        "description": "**Identification:** Egg-yolk yellow. Funnel-shaped. Blunt forking ridges (false gills) running down stem. Smells of apricots.",
        "id_keys": {
            "Colour": "Egg-yolk yellow",
            "Gills": "Blunt, forking ridges (false gills)",
            "Smell": "Apricots",
        },
        "foraging_tips": {
            "where": "Woodland floor.",
            "when": "Summer/Autumn.",
            "sustainable": "Cut stem, leave mycelium.",
            "danger_zone": "CRITICAL: Must have blunt ridges and smell of apricots.",
        },
        "lookalikes": [
            {
                "name": "False Chanterelle",
                "danger": "POISONOUS",
                "diff": "False Chanterelle has thin, true gills like paper and NO apricot smell.",
            },
            {
                "name": "Jack O'Lantern",
                "danger": "POISONOUS",
                "diff": "Grows in clusters on wood. True Chanterelle grows on the ground.",
            },
        ],
        "confusion_notes": "CRITICAL: True Chanterelle has RIDGES (not gills) and smells of apricots. False Chanterelle has thin gills like paper and NO apricot smell.",
    },
    {
        "name": "Field Mushroom",
        "latin_name": "Agaricus campestris",
        "category": "Fungi",
        "months": ['August', 'September', 'October'],
        "habitat": "Grassland, Fields",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "EXPERT ID. Yellow Stainer looks similar.",
        "description": "**Identification:** White cap. Pink gills turning dark brown. White stem with ring. Smells of mushroom/anise.",
        "id_keys": {
            "Cap": "White, smooth",
            "Gills": "Pink turning dark brown",
            "Smell": "Mushroom/Anise",
        },
        "foraging_tips": {
            "where": "Open grassland, fields.",
            "when": "Autumn.",
            "sustainable": "Cut stem.",
            "danger_zone": "CRITICAL: Check for yellow staining and bad smell.",
        },
        "lookalikes": [
            {
                "name": "Yellow Stainer",
                "danger": "POISONOUS",
                "diff": "Yellow Stainer stains bright yellow when bruised and smells of ink.",
            },
            {
                "name": "Death Cap",
                "danger": "DEADLY",
                "diff": "Death Cap has white gills (never pink) and a volva cup at the base.",
            },
        ],
        "confusion_notes": "CRITICAL: Yellow Stainer stains bright yellow when bruised and smells of ink. Death Cap has white gills (never pink). If in doubt, do NOT eat.",
    },
    {
        "name": "Morel",
        "latin_name": "Morchella esculenta",
        "category": "Fungi",
        "months": ['March', 'April', 'May'],
        "habitat": "Woodlands, Gardens, Burnt Ground",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "Must be cooked. EXPERT ID. Hollow inside.",
        "description": "**Identification:** Honeycomb cap (pits and ridges). Cap is attached to stem. Hollow inside.",
        "id_keys": {
            "Cap": "Honeycomb pits and ridges",
            "Inside": "Hollow like a balloon",
            "Attachment": "Cap joins stem at the bottom",
        },
        "foraging_tips": {
            "where": "Woodlands, ash, burn sites.",
            "when": "Spring.",
            "sustainable": "Cut stem, leave base.",
            "danger_zone": "CRITICAL: Must be HOLLOW inside.",
        },
        "lookalikes": [
            {
                "name": "False Morel",
                "danger": "DEADLY",
                "diff": "False Morel has brain wrinkles (not honeycomb pits) and is SOLID/CHAMBERED inside.",
            },
        ],
        "confusion_notes": "CRITICAL: True Morel is HOLLOW inside like a balloon. False Morel is chambered/solid inside. If it is NOT hollow, do NOT eat it.",
    },
    {
        "name": "Shaggy Inkcap",
        "latin_name": "Coprinus comatus",
        "category": "Fungi",
        "months": ['August', 'September', 'October', 'November'],
        "habitat": "Grassland, Roadsides, Waste Ground",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Whole mushroom",
        "warnings": "Must be eaten very fresh (within hours). Turns to ink. Do NOT mix with alcohol.",
        "description": "**Identification:** Tall, white, cylindrical cap with shaggy scales. White gills turn pink, then black, then dissolve into ink.",
        "id_keys": {
            "Cap": "White, tall, shaggy scales",
            "Gills": "White -> Pink -> Black -> Ink",
            "Habitat": "Bare soil, roadsides, paths",
        },
        "foraging_tips": {
            "where": "Grass, paths, roads.",
            "when": "Autumn.",
            "sustainable": "Cut stem.",
            "danger_zone": "CRITICAL: Eat within hours of picking. Do NOT drink alcohol.",
        },
        "lookalikes": [
            {
                "name": "Common Inkcap",
                "danger": "POISONOUS (with alcohol)",
                "diff": "Common Inkcap is smaller, less shaggy, and causes severe illness if alcohol is consumed.",
            },
        ],
        "confusion_notes": "CRITICAL: Must be eaten fresh before it turns to ink. Do NOT consume alcohol with Inkcap mushrooms.",
    },
    {
        "name": "Hedgehog Mushroom",
        "latin_name": "Hydnum repandum",
        "category": "Fungi",
        "months": ['August', 'September', 'October', 'November'],
        "habitat": "Woodlands (Beech, Oak)",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Whole mushroom",
        "warnings": "Can be bitter raw. Must be cooked.",
        "description": "**Identification:** Pale cap. Underneath has SPINES (not gills) that look like a hedgehog. Smells peppery.",
        "id_keys": {
            "Cap": "Pale buff/ochre, irregular",
            "Spines": "Under cap, hanging down (not gills)",
            "Smell": "Peppery",
        },
        "foraging_tips": {
            "where": "Woodland (under beech/oak).",
            "when": "Autumn.",
            "sustainable": "Cut stem.",
            "danger_zone": "Safe. Spines instead of gills make it hard to mistake.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "The spines underneath are unique. No dangerous lookalikes.",
            },
        ],
        "confusion_notes": "Safe. If it has spines underneath instead of gills, it is a Hedgehog Mushroom. No dangerous lookalikes.",
    },
    {
        "name": "Parasol Mushroom",
        "latin_name": "Macrolepiota procera",
        "category": "Fungi",
        "months": ['July', 'August', 'September', 'October'],
        "habitat": "Grassland, Pastures, Open Woods",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Cap",
        "warnings": "Only eat caps. Stems are too tough. Must be cooked.",
        "description": "**Identification:** Very tall. Large brown-scaled cap like a parasol. Brown 'snakeskin' pattern on stem. Moveable ring.",
        "id_keys": {
            "Cap": "Large, brown scales on white background",
            "Stem": "Brown snakeskin pattern",
            "Ring": "Moveable ring on stem",
        },
        "foraging_tips": {
            "where": "Open grassland, paths.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Cut cap, leave stem.",
            "danger_zone": "CRITICAL: Must have snakeskin stem and moveable ring.",
        },
        "lookalikes": [
            {
                "name": "Shaggy Parasol",
                "danger": "EDIBLE (some people allergic)",
                "diff": "Shaggy Parasol is smaller and has a white stem, not snakeskin.",
            },
        ],
        "confusion_notes": "CRITICAL: True Parasol has a SNAKESKIN pattern on the stem and a moveable ring. If the stem is smooth or white, do NOT eat it.",
    },
    {
        "name": "Chicken of the Woods",
        "latin_name": "Laetiporus sulphureus",
        "category": "Fungi",
        "months": ["May", "June", "July", "August", "September"],
        "habitat": "Woodlands (Oak, Sweet Chestnut)",
        "regions": ["Southern", "Central"],
        "difficulty": 2,
        "parts": "Young brackets",
        "warnings": "Must be cooked. Do NOT eat from Yew (toxic host). Some people are allergic.",
        "description": "**Identification:** Bright orange-yellow shelf fungus growing in tiers on tree trunks. Soft and juicy when young. Looks like chicken breast when cooked.",
        "id_keys": {
            "Colour": "Bright orange-yellow, zoned",
            "Texture": "Soft, spongy, juicy when young",
            "Habitat": "On tree trunks (oak, chestnut)",
            "Underside": "Yellow pores (not gills)"
        },
        "foraging_tips": {
            "where": "Oak and sweet chestnut trees.",
            "when": "Spring to early Autumn.",
            "sustainable": "Cut young brackets only. Leave older, harder ones.",
            "danger_zone": "CRITICAL: Do NOT eat from Yew trees. The fungus absorbs toxins from yew."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Bright orange-yellow brackets on trees are distinctive. Nothing else looks like this."}
        ],
        "confusion_notes": "Safe when cooked. Bright orange-yellow brackets on trees. Do NOT eat from Yew trees — the fungus absorbs yew toxins."
    },
    {
        "name": "Bay Bolete",
        "latin_name": "Imleria badia",
        "category": "Fungi",
        "months": ["August", "September", "October"],
        "habitat": "Woodlands (Pine, Birch)",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Cap, Tubes",
        "warnings": "Must be cooked. Blue staining on pores when pressed.",
        "description": "**Identification:** Chestnut-brown cap. Yellow tubes under the cap that stain blue when bruised. Net pattern on stem.",
        "id_keys": {
            "Cap": "Chestnut-brown, smooth, slightly sticky",
            "Tubes": "Yellow, stain BLUE when pressed",
            "Stem": "Pale with fine net pattern (reticulation)"
        },
        "foraging_tips": {
            "where": "Pine and birch woodland.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Cut stem. Leave young ones.",
            "danger_zone": "The blue staining is normal. Must be cooked."
        },
        "lookalikes": [
            {"name": "Bitter Bolete", "danger": "INEDIBLE", "diff": "Bitter Bolete tastes extremely bitter and has PINK tubes. Bay Bolete has YELLOW tubes."}
        ],
        "confusion_notes": "Safe when cooked. The blue staining on the tubes when pressed is NORMAL. If it tastes extremely bitter, it is the Bitter Bolete."
    },
    {
        "name": "Fairy Ring Champignon",
        "latin_name": "Marasmius oreades",
        "category": "Fungi",
        "months": ["May", "June", "July", "August", "September"],
        "habitat": "Grassland, Lawns",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Caps only",
        "warnings": "Discard stems. Must be cooked. Grows in fairy rings. Double-check ID.",
        "description": "**Identification:** Small tan/brown mushroom. Nipple-shaped cap. Widely spaced gills. Grows in rings on lawns and grassland.",
        "id_keys": {
            "Cap": "Tan/brown, nipple-shaped (umbo)",
            "Gills": "Widely spaced, pale",
            "Habitat": "Grows in rings on grassland",
            "Stem": "Tough, fibrous (discard)"
        },
        "foraging_tips": {
            "where": "Lawns, grassland, parks.",
            "when": "Spring to Autumn.",
            "sustainable": "Cut caps, leave stems. Only pick from clean grass.",
            "danger_zone": "CRITICAL: Must be confident in ID. Some similar mushrooms are toxic."
        },
        "lookalikes": [
            {"name": "Clitocybe species", "danger": "POISONOUS", "diff": "Some Clitocybe species also grow in rings but have crowded gills and no nipple on cap. Fairy Ring has widely spaced gills and a nipple."}
        ],
        "confusion_notes": "Only eat if confident. Fairy Ring has a NIPPLE-SHAPED cap and WIDELY SPACED gills. If in doubt, do NOT eat."
    },
    {
        "name": "Cauliflower Fungus",
        "latin_name": "Sparassis crispa",
        "category": "Fungi",
        "months": ["August", "September", "October"],
        "habitat": "Woodlands (Pine roots)",
        "regions": ["Southern", "Central"],
        "difficulty": 2,
        "parts": "Whole fungus",
        "warnings": "Must be washed thoroughly (traps dirt). Must be cooked.",
        "description": "**Identification:** Large, pale, brain-like or cauliflower-shaped fungus growing at the base of pine trees. Many flattened, wavy branches.",
        "id_keys": {
            "Shape": "Like a cauliflower — many wavy, flattened branches",
            "Colour": "Pale cream/yellowish",
            "Habitat": "Base of pine trees"
        },
        "foraging_tips": {
            "where": "At the base of pine trees.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Cut at base. Wash VERY thoroughly.",
            "danger_zone": "Safe. Distinctive shape. Must be washed thoroughly as it traps dirt."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The cauliflower/brain shape at the base of pine trees is unique."}
        ],
        "confusion_notes": "Safe. The cauliflower shape at the base of pine trees is distinctive. Must be washed very thoroughly as the folds trap dirt and insects."
    },
    {
        "name": "Amethyst Deceiver",
        "latin_name": "Laccaria amethystina",
        "category": "Fungi",
        "months": ["August", "September", "October", "November"],
        "habitat": "Woodlands (Beech, Oak)",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Whole mushroom",
        "warnings": "Only eat when clearly purple. Fades to brown when old or washed out.",
        "description": "**Identification:** Small, vivid purple mushroom when fresh. Gills are widely spaced and purple. Fades to pale brown with age or rain.",
        "id_keys": {
            "Cap": "Vivid purple when fresh, fading to brown",
            "Gills": "Widely spaced, purple then pale",
            "Stem": "Purple, fibrous, same colour as cap"
        },
        "foraging_tips": {
            "where": "Beech and oak woodland.",
            "when": "Autumn.",
            "sustainable": "Cut stem.",
            "danger_zone": "Only eat when clearly PURPLE. If faded to brown, it is hard to identify."
        },
        "lookalikes": [
            {"name": "Lilac Fibrecap", "danger": "POISONOUS", "diff": "Lilac Fibrecap has fibrous cap and grows in GRASS. Amethyst Deceiver has smooth cap and grows in WOODLAND."}
        ],
        "confusion_notes": "Safe when clearly purple. Amethyst Deceiver grows in WOODLAND, has a smooth cap, and widely spaced gills. If faded to brown, do NOT eat."
    },
    {
        "name": "Porcini (Penny Bun)",
        "latin_name": "Boletus edulis",
        "category": "Fungi",
        "months": ["July", "August", "September", "October"],
        "habitat": "Woodlands (Birch, Oak, Pine)",
        "regions": ["All"],
        "difficulty": 3,
        "parts": "Cap, Tubes, Stem",
        "warnings": "EXPERT ID. Must be 100% certain. Cook before eating.",
        "description": "**Identification:** Large, brown cap with white underside (pores, not gills). Thick white/cream stem with a fine net pattern (reticulation). Smells nutty.",
        "id_keys": {
            "Cap": "Brown, smooth, convex then flat",
            "Underside": "White pores when young, turning yellow-green with age (NO gills)",
            "Stem": "Thick, white/cream, fine net pattern (reticulation)"
        },
        "foraging_tips": {
            "where": "Woodland edges, birch/oak/pine.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Cut stem, leave base.",
            "danger_zone": "CRITICAL: Must have white pores (not gills), thick stem with net pattern, and nutty smell."
        },
        "lookalikes": [
            {"name": "Bitter Bolete", "danger": "INEDIBLE", "diff": "Bitter Bolete has PINK pores when young and tastes extremely bitter. Porcini has WHITE pores when young."},
            {"name": "Satan's Bolete", "danger": "POISONOUS", "diff": "Satan's Bolete has RED pores and turns blue when cut. Porcini has WHITE/YELLOW pores and does NOT turn blue."}
        ],
        "confusion_notes": "EXPERT ID ONLY. Porcini has WHITE pores (not gills), a thick stem with net pattern, and a nutty smell. If pores are RED or the flesh turns BLUE, do NOT eat."
    },
    {
        "name": "Field Blewit",
        "latin_name": "Lepista personata",
        "category": "Fungi",
        "months": ["October", "November", "December"],
        "habitat": "Grassland, Pastures, Gardens",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Cap, Stem",
        "warnings": "Must be cooked. Do NOT eat with alcohol.",
        "description": "**Identification:** Buff/tan cap with a smooth surface. Lilac-blue stem (distinctive). White to pale lilac gills. Appears late in the season.",
        "id_keys": {
            "Cap": "Buff/tan, smooth, convex then flat",
            "Gills": "White to pale lilac, crowded",
            "Stem": "LILAC-BLUE (distinctive, key feature)"
        },
        "foraging_tips": {
            "where": "Grassland, pastures, gardens.",
            "when": "Late Autumn to early Winter.",
            "sustainable": "Cut stem.",
            "danger_zone": "Must be cooked. Do NOT consume with alcohol."
        },
        "lookalikes": [
            {"name": "Wood Blewit", "danger": "EDIBLE", "diff": "Wood Blewit has a lilac cap AND stem. Field Blewit has a BROWN cap and LILAC stem."},
            {"name": "Cortinarius species", "danger": "POISONOUS", "diff": "Cortinarius species have a rusty spore print and web-like veil (cortina). Blewits have a pale pinkish spore print and NO cortina."}
        ],
        "confusion_notes": "Field Blewit has a BROWN cap and LILAC-BLUE stem. The lilac stem is the key identifier. Must be cooked. Do NOT eat with alcohol."
    },
    {
        "name": "Horn of Plenty",
        "latin_name": "Craterellus cornucopioides",
        "category": "Fungi",
        "months": ["August", "September", "October", "November"],
        "habitat": "Woodlands (Oak, Beech)",
        "regions": ["Southern", "Central"],
        "difficulty": 2,
        "parts": "Whole fungus",
        "warnings": "Must be washed thoroughly (traps dirt). Must be cooked.",
        "description": "**Identification:** Dark brown/black, funnel-shaped or horn-shaped. Smooth inside, wavy edges. Looks like a dark trumpet or horn of plenty.",
        "id_keys": {
            "Shape": "Funnel/horn shape, dark brown/black",
            "Inside": "Smooth, dark grey/brown",
            "Outside": "Wavy, rougher, dark brown/black"
        },
        "foraging_tips": {
            "where": "Oak and beech woodland floor.",
            "when": "Autumn.",
            "sustainable": "Cut at base.",
            "danger_zone": "Safe. Distinctive shape. Must be washed very thoroughly as it traps dirt."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The dark horn/trumpet shape is unique. No dangerous lookalikes."}
        ],
        "confusion_notes": "Safe. The dark horn/trumpet shape on the woodland floor is distinctive. No dangerous lookalikes. Often called 'Trompette de la Mort' (Trumpet of the Dead)."
    },
    {
        "name": "Deceiver",
        "latin_name": "Laccaria laccata",
        "category": "Fungi",
        "months": ["July", "August", "September", "October", "November"],
        "habitat": "Woodlands, Heathlands",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Whole mushroom",
        "warnings": "Variable colour — 'deceives' identification. Must be cooked.",
        "description": "**Identification:** Small, variable-coloured mushroom (pinkish-brown to dull tan). Widely spaced gills that are often pinkish. Thin, fibrous stem. Very common.",
        "id_keys": {
            "Cap": "Small, pinkish-brown to dull tan, variable (hence 'deceiver')",
            "Gills": "Widely spaced, pinkish, attached to stem",
            "Stem": "Thin, fibrous, same colour as cap or paler"
        },
        "foraging_tips": {
            "where": "Woodland and heathland, often in large groups.",
            "when": "Summer to Autumn.",
            "sustainable": "Cut stem.",
            "danger_zone": "Safe but variable appearance. Cook before eating."
        },
        "lookalikes": [
            {"name": "Amethyst Deceiver", "danger": "EDIBLE", "diff": "Amethyst Deceiver is clearly PURPLE. Deceiver is pinkish-brown/tan."},
            {"name": "Funnel Cap", "danger": "VARIES", "diff": "Some Clitocybe species can be toxic. Deceiver has widely spaced pinkish gills and a thin fibrous stem."}
        ],
        "confusion_notes": "Safe when confident. Called 'Deceiver' because its colour varies. Look for widely spaced pinkish gills and thin fibrous stem."
    },
    {
        "name": "Common Inkcap",
        "latin_name": "Coprinopsis atramentaria",
        "category": "Fungi",
        "months": ["June", "July", "August", "September", "October"],
        "habitat": "Grassland, Gardens, Disturbed ground",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Cap only (young)",
        "warnings": "EDIBLE but POISONOUS WITH ALCOHOL. Do NOT drink alcohol within 48 hours.",
        "description": "**Identification:** Grey-brown cap, oval when young then expanding. Gills start white, turn pink, then black, then dissolve into ink. Often in large clusters.",
        "id_keys": {
            "Cap": "Grey-brown, oval when young, expanding flat",
            "Gills": "White → Pink → Black → Dissolving into ink",
            "Habitat": "Disturbed ground, gardens, grass, often in large groups"
        },
        "foraging_tips": {
            "where": "Gardens, disturbed ground, grass.",
            "when": "Summer to Autumn.",
            "sustainable": "Cut young caps.",
            "danger_zone": "CRITICAL: EDIBLE but causes SEVERE illness if consumed with ALCOHOL. Do NOT drink alcohol within 48 hours of eating."
        },
        "lookalikes": [
            {"name": "Shaggy Inkcap", "danger": "EDIBLE", "diff": "Shaggy Inkcap is tall, white, shaggy, and has a moveable ring. Common Inkcap is shorter, grey-brown, smooth, and has NO moveable ring."}
        ],
        "confusion_notes": "CRITICAL: Common Inkcap is EDIBLE but causes SEVERE illness if consumed with ALCOHOL. Do NOT drink alcohol for 48 hours before or after eating. Shaggy Inkcap is safe with alcohol."
    },
    {
        "name": "Beefsteak Fungus",
        "latin_name": "Fistulina hepatica",
        "category": "Fungi",
        "months": ["August", "September", "October", "November"],
        "habitat": "Base and trunk of oak trees, occasionally sweet chestnut",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Fruiting body (slice and cook)",
        "warnings": "Must be cooked thoroughly — do not eat raw. Can be tough; slice thinly. Young specimens are more tender. Some people are sensitive — try a small amount first. Only collect from healthy-looking trees.",
        "description": "**Identification:** Large, tongue-shaped or fan-shaped bracket fungus, 10-30cm across. Upper surface is deep red-brown, rough, resembling raw meat. Underside is pale yellow with tiny pores (tubes), not gills. Exudes a red juice when cut. Flesh is thick, reddish, with pale marbling. Found on oak trunks and at the base of living oak trees. **Uses:** Slice thinly and cook long and slow in butter. Tastes slightly acidic, lemony, with a meaty texture. Often used as a meat substitute. Best when young and tender. The red juice can stain clothes.",
        "id_keys": {
            "Shape": "Large tongue or fan-shaped bracket, 10-30cm, sticking out horizontally from oak trunks",
            "Colour": "Deep red-brown upper surface, resembling raw beef — very distinctive",
            "Pores": "Underside has tiny pale yellow pores (tubes), NOT gills — key distinction from gilled mushrooms",
            "Juice": "Exudes red juice when cut or broken — unique among UK fungi",
            "Flesh": "Thick, reddish meat-like flesh with pale marbling, resembling steak"
        },
        "foraging_tips": {
            "where": "On oak trunks and at the base of living oak trees, occasionally on sweet chestnut",
            "when": "August to November, best in September-October",
            "sustainable": "Cut slices from the outer edge of young specimens. Leave older, tough specimens",
            "danger_zone": "⚠️ Must be cooked thoroughly — never eat raw. Slice thinly and cook long and slow"
        },
        "lookalikes": [
            {
                "name": "Other red bracket fungi (e.g., Ganoderma species)",
                "danger": "SAFE",
                "diff": "Ganoderma brackets have a lacquered, shiny upper surface and are woody/hard; Beefsteak Fungus is soft, fleshy, and exudes red juice when cut"
            }
        ],
        "confusion_notes": "Beefsteak Fungus is one of the easiest fungi to identify — its raw-meat appearance, red juice, and pore underside (not gills) make it unmistakable. No dangerous lookalikes."
    },
    {
        "name": "Dryad's Saddle",
        "latin_name": "Ceriolopsis squamosus",
        "category": "Fungi",
        "months": ["May", "June", "July", "August", "September", "October", "November"],
        "habitat": "Dead and dying hardwood trees, especially elm, beech, and oak",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Young, soft outer edges only",
        "warnings": "Only the young, soft outer edges are edible — older parts become tough and leathery. Must be cooked thoroughly. Some people find it causes mild stomach upset — try a small amount first. Do not eat raw.",
        "description": "**Identification:** Large, fan-shaped bracket fungus, 10-50cm across. Upper surface is cream-tan with dark brown overlapping scales, resembling a feather pattern. Underside is white with large, irregular pores. Stalk is thick, lateral, black-brown at the base. Flesh is white, thick, and smells strongly of watermelon rind or cucumber when fresh. **Uses:** Only the young, soft outer margin is worth eating. Slice thinly and cook in butter or add to soups. Has a mild cucumber/watermelon scent. Best when very young — older specimens become tough and inedible.",
        "id_keys": {
            "Shape": "Large fan-shaped bracket, 10-50cm, often overlapping in tiers",
            "Upper surface": "Cream-tan background with dark brown overlapping scales — distinctive feather-like pattern",
            "Pores": "Large, irregular, white to cream pores on the underside — NOT gills. Pores are 1-3mm wide",
            "Smell": "Strong, pleasant scent of watermelon rind or cucumber when fresh — key ID feature",
            "Flesh": "White, thick, fibrous. Young specimens are soft; older ones become tough and leathery"
        },
        "foraging_tips": {
            "where": "On dead and dying hardwood trees and stumps, especially elm, beech, and oak",
            "when": "May to November — one of the first edible bracket fungi of the year (appears in spring)",
            "sustainable": "Cut only the soft outer edges of young specimens. Leave older, tough specimens on the tree",
            "danger_zone": "⚠️ Only eat the young, soft outer margin. Older parts are too tough. Must be cooked thoroughly. Try a small amount first"
        },
        "lookalikes": [
            {
                "name": "Other large bracket fungi",
                "danger": "SAFE",
                "diff": "Most other large brackets are woody/leathery and inedible, but not poisonous. Dryad's Saddle is identified by its feather-like scales, large pores, and watermelon/cucumber smell"
            }
        ],
        "confusion_notes": "Dryad's Saddle is distinctive with its feather-patterned upper surface, large pores, and watermelon/cucumber scent. No dangerous lookalikes. The main issue is palatability — only young, soft specimens are worth eating."
    },
    {
        "name": "Shaggy Parasol",
        "latin_name": "Chlorophyllum rhacodes",
        "category": "Fungi",
        "months": ["August", "September", "October", "November"],
        "habitat": "Woodland edges, hedgerows, gardens, grassland near trees",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Cap and stem (young specimens best)",
        "warnings": "⚠️ Must be cooked thoroughly — NEVER eat raw. Some people are sensitive to Shaggy Parasols and get stomach upset even when cooked. Try a small amount first. The cut flesh turns bright orange-red — this is normal and NOT a sign of poisoning. Do NOT confuse with the poisonous Green-spored Parasol (not found in UK) or with immature Amanita species.",
        "description": "**Identification:** Large mushroom, cap 10-20cm across when expanded. Young caps are egg-shaped and covered in shaggy, upturned brown scales on a white background. Stem is thick, white, with a large, movable ring. Gills are white, turning cream. Flesh turns bright orange-red when cut or bruised — a key ID feature. Smells pleasant, mushroomy. **Uses:** Slice and cook thoroughly in butter. Excellent flavour, meaty texture. Good in risottos, soups, and pasta dishes. Must be cooked — never eat raw.",
        "id_keys": {
            "Cap": "Large (10-20cm), covered in shaggy, upturned brown scales on white background. Egg-shaped when young",
            "Stem": "Thick, white, with a large movable ring. Bulbous base but NO volva (cup at base)",
            "Gills": "White, turning cream. NOT green or greenish",
            "Flesh reaction": "Cut flesh turns bright orange-red — distinctive and important for identification",
            "Smell": "Pleasant, mushroomy smell"
        },
        "foraging_tips": {
            "where": "Woodland edges, hedgerows, gardens, and grassland near trees — likes disturbed ground",
            "when": "August to November, especially after warm rain in autumn",
            "sustainable": "Cut at base with a knife. Only take young, firm specimens. Leave some for spore dispersal",
            "danger_zone": "⚠️ Must cook thoroughly. Some people get stomach upset — try a small amount first. Do NOT confuse with Amanita species (check for volva/bag at base)"
        },
        "lookalikes": [
            {
                "name": "Parasol Mushroom (Macrolepiota procera)",
                "danger": "EDIBLE",
                "diff": "Parasol has a smooth, snakeskin-patterned stem (not shaggy), brown colour pattern on cap (not shaggy scales), and flesh does NOT turn orange-red when cut"
            },
            {
                "name": immature Amanita species (e.g., Amanita citrina)",
                "danger": "POISONOUS",
                "diff": "Young Amanitas are egg-shaped but have a VOLVA (bag/cup at the base of the stem) and do NOT have shaggy brown scales. Always dig up the base to check for a volva"
            }
        ],
        "confusion_notes": "⚠️ The bright orange-red flesh reaction is a key identifier. CRITICAL: Always check the base of the stem — Shaggy Parasol has NO volva (bag/cup). If you find a volva, it could be a deadly Amanita. Also, some people are sensitive to Shaggy Parasol even when cooked."
    },
    {
        "name": "Velvet Shank",
        "latin_name": "Flammulina velutipes",
        "category": "Fungi",
        "months": ["October", "November", "December", "January", "February", "March"],
        "habitat": "Dead and dying deciduous wood, especially elm, ash, and beech",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Caps and upper stems (discard tough lower stem)",
        "warnings": "Must be cooked — do not eat raw. Only collect from dead wood, never from the ground. Do NOT confuse with poisonous species of Galerina or Tubaria which grow in similar habitats. Always check gill attachment and stem features.",
        "description": "**Identification:** Small-medium mushroom, cap 2-8cm, orange-brown to dark brown, slimy when wet, smooth when dry. Gills are pale yellow-white, attached to the stem (adnate). Stem is tough, dark brown to black from the base upward, with a velvety texture. No ring. Grows in clusters on dead wood, even through snow and frost — one of the few mushrooms fruiting in midwinter. **Uses:** Cook thoroughly in stir-fries, soups, and stews. Discard the tough lower stems. Mild, pleasant flavour. Related to the cultivated Enoki mushroom.",
        "id_keys": {
            "Cap": "Orange-brown to dark brown, 2-8cm, slimy when wet, smooth when dry",
            "Gills": "Pale yellow-white, broadly attached to stem (adnate), NOT free",
            "Stem": "Tough, dark brown to black from base upward, velvety texture, NO ring",
            "Habitat": "Grows in tufted clusters on dead deciduous wood — especially elm, ash, beech",
            "Season": "One of the few mushrooms fruiting through winter — a key seasonal indicator"
        },
        "foraging_tips": {
            "where": "Dead and dying deciduous wood — stumps, fallen branches, standing dead trees",
            "when": "October to March — one of the best winter mushrooms. Can fruit through snow and frost",
            "sustainable": "Cut caps from stems. Leave some clusters to release spores. Discard tough lower stems",
            "danger_zone": "⚠️ CRITICAL: Do NOT confuse with Galerina species (DEADLY). Check: Velvet Shank has adnate gills, slimy cap, velvety dark stem, and grows on wood in winter"
        },
        "lookalikes": [
            {
                "name": "Funeral Bell / Deadly Galerina (Galerina marginata)",
                "danger": "DEADLY",
                "diff": "Funeral Bell has a RING on the stem, brown gills (not white-yellow), and a brown cap that is NOT slimy. Velvet Shank has NO ring, pale yellow-white gills, and a slimy cap"
            },
            {
                "name": "Sheathed Woodtuft (Kuehneromyces mutabilis)",
                "danger": "EDIBLE",
                "diff": "Very similar appearance. Sheathed Woodtuft has a ring on the stem and grows in tufts on wood. Requires expert ID to distinguish from Deadly Galerina — NOT recommended for beginners"
            }
        ],
        "confusion_notes": "⚠️ CRITICAL: Velvet Shank can be confused with DEADLY Galerina species. Key differences: Velvet Shank has NO ring, slimy cap, and pale gills. Galerina has a ring, brown spores/gills, and is not slimy. If in ANY doubt, do not eat."
    },
    {
        "name": "Charcoal Burner",
        "latin_name": "Russula cyanoxantha",
        "category": "Fungi",
        "months": ["June", "July", "August", "September", "October"],
        "habitat": "Broadleaf woodland, especially under beech and oak",
        "regions": ["All"],
        "difficulty": 3,
        "parts": "Cap and stem",
        "warnings": "⚠️ Russula identification requires experience. The Charcoal Burner is one of the safest Russulas due to its mild taste, but if you are not confident identifying Russulas, do NOT eat any of them. Some Russula species cause severe stomach upset. Always do a taste test on a tiny piece (spit it out).",
        "description": "**Identification:** Medium-large mushroom, cap 5-15cm. Cap colour is highly variable — can be grey-green, lilac, purple, brown, olive, or a mix. The key feature: cap surface is greasy/slippery, and the gills are FORKED, soft, and flexible (they bend like wax without breaking). Stem is white, turning greyish with age. Taste is MILD — not peppery or hot. **Uses:** Cook and eat in any mushroom dish. Firm, mild flavour. Must be cooked. Good fried, in risottos, and mixed mushroom dishes.",
        "id_keys": {
            "Cap": "Highly variable colour (grey-green, lilac, purple, olive, brown, or mixed), 5-15cm, greasy surface",
            "Gills": "White, FORKED (branching), soft and flexible — they bend like wax without breaking. This is the KEY feature",
            "Stem": "White, turning greyish with age, no ring",
            "Taste": "MILD — not peppery or hot. A tiny piece chewed and spat out should taste completely neutral",
            "Spore print": "White"
        },
        "foraging_tips": {
            "where": "Broadleaf woodland, especially under beech and oak on light, dry soils",
            "when": "June to October — one of the first Russulas to appear",
            "sustainable": "Cut at base with a knife. Only take firm, young specimens",
            "danger_zone": "⚠️ Russula ID requires experience. If in doubt, do NOT eat. Always do a tiny taste test (chew, spit out) — any peppery or hot taste means REJECT. Only eat if taste is completely mild"
        },
        "lookalikes": [
            {
                "name": "Sickener (Russula emetica)",
                "danger": "POISONOUS",
                "diff": "Sickener has a bright red cap, white brittle gills (not forked, not flexible), and a PEPPERY/ACRID taste. Charcoal Burner has variable cap colour, forked flexible gills, and MILD taste"
            },
            {
                "name": "Other Russula species",
                "danger": "MEDIUM",
                "diff": "Many Russulas look similar. The taste test is key: MILD = safe to try, PEPPERY = reject. Charcoal Burner is distinguished by forked, flexible gills and mild taste"
            }
        ],
        "confusion_notes": "⚠️ Russulas are a challenging group. The Charcoal Burner is one of the safest due to its mild taste and flexible, forked gills. If you are NOT confident with Russula identification, leave ALL Russulas alone. Any peppery taste = REJECT."
    },
    {
        "name": "Scarlet Elf Cup",
        "latin_name": "Sarcoscypha austriaca",
        "category": "Fungi",
        "months": ["January", "February", "March", "April", "November", "December"],
        "habitat": "Dead deciduous wood, especially fallen branches and twigs in damp woodland",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Entire fruiting body (cup)",
        "warnings": "Rinse thoroughly to remove debris. Cook before eating. Some people eat them raw in salads but cooking is safer. Ensure correct identification — only Sarcoscypha species with bright red cups on dead wood are safe.",
        "description": "**Identification:** Small to medium cup-shaped fungus, 1-5cm across. Inner surface is bright, vivid scarlet red and smooth. Outer surface is paler, pinkish-white, and slightly felty. Short stem attaches to dead wood. Grows on fallen deciduous branches and twigs in damp woodland, often partially buried in leaf litter. One of the few brightly coloured fungi that is safe. **Uses:** Cook in butter, add to soups, risottos, or stir-fries. Can be used raw as a striking salad garnish. Mild, slightly earthy flavour. Visually stunning on the plate.",
        "id_keys": {
            "Cup": "Bright scarlet red inner surface, smooth and shiny, 1-5cm across",
            "Outer surface": "Paler, pinkish-white, slightly felty or hairy",
            "Habitat": "On dead deciduous wood — fallen branches, twigs, sticks in damp woodland",
            "Season": "Winter to early spring — one of very few bright fungi fruiting in January-February"
        },
        "foraging_tips": {
            "where": "Damp woodland, on fallen deciduous branches and twigs partially buried in leaf litter",
            "when": "November to April — peak in January to March. A winter foraging speciality",
            "sustainable": "Cut with scissors or a knife. Leave small cups to grow. They regrow from the same wood",
            "danger_zone": "⚠️ Only collect bright red cups growing on dead wood. Rinse thoroughly — cups often hold debris and tiny insects"
        },
        "lookalikes": [
            {
                "name": "Sarcoscypha coccinea (Scarlet Elf Cup)",
                "danger": "EDIBLE",
                "diff": "Very similar — also edible. Microscopic examination needed to distinguish S. austriaca from S. coccinea. Both are safe to eat"
            }
        ],
        "confusion_notes": "Scarlet Elf Cups are easy to identify — bright scarlet cup-shaped fungi on dead wood in winter. There are no dangerous lookalikes with this combination of features. Both UK Sarcoscypha species are edible."
    }
]
