# data/edible_coastal.py
# Auto-generated by split_plants.py
# 7 Coastal plants

EDIBLE_COASTAL = [
    {
        "name": "Sea Purslane",
        "latin_name": "Halimione portulacoides",
        "category": "Coastal",
        "months": ['May', 'June', 'July', 'August', 'September'],
        "habitat": "Coastal Saltmarsh, Shingle",
        "regions": ['Coastal'],
        "difficulty": 1,
        "parts": "Leaves",
        "warnings": "Salty! Use as seasoning.",
        "description": "**Identification:** Grey-green fleshy leaves, woody stems. Grows near Samphire.",
        "id_keys": {
            "Leaves": "Succulent, grey-green, oblong",
            "Stem": "Woody at base",
            "Taste": "Very salty",
        },
        "foraging_tips": {
            "where": "Coastal saltmarsh, shingle.",
            "when": "Spring to Autumn.",
            "sustainable": "Pick sparingly in protected areas.",
            "danger_zone": "Safe. Distinctive grey colour.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive grey-green colour and salty taste.",
            },
        ],
        "confusion_notes": "Safe. Distinctive grey colour.",
    },
    {
        "name": "Alexanders",
        "latin_name": "Smyrnium olusatrum",
        "category": "Coastal",
        "months": ['March', 'April', 'May'],
        "habitat": "Coastal, Hedgerows (near sea)",
        "regions": ['Coastal'],
        "difficulty": 2,
        "parts": "Stems, Roots, Flower buds",
        "warnings": "Seasonal - best in Spring.",
        "description": "**Identification:** Tall plant, yellow-green flowers, shiny green leaves. Smells of celery/parsley.",
        "id_keys": {
            "Stem": "Solid, green (not hollow like hemlock)",
            "Flowers": "Yellow-green umbels",
            "Smell": "Celery-like",
        },
        "foraging_tips": {
            "where": "Coastal hedgerows, near sea.",
            "when": "Spring.",
            "sustainable": "Common on coast, rarer inland.",
            "danger_zone": "Check for purple spotted stems (Hemlock).",
        },
        "lookalikes": [
            {
                "name": "Hemlock",
                "danger": "POISONOUS",
                "diff": "Hemlock has purple spots on stem and smells of mouse urine. Alexanders is green and smells of celery.",
            },
        ],
        "confusion_notes": "CRITICAL: Alexanders has a solid GREEN stem and smells of celery. Hemlock has PURPLE SPOTS and smells of mouse urine.",
    },
    {
        "name": "Sea Beet",
        "latin_name": "Beta vulgaris maritima",
        "category": "Coastal",
        "months": ['May', 'June', 'July', 'August', 'September'],
        "habitat": "Coastal Cliffs, Shingle",
        "regions": ['Coastal'],
        "difficulty": 1,
        "parts": "Leaves",
        "warnings": "Wild ancestor of beetroot. Tasty.",
        "description": "**Identification:** Dark green, shiny leaves (like spinach). Grows on cliffs. Stems often reddish.",
        "id_keys": {
            "Leaves": "Dark green, shiny, triangular/oval",
            "Stem": "Often red/striped",
            "Habitat": "Coastal cliffs",
        },
        "foraging_tips": {
            "where": "Cliffs, shingle, coastal paths.",
            "when": "Spring - Autumn.",
            "sustainable": "Pick young leaves.",
            "danger_zone": "Safe. Wash to remove salt.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive coastal habitat.",
            },
        ],
        "confusion_notes": "Safe. Wild ancestor of beetroot. Cook like spinach. Wash to remove salt.",
    },
    {
        "name": "Marsh Samphire",
        "latin_name": "Salicornia europaea",
        "category": "Coastal",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Coastal Saltmarsh",
        "regions": ['Coastal'],
        "difficulty": 1,
        "parts": "Stems",
        "warnings": "Very salty. Best boiled or steamed. Do not overcook.",
        "description": "**Identification:** Green, jointed, fleshy stems that look like miniature cactus without the spines. Grows on mud.",
        "id_keys": {
            "Stem": "Fleshy, jointed, like a string of beads",
            "Habitat": "Saltmarsh, tidal mud",
            "Taste": "Very salty",
        },
        "foraging_tips": {
            "where": "Coastal saltmarsh.",
            "when": "Summer.",
            "sustainable": "Snip tops off, leave roots.",
            "danger_zone": "Safe. Known as 'Sea Asparagus'.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive jointed fleshy stems.",
            },
        ],
        "confusion_notes": "Safe. Known as 'Sea Asparagus'. Very distinctive — grows on saltmarshes and tastes salty.",
    },
    {
        "name": "Sea Kale",
        "latin_name": "Crambe maritima",
        "category": "Coastal",
        "months": ['March', 'April', 'May'],
        "habitat": "Coastal Shingle, Sand",
        "regions": ['Coastal'],
        "difficulty": 2,
        "parts": "Young shoots, Leaves",
        "warnings": "Protected in the wild. Grow from seed or pick sparingly.",
        "description": "**Identification:** Blue-green, waxy leaves. Crinkled edges. Thick shoots.",
        "id_keys": {
            "Leaves": "Blue-green, waxy, large, crinkled",
            "Habitat": "Shingle beaches",
            "Flowers": "White, 4 petals",
        },
        "foraging_tips": {
            "where": "Shingle beaches.",
            "when": "Spring.",
            "sustainable": "PROTECTED. Pick sparingly or grow your own.",
            "danger_zone": "Safe but protected.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive blue-green waxy leaves on shingle.",
            },
        ],
        "confusion_notes": "Safe but protected. Identify by the blue-green waxy leaves on shingle beaches.",
    },
    {
        "name": "Rock Samphire",
        "latin_name": "Crithmum maritimum",
        "category": "Coastal",
        "months": ['May', 'June', 'July', 'August'],
        "habitat": "Coastal Cliffs",
        "regions": ['Coastal'],
        "difficulty": 2,
        "parts": "Leaves, Stems",
        "warnings": "Strong, aromatic flavour. Often pickled.",
        "description": "**Identification:** Fleshy, green, carrot-like leaves growing on sea cliffs. Smells of carrots/aniseed.",
        "id_keys": {
            "Leaves": "Fleshy, divided, carrot-like",
            "Habitat": "Cliff faces, rocks by the sea",
            "Smell": "Carrot/aniseed",
        },
        "foraging_tips": {
            "where": "Cliff faces (DANGER: Do not risk falling).",
            "when": "Summer.",
            "sustainable": "Cut stems, leave roots.",
            "danger_zone": "CRITICAL: Do NOT climb dangerous cliffs for it.",
        },
        "lookalikes": [
            {
                "name": "Marsh Samphire",
                "danger": "EDIBLE",
                "diff": "Marsh Samphire grows on mud and has jointed stems. Rock Samphire grows on cliffs.",
            },
        ],
        "confusion_notes": "Safe but grows on dangerous cliffs. Distinctive carrot-like leaves and aniseed smell.",
    },
    {
        "name": "Sea Aster",
        "latin_name": "Tripolium pannonicum",
        "category": "Coastal",
        "months": ['July', 'August', 'September'],
        "habitat": "Coastal Saltmarsh",
        "regions": ['Coastal'],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Salty. Good raw or cooked.",
        "description": "**Identification:** Looks like a daisy/aster. Lilac petals with yellow centre. Fleshy, linear leaves.",
        "id_keys": {
            "Flowers": "Lilac/blue petals, yellow centre",
            "Leaves": "Fleshy, linear, salty",
            "Habitat": "Saltmarshes",
        },
        "foraging_tips": {
            "where": "Saltmarshes.",
            "when": "Summer/Autumn.",
            "sustainable": "Pick young leaves.",
            "danger_zone": "Safe. Very distinct.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive lilac daisy on saltmarsh.",
            },
        ],
        "confusion_notes": "Safe. Distinctive lilac daisy-like flower growing on saltmarshes.",
    },
        {
        "name": "Sea Lettuce",
        "latin_name": "Ulva lactuca",
        "category": "Seaweed",
        "months": ["May", "June", "July", "August", "September"],
        "habitat": "Coastal Rocks, Shallow water",
        "regions": ["Coastal"],
        "difficulty": 1,
        "parts": "Whole frond",
        "warnings": "Wash well. Can be eaten raw or cooked.",
        "description": "**Identification:** Bright green, thin, translucent sheets. Looks like lettuce leaves. Grows on rocks and in shallow water.",
        "id_keys": {
            "Colour": "Bright green, translucent",
            "Shape": "Flat sheets, like lettuce leaves",
            "Texture": "Thin, delicate"
        },
        "foraging_tips": {
            "where": "Rocks, rock pools, shallow water.",
            "when": "Spring to Autumn.",
            "sustainable": "Snip above holdfast. Wash thoroughly.",
            "danger_zone": "Safe. Very distinctive bright green colour."
        },
        "lookalikes": [
            {"name": "Green Sea Hair", "danger": "EDIBLE", "diff": "Green Sea Hair is filamentous (hair-like). Sea Lettuce is flat sheets."}
        ],
        "confusion_notes": "Safe. Bright green, flat, translucent sheets. The most recognisable seaweed."
    },
    {
        "name": "Mussels",
        "latin_name": "Mytilus edulis",
        "category": "Shellfish",
        "months": ["September", "October", "November", "January", "February", "March", "April"],
        "habitat": "Coastal Rocks, Estuaries",
        "regions": ["Coastal"],
        "difficulty": 2,
        "parts": "Whole animal",
        "warnings": "Must be from clean water. Check for red tide warnings. Cook thoroughly. Only collect in months with an 'R'.",
        "description": "**Identification:** Dark blue/black bivalve shell. Elongated, pointed at one end. Grows in dense clusters on rocks and piers.",
        "id_keys": {
            "Shell": "Dark blue/black, elongated, pointed at one end",
            "Habitat": "Dense clusters on rocks, piers, ropes",
            "Size": "5-10cm long"
        },
        "foraging_tips": {
            "where": "Rocks, piers, ropes in clean water.",
            "when": "Months with an 'R' (Sept-Apr). Avoid summer.",
            "sustainable": "Only take sizes over 5cm. Pull from rocks carefully.",
            "danger_zone": "CRITICAL: Check water quality and red tide warnings. Cook thoroughly."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "EDIBLE", "diff": "Mussels are distinctive. No dangerous shellfish look like mussels in the UK."}
        ],
        "confusion_notes": "Safe from clean water. Only collect in months with an 'R'. Check for red tide warnings. Cook thoroughly."
    },
]
