# data/edible_shellfish.py
# Auto-generated by split_plants.py
# 1 Coastal plants

EDIBLE_SHELLFISH = [
    {
        "name": "Cockles",
        "latin_name": "Cerastoderma edule",
        "category": "Shellfish",
        "months": ['July', 'August', 'September'],
        "habitat": "Coastal Estuaries, Sand",
        "regions": ['Coastal'],
        "difficulty": 2,
        "parts": "Whole animal",
        "warnings": "Must be from clean water. Check for red tide warnings.",
        "description": "**Identification:** Bivalve shell with deep ribs. Heart shape when viewed from end.",
        "id_keys": {
            "Shell": "Ribbed, symmetrical, heart-shaped profile",
            "Colour": "Pale brown/yellow",
            "Habitat": "Sandy/muddy estuaries",
        },
        "foraging_tips": {
            "where": "Sandy estuaries.",
            "when": "Summer.",
            "sustainable": "Only take sizes over 20mm.",
            "danger_zone": "CRITICAL: Check water quality and red tide warnings.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "EDIBLE",
                "diff": "Other similar bivalves (like clams) are edible if from clean water.",
            },
        ],
        "confusion_notes": "Safe. Distinctive ribbed shell, heart shape. Check for red tide warnings before collecting.",
    },
]
