# data/edible_plants.py
# Auto-generated by split_plants.py
# 24 Coastal plants

EDIBLE_PLANTS = [
    {
        "name": "Wild Strawberry",
        "latin_name": "Fragaria vesca",
        "category": "Plant",
        "months": ['June', 'July', 'August'],
        "habitat": "Woodlands, Grassland",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries, Leaves",
        "warnings": "Small yield but intense flavour.",
        "description": "**Identification:** Low growing, trifoliate leaves (3 leaflets), small red berries pointing upwards.",
        "id_keys": {
            "Leaves": "3 leaflets, toothed",
            "Flowers": "White, 5 petals",
            "Fruit": "Small, red, seeds on outside",
        },
        "foraging_tips": {
            "where": "Woodlands, grassland, tracks.",
            "when": "Summer.",
            "sustainable": "Pick ripe berries only.",
            "danger_zone": "Ensure correct identification to avoid Barren Strawberry.",
        },
        "lookalikes": [
            {
                "name": "Barren Strawberry",
                "danger": "INEDIBLE",
                "diff": "Barren Strawberry has petals with gaps between them. Wild Strawberry petals overlap.",
            },
        ],
        "confusion_notes": "Confused with Barren Strawberry. **Key Diff:** Barren Strawberry has petals spaced apart (gaps show). Wild Strawberry petals overlap.",
    },
    {
        "name": "Meadowsweet",
        "latin_name": "Filipendula ulmaria",
        "category": "Plant",
        "months": ['June', 'July', 'August'],
        "habitat": "Damp Meadows, Riverbanks",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Flowers, Leaves",
        "warnings": "Contains aspirin-like compounds. Avoid if allergic to aspirin.",
        "description": "**Identification:** Tall, frothy cream-white flower heads. Smells of almond/honey.",
        "id_keys": {
            "Flowers": "Cream, frothy clusters",
            "Smell": "Almond/Honey scent",
            "Leaves": "Compound, white underside",
        },
        "foraging_tips": {
            "where": "Damp meadows, riverbanks.",
            "when": "Summer.",
            "sustainable": "Pick flower heads, leave plenty for pollinators.",
            "danger_zone": "Avoid if allergic to aspirin (salicylates).",
        },
        "lookalikes": [
            {
                "name": "Dropwort",
                "danger": "POISONOUS",
                "diff": "Dropwort grows on DRY ground. Meadowsweet loves DAMP ground.",
            },
        ],
        "confusion_notes": "Confused with Dropwort. **Key Diff:** Dropwort is usually on dry ground. Meadowsweet loves damp ground and smells sweet.",
    },
    {
        "name": "Chickweed",
        "latin_name": "Stellaria media",
        "category": "Plant",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Gardens, Waste Ground",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Stems",
        "warnings": "Eat raw or cooked. Very mild.",
        "description": "**Identification:** Low growing, small white star flowers, line of hairs on stem.",
        "id_keys": {
            "Stem": "Line of fine hairs (distinctive feature)",
            "Flowers": "Tiny white stars",
            "Leaves": "Oval, opposite pairs",
        },
        "foraging_tips": {
            "where": "Gardens, waste ground, fertile soil.",
            "when": "Year-round.",
            "sustainable": "Common weed, harvest freely.",
            "danger_zone": "Safe. Check for dog fouling in urban areas.",
        },
        "lookalikes": [
            {
                "name": "Mouse-ear Chickweed",
                "danger": "EDIBLE",
                "diff": "Mouse-ear is hairy and tough. Chickweed has a line of hairs on one side only.",
            },
        ],
        "confusion_notes": "Safe. Very common weed. Hairy mouse-ear chickweed is edible but texture is rough.",
    },
    {
        "name": "Burdock (Root)",
        "latin_name": "Arctium lappa",
        "category": "Plant",
        "months": ['September', 'October', 'November', 'December'],
        "habitat": "Hedgerows, Waste Ground",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Root (First year)",
        "warnings": "Requires digging. Look for first-year plants (no burrs/flowers).",
        "description": "**Identification:** Large rhubarb-like leaves, purple thistle-like flowers that turn into sticky burrs.",
        "id_keys": {
            "Leaves": "Large, heart-shaped, rhubarb-like",
            "Flowers": "Purple thistle, sticky burrs",
            "Root": "Long, thin, brown skin",
        },
        "foraging_tips": {
            "where": "Hedgerows, waste ground.",
            "when": "Autumn/Winter (first year roots).",
            "sustainable": "Digging kills the plant. Only dig where abundant.",
            "danger_zone": "Only eat roots from first-year plants (those without flowers/burrs).",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Large leaves and sticky burrs are distinctive.",
            },
        ],
        "confusion_notes": "Safe. Identify by the large leaves and sticky burrs. Only eat roots from first-year plants.",
    },
    {
        "name": "Pignut",
        "latin_name": "Bunium bulbocastanum",
        "category": "Plant",
        "months": ['May', 'June', 'July'],
        "habitat": "Grassland, Meadows",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Tubers",
        "warnings": "Dig carefully. Distinctive nutty taste.",
        "description": "**Identification:** Delicate plant with fine, feathery leaves (like carrot). Small white flower umbels.",
        "id_keys": {
            "Leaves": "Feathery, carrot-like, delicate",
            "Flowers": "White umbels",
            "Root": "Small tuber, brown/black skin",
        },
        "foraging_tips": {
            "where": "Dry meadows, grassland.",
            "when": "Late Spring/Summer.",
            "sustainable": "Dig carefully, refill holes.",
            "danger_zone": "CRITICAL: Check ground is DRY. Hemlock Water Dropwort (Deadly) grows in WET ground.",
        },
        "lookalikes": [
            {
                "name": "Hemlock Water Dropwort",
                "danger": "DEADLY",
                "diff": "Dropwort grows in WET ground/ditches. Pignut grows in DRY meadows.",
            },
        ],
        "confusion_notes": "CRITICAL: Pignut grows in DRY meadows. Hemlock Water Dropwort grows in WET ground. If your feet are wet, STOP digging.",
    },
    {
        "name": "Garlic Mustard (Jack-by-the-Hedge)",
        "latin_name": "Alliaria petiolata",
        "category": "Plant",
        "months": ['April', 'May', 'June'],
        "habitat": "Hedgerows, Woodlands, Roadsides",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Flowers, Roots",
        "warnings": "Smells of garlic. Invasive in some areas.",
        "description": "**Identification:** Heart-shaped leaves with toothed edges. White flowers. Smells of garlic when crushed.",
        "id_keys": {
            "Leaves": "Heart-shaped, toothed, garlic smell",
            "Flowers": "White, 4 petals (cross shape)",
            "Height": "Up to 1m",
        },
        "foraging_tips": {
            "where": "Hedgerows, woods, paths.",
            "when": "Spring.",
            "sustainable": "Invasive - pick freely.",
            "danger_zone": "Safe. Distinctive garlic smell.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Garlic smell is unique.",
            },
        ],
        "confusion_notes": "Safe. The garlic smell is the key identifier. If it smells of garlic, it is likely Garlic Mustard.",
    },
    {
        "name": "Cleavers (Goosegrass)",
        "latin_name": "Galium aparine",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June'],
        "habitat": "Hedgerows, Gardens, Waste Ground",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Stems, Seeds",
        "warnings": "Sticky/hairy texture. Best cooked or strained.",
        "description": "**Identification:** Straggly plant with hooked hairs that stick to clothes. Whorls of narrow leaves.",
        "id_keys": {
            "Texture": "Sticky (cleaves to clothes/fur)",
            "Leaves": "Whorls (circles) of 6-8 narrow leaves",
            "Stem": "Square, sticky",
        },
        "foraging_tips": {
            "where": "Everywhere.",
            "when": "Spring.",
            "sustainable": "Common weed. Pick freely.",
            "danger_zone": "Juice is good for lymphatic system. Cook like spinach.",
        },
        "lookalikes": [
            {
                "name": "None",
                "danger": "SAFE",
                "diff": "The sticky texture is unique.",
            },
        ],
        "confusion_notes": "Safe. The sticky texture makes it impossible to mistake. Cleaves to clothes and fur.",
    },
    {
        "name": "Ribwort Plantain",
        "latin_name": "Plantago lanceolata",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June', 'July', 'August'],
        "habitat": "Grassland, Paths, Lawns",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Seeds",
        "warnings": "Tough veins. Best eaten young.",
        "description": "**Identification:** Long, narrow, lance-shaped leaves with strong parallel veins. Brown flower head on a long stem.",
        "id_keys": {
            "Leaves": "Long, narrow, parallel veins",
            "Flower": "Brown oval/short spike on long stem",
            "Habitat": "Common in grass",
        },
        "foraging_tips": {
            "where": "Lawns, paths, fields.",
            "when": "Spring - Autumn.",
            "sustainable": "Common. Pick young leaves.",
            "danger_zone": "Safe. Seeds can be eaten like porridge.",
        },
        "lookalikes": [
            {
                "name": "Greater Plantain",
                "danger": "EDIBLE",
                "diff": "Rounder leaves. Also edible.",
            },
        ],
        "confusion_notes": "Safe. Very common. Long, narrow leaves with strong parallel veins.",
    },
    {
        "name": "Common Mallow",
        "latin_name": "Malva sylvestris",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Waste Ground, Roadsides, Gardens",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Flowers, Seeds (Cheeses)",
        "warnings": "Mucilaginous (slimy) texture. Good for thickening.",
        "description": "**Identification:** Large maple-like leaves. Purple flowers with darker stripes. Seeds look like tiny cheeses.",
        "id_keys": {
            "Leaves": "Maple-like, 5-7 lobes",
            "Flowers": "Purple, dark veins/stripes",
            "Seeds": "Flat, round discs (cheeses)",
        },
        "foraging_tips": {
            "where": "Waste ground, fields.",
            "when": "Summer.",
            "sustainable": "Pick leaves and flowers.",
            "danger_zone": "Safe. Mucilage is soothing for digestion.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Maple-like leaves and purple flowers.",
            },
        ],
        "confusion_notes": "Safe. Maple-like leaves and purple flowers. The 'cheese' shaped seeds are unique.",
    },
    {
        "name": "Sweet Violet",
        "latin_name": "Viola odorata",
        "category": "Plant",
        "months": ['February', 'March', 'April'],
        "habitat": "Woodlands, Hedgerows, Gardens",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Flowers, Leaves",
        "warnings": "Sweet scent. Do not confuse with Dog Violet (scentless).",
        "description": "**Identification:** Heart-shaped leaves. Deep purple (sometimes white) flowers with a sweet scent.",
        "id_keys": {
            "Flowers": "Purple/White, sweet scent",
            "Leaves": "Heart-shaped",
            "Smell": "Sweet, perfumed",
        },
        "foraging_tips": {
            "where": "Woodlands, old gardens.",
            "when": "Early Spring.",
            "sustainable": "Pick a few flowers. Leave leaves.",
            "danger_zone": "Dog Violet has no scent. Safe but tasteless.",
        },
        "lookalikes": [
            {
                "name": "Dog Violet",
                "danger": "EDIBLE",
                "diff": "No scent. Safe but not flavourful.",
            },
        ],
        "confusion_notes": "Safe. Use your nose! Sweet Violet has a sweet scent. Dog Violet has no scent — safe but not flavourful.",
    },
    {
        "name": "Ground Ivy",
        "latin_name": "Glechoma hederacea",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June'],
        "habitat": "Woodlands, Hedgerows, Lawns",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves",
        "warnings": "Strong minty aroma. Good for tea.",
        "description": "**Identification:** Creeping plant. Round, scalloped leaves. Purple trumpet flowers. Smells minty.",
        "id_keys": {
            "Leaves": "Round, scalloped, opposite pairs",
            "Stem": "Creeping (square)",
            "Smell": "Minty/Aromatic",
        },
        "foraging_tips": {
            "where": "Lawns, paths, woods.",
            "when": "Spring.",
            "sustainable": "Common. Pick freely.",
            "danger_zone": "Safe. Good tea substitute.",
        },
        "lookalikes": [
            {
                "name": "Dead-Nettle",
                "danger": "EDIBLE",
                "diff": "Dead-nettle has heart-shaped leaves. Ground Ivy has round/scalloped.",
            },
        ],
        "confusion_notes": "Safe. The minty smell on a creeping plant is distinct. Dead-Nettle has heart-shaped leaves; Ground Ivy has round/scalloped leaves.",
    },
    {
        "name": "Charlock",
        "latin_name": "Sinapis arvensis",
        "category": "Plant",
        "months": ['May', 'June', 'July', 'August'],
        "habitat": "Fields, Waste Ground, Arable Land",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Flowers, Seeds",
        "warnings": "Taste is hot/spicy (mustard). Use in moderation.",
        "description": "**Identification:** Bright yellow flowers (4 petals in a cross). Rough/hairy leaves. Seed pods are like small sausage shapes.",
        "id_keys": {
            "Flowers": "Yellow, 4 petals in a cross (Crucifer)",
            "Leaves": "Rough, hairy, lobed",
            "Stem": "Hairy",
            "Smell": "Hot/Mustardy when crushed",
        },
        "foraging_tips": {
            "where": "Fields, roadsides, arable land.",
            "when": "May - August.",
            "sustainable": "Common weed. Pick freely.",
            "danger_zone": "Can be spicy! Cook like spinach or use as seasoning.",
        },
        "lookalikes": [
            {
                "name": "Rape (Oilseed Rape)",
                "danger": "EDIBLE",
                "diff": "Tall, blue-green leaves. Yellow flowers. Edible but bitter.",
            },
            {
                "name": "Hedge Mustard",
                "danger": "EDIBLE",
                "diff": "Has a distinctive 'sauce' smell. Edible.",
            },
        ],
        "confusion_notes": "Safe. The Cabbage family (Brassicaceae) is generally safe in the UK. If it has 4 petals in a cross and smells mustardy, it is likely edible.",
    },
    {
        "name": "Shepherd's Purse",
        "latin_name": "Capsella bursa-pastoris",
        "category": "Plant",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Gardens, Fields, Paths, Waste Ground",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Seeds (peppery)",
        "warnings": "Seeds are peppery. Leaves best when young.",
        "description": "**Identification:** Rosette of leaves at base (dandelion-like). Tiny white flowers. Distinctive heart-shaped seed pods (purses).",
        "id_keys": {
            "Leaves": "Lobed, dandelion-like rosette (deep teeth)",
            "Flowers": "Tiny white, 4 petals",
            "Seeds": "Heart-shaped purses (distinctive)",
            "Height": "Low to medium (up to 40cm)",
        },
        "foraging_tips": {
            "where": "Everywhere. Gardens, paths, fields.",
            "when": "Year round (Best in Spring).",
            "sustainable": "Very common weed. Pick freely.",
            "danger_zone": "Seeds can be used as a pepper substitute.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive heart-shaped seed pods make it easy to ID.",
            },
        ],
        "confusion_notes": "Safe. One of the most common weeds. Look for the 'purse' shaped seed pods — that is unique.",
    },
    {
        "name": "Wild Garlic",
        "latin_name": "Allium ursinum",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June'],
        "habitat": "Woodlands, Riverbanks",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Flowers, Bulbs",
        "warnings": "Can be confused with poisonous plants if not smelled.",
        "description": "**Identification:** Broad, lance-shaped leaves. White star-like flowers. Smells strongly of garlic.",
        "id_keys": {
            "Leaves": "Lance-shaped, soft, parallel veins",
            "Flowers": "White, 6 petals, star-shaped",
            "Smell": "Strong garlic smell when crushed",
        },
        "foraging_tips": {
            "where": "Damp woodlands, riverbanks.",
            "when": "Spring.",
            "sustainable": "Pick leaves sparingly, leave flowers for bees.",
            "danger_zone": "Safe if it smells of garlic. If no smell, do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Lily of the Valley",
                "danger": "POISONOUS",
                "diff": "Lily of the Valley has leaves that come from a central stem and NO garlic smell.",
            },
            {
                "name": "Lords and Ladies",
                "danger": "POISONOUS",
                "diff": "Lords and Ladies has arrow-shaped leaves, often black spots, and NO garlic smell.",
            },
        ],
        "confusion_notes": "☠️ CRITICAL: Wild Garlic smells STRONGLY of garlic. If it doesn't smell of garlic, do NOT eat it. Lily of the Valley has NO garlic smell.",
    },
    {
        "name": "Nettles",
        "latin_name": "Urtica dioica",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June'],
        "habitat": "Woodlands, Gardens, Fields",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Young leaves (tops)",
        "warnings": "Must be cooked to destroy stingers. Wear gloves to pick!",
        "description": "**Identification:** Green, heart-shaped leaves with jagged edges. Covered in tiny stinging hairs.",
        "id_keys": {
            "Leaves": "Heart-shaped, heavily toothed, opposite pairs",
            "Stem": "Square stem, stinging hairs",
            "Sting": "Causes immediate burning rash",
        },
        "foraging_tips": {
            "where": "Everywhere (fertile soil).",
            "when": "Spring (young tops).",
            "sustainable": "Cut tops off, plant will regrow.",
            "danger_zone": "Wear gloves! Must be cooked to remove sting.",
        },
        "lookalikes": [
            {
                "name": "Dead-Nettle",
                "danger": "EDIBLE",
                "diff": "Dead-Nettles do not sting and have square stems with nettle-like leaves.",
            },
        ],
        "confusion_notes": "Safe. Dead-Nettles look similar but are soft and don't sting. If it stings, it's a Nettle (and edible when cooked).",
    },
    {
        "name": "Dandelion",
        "latin_name": "Taraxacum officinale",
        "category": "Plant",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Lawns, Fields, Roadsides",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Flowers, Roots",
        "warnings": "Leaves are bitter. Root makes a coffee substitute.",
        "description": "**Identification:** Rosette of jagged leaves. Yellow flower head on a hollow stem. Milky sap.",
        "id_keys": {
            "Leaves": "Lion's tooth (jagged), rosette at base",
            "Stem": "Hollow, exudes milky sap",
            "Flower": "Bright yellow, single head",
        },
        "foraging_tips": {
            "where": "Lawns, fields, paths.",
            "when": "Spring for leaves, Autumn for roots.",
            "sustainable": "Very common.",
            "danger_zone": "Bitter but safe.",
        },
        "lookalikes": [
            {
                "name": "Cat's Ear",
                "danger": "EDIBLE",
                "diff": "Cat's Ear has hairy leaves. Dandelion leaves are hairless.",
            },
        ],
        "confusion_notes": "Safe. Most lookalikes are edible. Identify by the hollow stem and milky sap.",
    },
    {
        "name": "Wild Carrot (Queen Anne's Lace)",
        "latin_name": "Daucus carota",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Grassland, Roadsides",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Root (1st year), Seeds",
        "warnings": "EXTREME CAUTION. Very easy to confuse with deadly Hemlock.",
        "description": "**Identification:** White lace-like flower head, often with a single red centre. Hairy stems. Carrot smell.",
        "id_keys": {
            "Flowers": "White umbels, flat-topped, red centre dot",
            "Stem": "HAIRY, green, NO purple spots",
            "Smell": "Smells of carrot when crushed",
        },
        "foraging_tips": {
            "where": "Dry grassland, roadsides.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Digging root kills plant.",
            "danger_zone": "☠️ CRITICAL: Must have HAIRY stems and smell of CARROT. If it has purple spots, do NOT touch.",
        },
        "lookalikes": [
            {
                "name": "Hemlock",
                "danger": "DEADLY",
                "diff": "Hemlock has SMOOTH stems with PURPLE SPOTS. Wild Carrot has HAIRY stems.",
            },
        ],
        "confusion_notes": "☠️ CRITICAL: Hemlock has SMOOTH stems with PURPLE SPOTS. Wild Carrot has HAIRY stems. If you see purple spots, do NOT touch it.",
    },
    {
        "name": "Three-Cornered Leek",
        "latin_name": "Allium triquetrum",
        "category": "Plant",
        "months": ['March', 'April', 'May'],
        "habitat": "Hedgerows, Woodlands, Roadsides",
        "regions": ['South West', 'Wales', 'Ireland'],
        "difficulty": 1,
        "parts": "Leaves, Flowers, Bulbs",
        "warnings": "Invasive in some areas. Very strong garlic/onion flavour.",
        "description": "**Identification:** Leaves are triangular in cross-section. White bell-shaped flowers with a green stripe.",
        "id_keys": {
            "Stem": "Triangular (3-cornered) in cross-section",
            "Flowers": "White bells with green stripe",
            "Smell": "Strong garlic/onion smell",
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland (South West).",
            "when": "Spring.",
            "sustainable": "Invasive — pick freely where allowed.",
            "danger_zone": "Safe if it smells of garlic/onion.",
        },
        "lookalikes": [
            {
                "name": "Bluebell",
                "danger": "POISONOUS",
                "diff": "Bluebell has NO garlic smell and tubular leaves. Three-Cornered Leek smells of garlic.",
            },
        ],
        "confusion_notes": "CRITICAL: If it does NOT smell of garlic or onion, do NOT eat it. Bluebell is POISONOUS and has NO garlic smell.",
    },
    {
        "name": "Sorrel",
        "latin_name": "Rumex acetosa",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June', 'July'],
        "habitat": "Grassland, Meadows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves",
        "warnings": "Contains oxalic acid (like spinach). Eat in moderation.",
        "description": "**Identification:** Large, arrow-shaped leaves. Very sharp lemon flavour.",
        "id_keys": {
            "Leaves": "Arrow-shaped, pointed lobes at base",
            "Taste": "Sharp, lemon/vinegar flavour",
            "Stem": "Tall, ridged, green/reddish",
        },
        "foraging_tips": {
            "where": "Meadows, grassland.",
            "when": "Spring.",
            "sustainable": "Pick outer leaves, leave centre.",
            "danger_zone": "Safe. Eat in moderation due to oxalic acid.",
        },
        "lookalikes": [
            {
                "name": "Lords and Ladies",
                "danger": "POISONOUS",
                "diff": "Lords and Ladies BURNS the mouth instantly. Sorrel TASTES of lemon.",
            },
        ],
        "confusion_notes": "Safe. Identified by the sharp lemon taste. If it burns your mouth (not lemon), it is NOT Sorrel.",
    },
    {
        "name": "Fat-Hen",
        "latin_name": "Chenopodium album",
        "category": "Plant",
        "months": ['May', 'June', 'July', 'August', 'September'],
        "habitat": "Gardens, Arable Land, Waste Ground",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Seeds",
        "warnings": "Contains oxalic acid. Cook before eating.",
        "description": "**Identification:** Diamond/mealy grey-green leaves. White powder on underside. Tall spikes of tiny green flowers.",
        "id_keys": {
            "Leaves": "Diamond-shaped, mealy white powder underneath",
            "Stem": "Streaked with red/purple",
            "Flowers": "Tiny, green, dense spikes",
        },
        "foraging_tips": {
            "where": "Gardens, arable fields.",
            "when": "Summer.",
            "sustainable": "Common weed. Pick freely.",
            "danger_zone": "Safe. Cook like spinach.",
        },
        "lookalikes": [
            {
                "name": "Orache",
                "danger": "EDIBLE",
                "diff": "Orache has leaves that are more triangular and often red-tinged.",
            },
        ],
        "confusion_notes": "Safe. The mealy white powder on the underside of the leaves is distinctive. Cook like spinach.",
    },
    {
        "name": "Hairy Bittercress",
        "latin_name": "Cardamine hirsuta",
        "category": "Plant",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Gardens, Paths",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Stems, Flowers",
        "warnings": "Peppery taste. Don't eat too much raw.",
        "description": "**Identification:** Small rosette of leaflets. Tiny white flowers. Seed pods explode when touched.",
        "id_keys": {
            "Leaves": "Small, round leaflets in a rosette",
            "Flowers": "Tiny, white, 4 petals",
            "Seeds": "Slender pods that explode",
        },
        "foraging_tips": {
            "where": "Gardens, paths, plant pots.",
            "when": "Year-round.",
            "sustainable": "Common garden weed.",
            "danger_zone": "Safe. Great pepper substitute.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive exploding seed pods.",
            },
        ],
        "confusion_notes": "Safe. The exploding seed pods make it impossible to mistake.",
    },
    {
        "name": "Watercress",
        "latin_name": "Nasturtium officinale",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June', 'July', 'August', 'September'],
        "habitat": "Clean Streams, Waterways",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Leaves, Stems",
        "warnings": "Must be washed. Do not collect from polluted water (liver fluke risk).",
        "description": "**Identification:** Grows in running water. Small, rounded leaves. White flowers. Peppery taste.",
        "id_keys": {
            "Leaves": "Small, rounded, dark green",
            "Habitat": "Growing IN clean running water",
            "Taste": "Peppery",
        },
        "foraging_tips": {
            "where": "Clean, fast-flowing streams.",
            "when": "Spring - Autumn.",
            "sustainable": "Snip tops, leave roots.",
            "danger_zone": "CRITICAL: Must be from CLEAN water. Risk of liver fluke.",
        },
        "lookalikes": [
            {
                "name": "Fool's Watercress",
                "danger": "EDIBLE",
                "diff": "Fool's Watercress has broader leaves and grows in still water. Edible but check water quality.",
            },
        ],
        "confusion_notes": "CRITICAL: Only pick from CLEAN, running water. If water is polluted or still, do NOT eat due to liver fluke risk.",
    },
    {
        "name": "Yarrow",
        "latin_name": "Achillea millefolium",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Grassland, Meadows, Lawns",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Good for tea. Can be bitter. Avoid if pregnant.",
        "description": "**Identification:** Feathery, fern-like leaves. Flat-topped clusters of white (or pink) flowers.",
        "id_keys": {
            "Leaves": "Feathery, fern-like, divided",
            "Flowers": "Flat-topped clusters, white/pink",
            "Smell": "Aromatic, medicinal",
        },
        "foraging_tips": {
            "where": "Grassland, lawns, paths.",
            "when": "Summer.",
            "sustainable": "Common. Pick leaves and flowers.",
            "danger_zone": "Safe. Avoid if pregnant.",
        },
        "lookalikes": [
            {
                "name": "Hemlock",
                "danger": "DEADLY",
                "diff": "Hemlock has SMOOTH stems with PURPLE SPOTS and smells of mouse urine. Yarrow has FEATHERY leaves and smells aromatic.",
            },
        ],
        "confusion_notes": "Safe. Distinctive feathery leaves and aromatic smell. Hemlock has purple spotted stems.",
    },
    {
        "name": "Sweet Cicely",
        "latin_name": "Myrrhis odorata",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'June'],
        "habitat": "Roadsides, Hedgerows, Gardens",
        "regions": ['North', 'Scotland', 'Wales'],
        "difficulty": 2,
        "parts": "Leaves, Stems, Roots, Seeds",
        "warnings": "Sweet aniseed flavour. Great sugar substitute.",
        "description": "**Identification:** Feathery leaves with white blotches. White umbels. Strong aniseed smell.",
        "id_keys": {
            "Leaves": "Feathery, white blotches on underside",
            "Flowers": "White umbels",
            "Smell": "Strong aniseed",
        },
        "foraging_tips": {
            "where": "Hedgerows, roadsides (North).",
            "when": "Spring.",
            "sustainable": "Pick leaves, leave roots.",
            "danger_zone": "Safe. Smells strongly of aniseed.",
        },
        "lookalikes": [
            {
                "name": "Hemlock",
                "danger": "DEADLY",
                "diff": "Hemlock has purple spots and smells of mouse urine. Sweet Cicely has white blotches on leaves and smells of aniseed.",
            },
        ],
        "confusion_notes": "CRITICAL: Sweet Cicely smells of ANISEED and has white blotches on leaves. Hemlock smells of MOUSE URINE and has purple spots.",
    },
    {
        "name": "Wild Thyme",
        "latin_name": "Thymus polytrichus",
        "category": "Plant",
        "months": ["May", "June", "July", "August"],
        "habitat": "Grassland, Heaths, Dry banks",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Strong flavour. Use sparingly.",
        "description": "**Identification:** Low-growing, mat-forming herb. Tiny oval leaves on wiry stems. Pink/purple flowers in whorls. Strong thyme scent when crushed.",
        "id_keys": {
            "Leaves": "Tiny, oval, opposite pairs on wiry stems",
            "Flowers": "Pink/purple, in whorls",
            "Smell": "Strong thyme scent when crushed"
        },
        "foraging_tips": {
            "where": "Dry grassland, heaths, banks.",
            "when": "Summer.",
            "sustainable": "Snip sprigs, leave roots.",
            "danger_zone": "Safe. Distinctive thyme smell."
        },
        "lookalikes": [
            {"name": "Wild Marjoram", "danger": "EDIBLE", "diff": "Wild Marjoram is taller with larger leaves and a oregano smell."}
        ],
        "confusion_notes": "Safe. If it smells of thyme, it is thyme. Wild Marjoram smells of oregano and is also edible."
    },
    {
        "name": "Wild Marjoram",
        "latin_name": "Origanum vulgare",
        "category": "Plant",
        "months": ["June", "July", "August", "September"],
        "habitat": "Grassland, Hedge banks, Dry soils",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Same family as culinary oregano. Strong flavour.",
        "description": "**Identification:** Upright plant with oval leaves. Flat-topped clusters of pink/purple flowers. Strong oregano/marjoram scent.",
        "id_keys": {
            "Leaves": "Oval, slightly hairy, opposite pairs",
            "Flowers": "Pink/purple, flat-topped clusters",
            "Smell": "Strong oregano/marjoram scent"
        },
        "foraging_tips": {
            "where": "Dry grassland, hedge banks, chalky soil.",
            "when": "Summer.",
            "sustainable": "Snip stems, leave roots.",
            "danger_zone": "Safe. Distinctive oregano smell."
        },
        "lookalikes": [
            {"name": "Wild Thyme", "danger": "EDIBLE", "diff": "Wild Thyme is smaller, more mat-forming, and smells of thyme, not oregano."}
        ],
        "confusion_notes": "Safe. If it smells of oregano, it is Wild Marjoram. Wild Thyme is also edible but smells different."
    },
    {
        "name": "Wild Fennel",
        "latin_name": "Foeniculum vulgare",
        "category": "Plant",
        "months": ["June", "July", "August", "September", "October"],
        "habitat": "Coastal, Waste ground, Roadsides",
        "regions": ["Southern", "Coastal"],
        "difficulty": 2,
        "parts": "Leaves, Seeds, Stems",
        "warnings": "Can look similar to Hemlock. MUST smell of aniseed.",
        "description": "**Identification:** Tall, feathery plant with yellow umbel flowers. Aniseed smell. Thread-like leaves.",
        "id_keys": {
            "Leaves": "Feathery, thread-like (like dill)",
            "Stem": "Green, ridged, NO purple spots",
            "Smell": "Strong aniseed/fennel smell",
            "Seeds": "Green then brown, oval, ribbed"
        },
        "foraging_tips": {
            "where": "Coastal paths, waste ground (especially Southern England).",
            "when": "Summer for leaves, Autumn for seeds.",
            "sustainable": "Snip leaves and seeds, leave roots.",
            "danger_zone": "CRITICAL: Must smell of ANISEED and have NO purple spots on stem."
        },
        "lookalikes": [
            {"name": "Hemlock", "danger": "DEADLY", "diff": "Hemlock has SMOOTH stems with PURPLE SPOTS and smells of mouse urine. Wild Fennel has ridged green stems and smells of aniseed."}
        ],
        "confusion_notes": "CRITICAL: Wild Fennel smells of ANISEED and has ridged GREEN stems with NO purple spots. Hemlock has PURPLE SPOTS and smells of mouse urine."
    },
    {
        "name": "Comfrey",
        "latin_name": "Symphytum officinale",
        "category": "Plant",
        "months": ["May", "June", "July"],
        "habitat": "Damp meadows, Riverbanks",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Young leaves (cooked only)",
        "warnings": "Contains pyrrolizidine alkaloids. Do NOT eat regularly. External use safest.",
        "description": "**Identification:** Tall plant with large, hairy leaves. Bell-shaped flowers that hang in loose clusters, usually purple/pink but sometimes white or cream.",
        "id_keys": {
            "Leaves": "Large, hairy, lance-shaped, decurrent (wings running down stem)",
            "Flowers": "Purple/pink bells, hanging in loose clusters",
            "Stem": "Winged (leaves run down the stem)"
        },
        "foraging_tips": {
            "where": "Damp meadows, riverbanks, ditches.",
            "when": "Spring for young leaves.",
            "sustainable": "Harvest a few leaves per plant.",
            "danger_zone": "CAUTION: Contains PAs. Best used externally as a poultice. Do NOT eat regularly."
        },
        "lookalikes": [
            {"name": "Foxglove", "danger": "DEADLY", "diff": "Foxglove has tall spikes of trumpet flowers growing UP. Comfrey has bell flowers hanging DOWN in loose clusters."}
        ],
        "confusion_notes": "⚠️ CAUTION: Comfrey has bell-shaped flowers that hang DOWN. Foxglove has trumpet flowers growing UP on a tall spike. Comfrey should NOT be eaten regularly."
    },
    {
        "name": "Self-Heal",
        "latin_name": "Prunella vulgaris",
        "category": "Plant",
        "months": ["June", "July", "August", "September"],
        "habitat": "Lawns, Meadows, Paths",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Mild flavour. Good in salads or as tea.",
        "description": "**Identification:** Low-growing plant with oval leaves. Distinctive purple flower head shaped like a small club or bottlebrush.",
        "id_keys": {
            "Flowers": "Purple, in a club-shaped head",
            "Leaves": "Oval, opposite, slightly toothed",
            "Habitat": "Very common in lawns and paths"
        },
        "foraging_tips": {
            "where": "Lawns, meadows, paths.",
            "when": "Summer.",
            "sustainable": "Common. Pick leaves and flowers.",
            "danger_zone": "Safe. Very common lawn plant."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The club-shaped purple flower head is distinctive."}
        ],
        "confusion_notes": "Safe. The club-shaped purple flower head is unique. Very common in lawns."
    },
    {
        "name": "Red Clover",
        "latin_name": "Trifolium pratense",
        "category": "Plant",
        "months": ["May", "June", "July", "August", "September"],
        "habitat": "Meadows, Grassland, Lawns",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Flowers, Leaves",
        "warnings": "Mild, sweet flavour. Good as tea. Avoid if on blood thinners.",
        "description": "**Identification:** Classic clover with three leaflets. Round pink/purple flower heads. White V-shaped mark on each leaflet.",
        "id_keys": {
            "Leaves": "3 leaflets, each with white V-shaped mark",
            "Flowers": "Round, pink/purple, fluffy",
            "Habitat": "Very common in grass"
        },
        "foraging_tips": {
            "where": "Meadows, lawns, grassland.",
            "when": "Summer.",
            "sustainable": "Pick flower heads. Very common.",
            "danger_zone": "Safe. Avoid if on blood thinners (contains coumarins)."
        },
        "lookalikes": [
            {"name": "White Clover", "danger": "EDIBLE", "diff": "White Clover has white/pale pink flowers. Both are edible."}
        ],
        "confusion_notes": "Safe. The round pink/purple flower head and three leaflets with white marks are distinctive."
    },
    {
        "name": "Cow Parsley",
        "latin_name": "Anthriscus sylvestris",
        "category": "Plant",
        "months": ["April", "May", "June"],
        "habitat": "Hedgerows, Roadsides, Woodland edges",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Young leaves, Stems (cooked)",
        "warnings": "MUST be identified with certainty — confused with deadly Hemlock. Check for ridged stems and NO purple spots.",
        "description": "**Identification:** White umbel flowers (flat-topped clusters). Finely divided, feathery leaves. Ridged/grooved GREEN stems. Smells of sweet parsley.",
        "id_keys": {
            "Stem": "Ridged/grooved, GREEN, NO purple spots",
            "Leaves": "Feathery, 2-3 times divided, fern-like",
            "Smell": "Sweet parsley smell when crushed",
            "Flowers": "White, flat-topped umbels"
        },
        "foraging_tips": {
            "where": "Hedgerows, roadsides, woodland edges.",
            "when": "Spring.",
            "sustainable": "Pick a few young leaves. Do NOT dig up roots (illegal).",
            "danger_zone": "CRITICAL: Must have RIDGED stems and smell of PARSLEY. If it has purple spots or smells of mouse urine, it is HEMLOCK."
        },
        "lookalikes": [
            {"name": "Hemlock", "danger": "DEADLY", "diff": "Hemlock has SMOOTH stems with PURPLE SPOTS. Cow Parsley has RIDGED/GROOVED GREEN stems with NO purple spots."}
        ],
        "confusion_notes": "CRITICAL: Cow Parsley has RIDGED/GROOVED GREEN stems and smells of PARSLEY. Hemlock has SMOOTH stems with PURPLE SPOTS and smells of MOUSE URINE."
    },
    {
        "name": "Good King Henry",
        "latin_name": "Blitum bonus-henricus",
        "category": "Plant",
        "months": ["March", "April", "May", "June"],
        "habitat": "Gardens, Waste ground, Village greens",
        "regions": ["Southern", "Central"],
        "difficulty": 2,
        "parts": "Leaves, Shoots",
        "warnings": "Cook like spinach. Contains oxalates.",
        "description": "**Identification:** Large, triangular, arrow-shaped leaves with a mealy coating underneath. Tall flower spikes with tiny green flowers. Often found near old settlements.",
        "id_keys": {
            "Leaves": "Large, triangular, arrow-shaped, mealy underneath",
            "Flowers": "Tiny, green, in tall spikes",
            "Habitat": "Near old settlements, village greens"
        },
        "foraging_tips": {
            "where": "Village greens, waste ground, old gardens.",
            "when": "Spring.",
            "sustainable": "Harvest outer leaves, leave centre.",
            "danger_zone": "Safe when cooked. Contains oxalates (like spinach)."
        },
        "lookalikes": [
            {"name": "Fat-Hen", "danger": "EDIBLE", "diff": "Fat-Hen has diamond-shaped leaves with mealy white powder. Good King Henry has arrow-shaped leaves."}
        ],
        "confusion_notes": "Safe when cooked. Arrow-shaped leaves with mealy coating underneath. Often found near old settlements."
    },
    {
        "name": "Primrose",
        "latin_name": "Primula vulgaris",
        "category": "Plant",
        "months": ["February", "March", "April"],
        "habitat": "Woodlands, Hedgerows, Gardens",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Flowers, Young leaves",
        "warnings": "Only eat in moderation. Do not confuse with Primula obconica (indoor primrose, irritant).",
        "description": "**Identification:** Low-growing plant. Pale yellow flowers with five petals, each petal notched. Crinkled, tongue-shaped leaves in a rosette.",
        "id_keys": {
            "Flowers": "Pale yellow, 5 notched petals, facing upwards",
            "Leaves": "Crinkled, tongue-shaped, in a rosette",
            "Habitat": "Woodland, hedge banks, shady places"
        },
        "foraging_tips": {
            "where": "Woodlands, hedge banks, shady gardens.",
            "when": "Early spring (February-April).",
            "sustainable": "Pick a few flowers only. Leave leaves.",
            "danger_zone": "Safe in moderation. Do NOT eat indoor primroses."
        },
        "lookalikes": [
            {"name": "Cowslip", "danger": "EDIBLE", "diff": "Cowslip has taller stems with nodding clusters of yellow flowers. Primrose has single flowers on short stems."},
            {"name": "Oxlip", "danger": "EDIBLE", "diff": "Oxlip has flowers on one side of the stem. Primrose flowers face upwards."}
        ],
        "confusion_notes": "Safe. Pale yellow flowers facing upwards on short stems. Do NOT eat indoor primroses (Primula obconica) — they cause skin irritation."
    },
    {
        "name": "Cowslip",
        "latin_name": "Primula veris",
        "category": "Plant",
        "months": ["April", "May"],
        "habitat": "Meadows, Pastures, Hedge banks",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Flowers, Young leaves",
        "warnings": "Protected in the wild. Pick sparingly. Cowslip wine is traditional.",
        "description": "**Identification:** Tall stems with nodding clusters of deep yellow, funnel-shaped flowers. Each flower has a small calyx with five teeth. Crinkled leaves in a rosette.",
        "id_keys": {
            "Flowers": "Deep yellow, funnel-shaped, nodding clusters on tall stems",
            "Leaves": "Crinkled, oval, in a rosette",
            "Calyx": "Five-toothed green calyx behind flower"
        },
        "foraging_tips": {
            "where": "Meadows, pastures, hedge banks (decreasing due to habitat loss).",
            "when": "April-May.",
            "sustainable": "PROTECTED in many areas. Pick flowers sparingly from abundant patches only.",
            "danger_zone": "Safe. Traditional for cowslip wine and tea."
        },
        "lookalikes": [
            {"name": "Primrose", "danger": "EDIBLE", "diff": "Primrose has single pale yellow flowers on short stems. Cowslip has clusters of deeper yellow on tall stems."}
        ],
        "confusion_notes": "Safe. Deep yellow funnel-shaped flowers in nodding clusters on tall stems. Protected — pick sparingly."
    },
    {
        "name": "Salad Burnet",
        "latin_name": "Sanguisorba minor",
        "category": "Plant",
        "months": ["March", "April", "May", "June", "July"],
        "habitat": "Grassland, Dry meadows, Chalk",
        "regions": ["Southern", "Central"],
        "difficulty": 1,
        "parts": "Leaves",
        "warnings": "Cucumber flavour. Good in salads.",
        "description": "**Identification:** Low-growing plant with paired, rounded leaflets with toothed edges. Tiny pink/red flowers in round heads on tall stems.",
        "id_keys": {
            "Leaves": "Rounded, paired leaflets, toothed edges",
            "Flowers": "Tiny, pink/red, in round cluster heads",
            "Taste": "Cucumber flavour"
        },
        "foraging_tips": {
            "where": "Dry grassland, chalk, meadows.",
            "when": "Spring to Summer.",
            "sustainable": "Pick young leaves from the rosette.",
            "danger_zone": "Safe. Cucumber flavour is distinctive."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Rounded leaflets with toothed edges and cucumber flavour are distinctive."}
        ],
        "confusion_notes": "Safe. The cucumber flavour and rounded, toothed leaflets are distinctive."
    },
    {
        "name": "Silverweed",
        "latin_name": "Potentilla anserina",
        "category": "Plant",
        "months": ["April", "May", "June", "July", "August", "September"],
        "habitat": "Grassland, Paths, Riverbanks",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Roots (cooked)",
        "warnings": "Roots are starchy and edible cooked. Leaves also edible raw but bitter.",
        "description": "**Identification:** Low-growing creeping plant. Leaves are silvery-white underneath, green on top, with many toothed leaflets. Yellow flowers with 5 petals.",
        "id_keys": {
            "Leaves": "Green on top, SILVER-WHITE underneath, many toothed leaflets",
            "Flowers": "Yellow, 5 petals",
            "Habitat": "Paths, bare ground, riverbanks"
        },
        "foraging_tips": {
            "where": "Paths, bare ground, riverbanks, grassland.",
            "when": "Autumn for roots, Spring for leaves.",
            "sustainable": "Digging roots kills the plant. Only dig where abundant.",
            "danger_zone": "Roots must be cooked. Raw roots are starchy but tough."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The silver-white underside of the leaves is unique."}
        ],
        "confusion_notes": "Safe. The SILVER-WHITE underside of the leaves is the key identifier. Roots were an important food source historically."
    },
    {
        "name": "Wild Hop",
        "latin_name": "Humulus lupulus",
        "category": "Plant",
        "months": ["June", "July", "August", "September"],
        "habitat": "Hedgerows, Woodlands, Riverbanks",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Young shoots, Flowers (cones)",
        "warnings": "Young shoots eaten like asparagus. Flowers used for brewing. Can cause skin irritation.",
        "description": "**Identification:** Vigorous climbing plant with twining stems. Deeply lobed, rough leaves. Distinctive cone-like green flowers (hops).",
        "id_keys": {
            "Leaves": "Lobed, rough texture, opposite pairs",
            "Flowers": "Green cone-like papery structures (hops)",
            "Stem": "Twining, climbing (wraps clockwise)"
        },
        "foraging_tips": {
            "where": "Hedgerows, riverbanks, woods.",
            "when": "Spring for shoots, Late Summer for flowers.",
            "sustainable": "Pick a few cones. Leave plenty for wildlife.",
            "danger_zone": "Can cause skin irritation. Handle with gloves if sensitive."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The cone-like flowers and twining stems are distinctive."}
        ],
        "confusion_notes": "Safe. The cone-like green flowers (hops) and twining stems are distinctive. Can cause skin irritation in some people."
    },
    {
        "name": "Bistort",
        "latin_name": "Persicaria bistorta",
        "category": "Plant",
        "months": ["April", "May", "June"],
        "habitat": "Meadows, Damp grassland",
        "regions": ["Northern", "Wales", "Scotland"],
        "difficulty": 1,
        "parts": "Leaves, Roots",
        "warnings": "Leaves edible raw or cooked. Roots are very astringent — best cooked.",
        "description": "**Identification:** Tall pink flower spikes on a plant with distinctive arrow-shaped basal leaves. The leaves have a 'tucked under' edge.",
        "id_keys": {
            "Leaves": "Arrow-shaped, basal, edges curled under",
            "Flowers": "Pink, in dense spikes on tall stems",
            "Habitat": "Damp meadows, northern UK"
        },
        "foraging_tips": {
            "where": "Damp meadows, northern England, Wales, Scotland.",
            "when": "Spring for leaves.",
            "sustainable": "Pick leaves, leave roots.",
            "danger_zone": "Leaves are safe. Roots are very astringent and should be soaked before cooking."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The pink flower spikes and arrow-shaped leaves with curled edges are distinctive."}
        ],
        "confusion_notes": "Safe. The pink flower spikes and arrow-shaped leaves with edges curled under are distinctive."
    },
    {
        "name": "Lesser Celandine",
        "latin_name": "Ficaria verna",
        "category": "Plant",
        "months": ["February", "March", "April"],
        "habitat": "Woodlands, Hedgerows, Gardens",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Leaves (cooked), Flower buds (pickled)",
        "warnings": "Contains protoanemonin when RAW. Must be cooked or dried. Do NOT eat raw in quantity.",
        "description": "**Identification:** Low-growing with shiny, heart-shaped leaves. Bright yellow star-like flowers (8-12 petals). One of the first flowers of spring.",
        "id_keys": {
            "Leaves": "Heart-shaped, shiny, dark green, often mottled",
            "Flowers": "Bright yellow, 8-12 petals, star-like",
            "Habitat": "Woodland floor, hedge banks, early spring"
        },
        "foraging_tips": {
            "where": "Woodlands, hedge banks, gardens.",
            "when": "February-April.",
            "sustainable": "Pick a few leaves from abundant patches.",
            "danger_zone": "MUST be cooked or dried. Contains protoanemonin when raw."
        },
        "lookalikes": [
            {"name": "Buttercup", "danger": "POISONOUS", "diff": "Buttercup has 5 shiny petals. Lesser Celandine has 8-12 petals and is a low-growing plant."},
            {"name": "Greater Celandine", "danger": "POISONOUS", "diff": "Greater Celandine has orange sap and divided leaves. Lesser Celandine has no orange sap and heart-shaped leaves."}
        ],
        "confusion_notes": "CAUTION: Must be COOKED or dried. Lesser Celandine has 8-12 petals and heart-shaped leaves. Buttercup has exactly 5 petals. Do NOT eat raw."
    },
    {
        "name": "Sweet Woodruff",
        "latin_name": "Galium odoratum",
        "category": "Plant",
        "months": ["May", "June"],
        "habitat": "Woodlands, Hedgerows",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Use in moderation. Contains coumarin (gives the sweet scent). Large amounts can cause headaches.",
        "description": "**Identification:** Low-growing, spreading plant with whorls of narrow leaves. Tiny white flowers. Smells of sweet hay/vanilla when dried.",
        "id_keys": {
            "Leaves": "Whorls of 6-8 narrow leaves",
            "Flowers": "Tiny white, star-shaped",
            "Smell": "Sweet hay/vanilla when dried"
        },
        "foraging_tips": {
            "where": "Woodland floors, hedge bottoms.",
            "when": "May-June.",
            "sustainable": "Pick sparingly. Dry for later use.",
            "danger_zone": "Use in moderation. Contains coumarin. Large amounts cause headaches."
        },
        "lookalikes": [
            {"name": "Cleavers", "danger": "EDIBLE", "diff": "Cleavers is sticky and has whorls of 6-8 narrow leaves too, but has NO sweet smell when dried."}
        ],
        "confusion_notes": "Safe in moderation. The sweet hay/vanilla smell when dried is distinctive. Use sparingly — large amounts can cause headaches."
    },
    {
        "name": "Wild Basil",
        "latin_name": "Clinopodium vulgare",
        "category": "Plant",
        "months": ["July", "August", "September"],
        "habitat": "Grassland, Hedgerows, Dry banks",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Leaves, Flowers",
        "warnings": "Mild basil flavour. Use as seasoning.",
        "description": "**Identification:** Upright plant with oval, slightly toothed leaves. Whorls of pink/purple flowers at the top of the stem. Mild basil scent.",
        "id_keys": {
            "Leaves": "Oval, slightly toothed, opposite pairs",
            "Flowers": "Pink/purple, in whorls at top of stem",
            "Smell": "Mild basil scent when crushed"
        },
        "foraging_tips": {
            "where": "Dry grassland, hedge banks.",
            "when": "Summer.",
            "sustainable": "Pick leaves and flowers.",
            "danger_zone": "Safe. Mild basil flavour."
        },
        "lookalikes": [
            {"name": "Wild Thyme", "danger": "EDIBLE", "diff": "Wild Thyme is low-growing with tiny leaves and a stronger thyme smell. Wild Basil is taller with larger leaves and a milder basil smell."}
        ],
        "confusion_notes": "Safe. Mild basil smell. Taller than Wild Thyme with larger leaves."
    },
    {
        "name": "White Clover",
        "latin_name": "Trifolium repens",
        "category": "Plant",
        "months": ["May", "June", "July", "August", "September"],
        "habitat": "Lawns, Grassland, Paths",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Flowers, Leaves",
        "warnings": "Mild, sweet flavour. Good as tea. Avoid if on blood thinners.",
        "description": "**Identification:** Low-growing with three leaflets (often with white mark). White/pale pink globe-shaped flowers. Very common in lawns.",
        "id_keys": {
            "Leaves": "3 leaflets, often with white V-shaped mark",
            "Flowers": "White/pale pink, round globe shape",
            "Habitat": "Very common in lawns and grass"
        },
        "foraging_tips": {
            "where": "Lawns, paths, fields.",
            "when": "Spring to Autumn.",
            "sustainable": "Very common. Pick flowers freely.",
            "danger_zone": "Safe. Avoid if on blood thinners."
        },
        "lookalikes": [
            {"name": "Red Clover", "danger": "EDIBLE", "diff": "Red Clover has pink/purple flowers. White Clover has white/pale pink flowers."}
        ],
        "confusion_notes": "Safe. White globe-shaped flowers and three leaflets. Very common in lawns. Good for tea."
    },
    {
        "name": "Wood Avens",
        "latin_name": "Geum urbanum",
        "category": "Plant",
        "months": ["May", "June", "July"],
        "habitat": "Woodlands, Hedgerows, Gardens",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Roots, Young leaves",
        "warnings": "Roots have a clove-like flavour. Used in herbal tea.",
        "description": "**Identification:** Low rosette of lobed leaves. Yellow, 5-petalled flowers on thin stems. Seeds are small burred hooks that stick to clothing.",
        "id_keys": {
            "Leaves": "Lobed, toothed, in a rosette",
            "Flowers": "Yellow, 5 petals, nodding",
            "Seeds": "Small hooked burs that stick to clothes"
        },
        "foraging_tips": {
            "where": "Woodland, hedgerows, gardens.",
            "when": "Spring for leaves, Autumn for roots.",
            "sustainable": "Dig roots only where abundant.",
            "danger_zone": "Safe. Roots taste of cloves."
        },
        "lookalikes": [
            {"name": "Water Avens", "danger": "EDIBLE", "diff": "Water Avens has pink/purple flowers and grows in damp places. Wood Avens has yellow flowers."}
        ],
        "confusion_notes": "Safe. Yellow flowers and seeds that stick to clothing. The roots have a distinctive clove flavour."
    },
    {
        "name": "Wild Chervil",
        "latin_name": "Anthriscus cerefolium",
        "category": "Plant",
        "months": ["April", "May", "June"],
        "habitat": "Hedgerows, Woodland edges",
        "regions": ["Southern", "Central"],
        "difficulty": 3,
        "parts": "Leaves, Stems",
        "warnings": "EXPERT ONLY. Very similar to Hemlock. MUST have hairy stems and smell of parsley.",
        "description": "**Identification:** Feathery, fern-like leaves. White umbel flowers. Hairy stems (key ID feature). Smells of sweet parsley when crushed.",
        "id_keys": {
            "Stem": "HAIRY, green, NO purple spots (critical ID)",
            "Leaves": "Feathery, fern-like, hairy underneath",
            "Smell": "Sweet parsley when crushed"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges.",
            "when": "Spring.",
            "sustainable": "Pick leaves from the top.",
            "danger_zone": "CRITICAL: Must have HAIRY stems and smell of PARSLEY. If it has purple spots or smells of mouse urine, it is HEMLOCK."
        },
        "lookalikes": [
            {"name": "Hemlock", "danger": "DEADLY", "diff": "Hemlock has SMOOTH stems with PURPLE SPOTS and smells of mouse urine. Wild Chervil has HAIRY stems and smells of parsley."}
        ],
        "confusion_notes": "CRITICAL: Wild Chervil has HAIRY stems and smells of PARSLEY. Hemlock has SMOOTH stems with PURPLE SPOTS and smells of MOUSE URINE. If you see purple spots, do NOT touch it."
    },
    {
        "name": "Marsh Woundwort",
        "latin_name": "Stachys palustris",
        "category": "Plant",
        "months": ["June", "July", "August"],
        "habitat": "Damp meadows, Riverbanks, Marshes",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Tubers (cooked)",
        "warnings": "Tubers must be cooked. Raw tubers are unpleasant.",
        "description": "**Identification:** Tall plant with square stem. Pink/purple flower spikes. Toothed, pointed leaves. Produces strings of small tubers underground.",
        "id_keys": {
            "Stem": "Square (mint family), tall",
            "Flowers": "Pink/purple spikes, orchid-like",
            "Leaves": "Pointed, toothed, opposite pairs",
            "Tubers": "Strings of small tubers underground"
        },
        "foraging_tips": {
            "where": "Damp meadows, riverbanks, marshes.",
            "when": "Autumn for tubers.",
            "sustainable": "Digging tubers kills the plant. Only dig where abundant.",
            "danger_zone": "MUST be cooked. Raw tubers are unpleasant."
        },
        "lookalikes": [
            {"name": "Hedge Woundwort", "danger": "EDIBLE (leaves only)", "diff": "Hedge Woundwort has unpleasant smell and grows in dry places. Marsh Woundwort has no bad smell and grows in WET places."}
        ],
        "confusion_notes": "Safe when cooked. Marsh Woundwort grows in WET places and has no bad smell. Hedge Woundwort grows in dry places and smells unpleasant."
    },
    {
        "name": "Common Poppy",
        "latin_name": "Papaver rhoeas",
        "category": "Plant",
        "months": ["June", "July", "August"],
        "habitat": "Fields, Roadsides, Waste ground",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Seeds only",
        "warnings": "ONLY the seeds are edible. All other parts are toxic. Do NOT confuse with Opium Poppy.",
        "description": "**Identification:** Iconic bright red flowers with 4 papery petals and a dark centre. Finely divided leaves. Round seed heads that rattle when dry.",
        "id_keys": {
            "Flowers": "Bright red, 4 papery petals, dark centre",
            "Leaves": "Finely divided, hairy",
            "Seed heads": "Round, rattle when dry"
        },
        "foraging_tips": {
            "where": "Fields, roadsides, waste ground.",
            "when": "Summer for flowers, Late Summer for seeds.",
            "sustainable": "Shake seeds from dry heads. Leave plenty.",
            "danger_zone": "ONLY the seeds are edible. ALL other parts are TOXIC."
        },
        "lookalikes": [
            {"name": "Opium Poppy", "danger": "POISONOUS (cultivated)", "diff": "Opium Poppy is larger with pink/purple/red flowers and a smooth seed head. Common Poppy is smaller with bright red flowers."}
        ],
        "confusion_notes": "ONLY the SEEDS are edible. The flowers, leaves, and stems are TOXIC. Do NOT eat any part except the seeds."
    },
    {
        "name": "Wavy Bittercress",
        "latin_name": "Cardamine flexuosa",
        "category": "Plant",
        "months": ["March", "April", "May", "June", "July", "August", "September"],
        "habitat": "Damp ground, Stream sides, Gardens",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Leaves, Stems, Flowers",
        "warnings": "Peppery taste, similar to Hairy Bittercress.",
        "description": "**Identification:** Small plant with pinnate leaves (leaflets along a central stem). Tiny white 4-petalled flowers. Slender seed pods that explode when touched. Prefers damp ground.",
        "id_keys": {
            "Leaves": "Pinnate, 5-9 leaflets, on a central stem",
            "Flowers": "Tiny white, 4 petals",
            "Stem": "Wavy/bent at the nodes (flexuosa = wavy)",
            "Seeds": "Slender pods that explode"
        },
        "foraging_tips": {
            "where": "Damp ground, stream sides, gardens.",
            "when": "Spring to Autumn.",
            "sustainable": "Common. Pick freely.",
            "danger_zone": "Safe. Great pepper substitute."
        },
        "lookalikes": [
            {"name": "Hairy Bittercress", "danger": "EDIBLE", "diff": "Hairy Bittercress has a line of hairs on the stem. Wavy Bittercress has a wavy stem with no line of hairs."}
        ],
        "confusion_notes": "Safe. Both bittercresses are edible. Wavy Bittercress prefers damp ground and has a wavy stem. Both have exploding seed pods."
    },
    {
        "name": "Poppy (Seeds)",
        "latin_name": "Papaver somniferum",
        "category": "Plant",
        "months": ["June", "July", "August"],
        "habitat": "Gardens, Waste ground",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Seeds ONLY",
        "warnings": "ONLY the seeds are edible. All other parts are TOXIC. Do NOT cultivate in the UK (controlled).",
        "description": "**Identification:** Large flowers in pink, purple, red, or white. Large, smooth seed pod (rounded). Blue-grey seeds.",
        "id_keys": {
            "Flowers": "Large, pink/purple/red/white, papery petals",
            "Seed pod": "Large, smooth, rounded (distinctive)",
            "Seeds": "Blue-grey, small, edible"
        },
        "foraging_tips": {
            "where": "Gardens (ornamental), waste ground.",
            "when": "Late Summer for seeds.",
            "sustainable": "Shake seeds from dry heads.",
            "danger_zone": "CRITICAL: ONLY the SEEDS are edible. All other parts contain opiates. Do NOT cultivate (controlled substance)."
        },
        "lookalikes": [
            {"name": "Common Poppy", "danger": "EDIBLE (seeds)", "diff": "Common Poppy is smaller with bright red flowers and hairy stems. Opium Poppy is larger with smooth stems and a smooth, rounded seed pod."}
        ],
        "confusion_notes": "CRITICAL: ONLY the SEEDS are edible. All other parts of Opium Poppy are TOXIC and contain opiates. Do NOT cultivate (it is a controlled substance in the UK)."
    },
]
