# data/edible_shrubs.py
# Auto-generated by split_plants.py
# 6 Coastal plants

EDIBLE_SHRUBS = [
    {
        "name": "Bilberry (Whortleberry)",
        "latin_name": "Vaccinium myrtillus",
        "category": "Shrub",
        "months": ['July', 'August'],
        "habitat": "Moorland, Acid Soils",
        "regions": ['North', 'Wales', 'Scotland'],
        "difficulty": 2,
        "parts": "Berries",
        "warnings": "Stains fingers/teeth blue! Difficult to wash out.",
        "description": "**Identification:** Small deciduous shrub, blue-black berries (solo, not in clusters).",
        "id_keys": {
            "Berries": "Blue-black, soft, bloom",
            "Leaves": "Small, oval, finely toothed",
            "Habitat": "High moors",
        },
        "foraging_tips": {
            "where": "High moors, acid soils.",
            "when": "Late Summer.",
            "sustainable": "Pick sparingly; birds rely on them.",
            "danger_zone": "CRITICAL: Do not confuse with Deadly Nightshade. Bilberry is a LOW shrub.",
        },
        "lookalikes": [
            {
                "name": "Deadly Nightshade",
                "danger": "POISONOUS",
                "diff": "Nightshade is a tall leafy plant with large shiny black berries. Bilberry is a low shrub with small berries.",
            },
        ],
        "confusion_notes": "Confused with Deadly Nightshade. **Key Diff:** Nightshade is a tall plant with large shiny black berries. Bilberry is a low shrub with small berries.",
    },
    {
        "name": "Sloe (Blackthorn)",
        "latin_name": "Prunus spinosa",
        "category": "Shrub",
        "months": ['September', 'October', 'November'],
        "habitat": "Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Very bitter raw! Best after frost or frozen.",
        "description": "**Identification:** Small blue-black berries with a white 'bloom'. Large thorns on black branches.",
        "id_keys": {
            "Fruit": "Small, blue-black, sour",
            "Stem": "Black bark, large sharp thorns",
            "Bush": "Dense, thicket-forming",
        },
        "foraging_tips": {
            "where": "Hedgerows.",
            "when": "Autumn (after frost).",
            "sustainable": "Leave plenty for birds.",
            "danger_zone": "Thorns are sharp and can cause infection.",
        },
        "lookalikes": [
            {
                "name": "Bullace",
                "danger": "EDIBLE",
                "diff": "Bullace is larger and less thorny.",
            },
            {
                "name": "Damson",
                "danger": "EDIBLE",
                "diff": "Damson is larger and less thorny.",
            },
        ],
        "confusion_notes": "Safe. Very sour raw but best after frost. Bullace and Damson are larger and less thorny. All are edible.",
    },
    {
        "name": "Blackberries",
        "latin_name": "Rubus fruticosus",
        "category": "Shrub",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Thorny! Watch out for ticks and leeches.",
        "description": "**Identification:** Bramble shrub with thorny stems. Aggregate fruit (many tiny drupelets) turning from red to black.",
        "id_keys": {
            "Fruit": "Black, aggregate berry",
            "Stem": "Thorny (prickles), arching",
            "Leaves": "Compound, 3-5 leaflets",
        },
        "foraging_tips": {
            "where": "Hedgerows, fields.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Very prolific. Pick freely.",
            "danger_zone": "Safe. Wash well.",
        },
        "lookalikes": [
            {
                "name": "None",
                "danger": "SAFE",
                "diff": "All blackberry-like fruits in the UK are edible.",
            },
        ],
        "confusion_notes": "Safe. No dangerous lookalikes in the UK. All blackberry-like fruits are edible.",
    },
    {
        "name": "Rosehips",
        "latin_name": "Rosa canina",
        "category": "Shrub",
        "months": ['September', 'October', 'November'],
        "habitat": "Hedgerows, Scrub",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Fruit (Hips)",
        "warnings": "Seeds inside have irritating hairs. Must be strained out!",
        "description": "**Identification:** Red, oval hips on thorny shrubs with compound leaves.",
        "id_keys": {
            "Fruit": "Red, oval hips",
            "Stem": "Thorny shrub",
            "Leaves": "Compound, serrated edges",
        },
        "foraging_tips": {
            "where": "Hedgerows.",
            "when": "Autumn (after frost).",
            "sustainable": "Leave some for birds.",
            "danger_zone": "CRITICAL: Do NOT eat the seeds inside (they are itchy).",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive red hips.",
            },
        ],
        "confusion_notes": "Safe. Distinctive red hips. Do NOT eat the seeds inside (they are itchy).",
    },
    {
        "name": "Hazelnut",
        "latin_name": "Corylus avellana",
        "category": "Shrub",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Nuts",
        "warnings": "Must be ripe. Green nuts are very astringent.",
        "description": "**Identification:** Shrub with rounded, toothed leaves. Nuts in leafy 'caps' (hats).",
        "id_keys": {
            "Leaves": "Rounded, double-toothed, soft",
            "Nut": "In a leafy, frilly 'hat'",
            "Shrub": "Bendy, multi-stemmed",
        },
        "foraging_tips": {
            "where": "Hedgerows, woods.",
            "when": "Early Autumn.",
            "sustainable": "Leave some for wildlife.",
            "danger_zone": "Safe. Identify by the leafy hat.",
        },
        "lookalikes": [
            {
                "name": "Horse Chestnut",
                "danger": "POISONOUS",
                "diff": "Conkers have a smooth/warty green case, not a leafy frilly hat.",
            },
        ],
        "confusion_notes": "Safe. Look for the leafy 'hat' on the nut. Horse Chestnut (conkers) has a smooth/warty case — NOT spiky.",
    },
    {
        "name": "Wild Raspberry",
        "latin_name": "Rubus idaeus",
        "category": "Shrub",
        "months": ['July', 'August'],
        "habitat": "Woodlands, Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Thorny canes.",
        "description": "**Identification:** Red/purple berries that pull easily from the plug. White flowers. Pale, prickly canes.",
        "id_keys": {
            "Fruit": "Red, hollow (leaves core behind)",
            "Stem": "Prickly, pale/grey",
            "Leaves": "Compound, white underneath",
        },
        "foraging_tips": {
            "where": "Woodland edges, clearings.",
            "when": "Summer.",
            "sustainable": "Leave plenty for wildlife.",
            "danger_zone": "Safe. Distinctive hollow berry.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "All raspberry-like fruits in the UK are edible.",
            },
        ],
        "confusion_notes": "Safe. All raspberry-like fruits in the UK are edible.",
    },
        {
        "name": "Bullace",
        "latin_name": "Prunus insititia",
        "category": "Shrub",
        "months": ["September", "October"],
        "habitat": "Hedgerows, Woodlands",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Fruit",
        "warnings": "Tart raw. Best after frost or cooked into jam.",
        "description": "**Identification:** Small round fruit, larger than sloe, purple-blue with a bloom. Fewer thorns than Blackthorn. Leaves are broader.",
        "id_keys": {
            "Fruit": "Purple-blue, larger than sloe, less tart",
            "Stem": "Fewer thorns than Blackthorn",
            "Leaves": "Broader than Sloe, slightly folded"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges.",
            "when": "Autumn.",
            "sustainable": "Leave some for wildlife.",
            "danger_zone": "Safe. Less tart than Sloe. Good for jam."
        },
        "lookalikes": [
            {"name": "Sloe (Blackthorn)", "danger": "EDIBLE", "diff": "Sloe is smaller, more tart, and has more/larger thorns. Bullace is larger and less thorny."},
            {"name": "Damson", "danger": "EDIBLE", "diff": "Damson is larger still, with a more distinct neck. All three are edible."}
        ],
        "confusion_notes": "Safe. All sloe/bullace/damson fruits are edible. Bullace is larger than Sloe and less thorny."
    },
    {
        "name": "Damson",
        "latin_name": "Prunus domestica subsp. insititia",
        "category": "Shrub",
        "months": ["August", "September", "October"],
        "habitat": "Hedgerows, Orchards, Gardens",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Fruit",
        "warnings": "Tart but edible raw when ripe. Excellent for jam and gin.",
        "description": "**Identification:** Small plum, oval shape, dark purple-blue skin with bloom. Less thorny than Blackthorn. Distinctive neck at the top of the fruit.",
        "id_keys": {
            "Fruit": "Oval plum, dark purple, distinct neck",
            "Stem": "Few or no thorns",
            "Leaves": "Oval, slightly folded, finely toothed"
        },
        "foraging_tips": {
            "where": "Hedgerows, old orchards, gardens.",
            "when": "Late Summer/Autumn.",
            "sustainable": "Leave some for wildlife.",
            "danger_zone": "Safe. Excellent for jam, gin, and baking."
        },
        "lookalikes": [
            {"name": "Sloe", "danger": "EDIBLE", "diff": "Sloe is smaller and much more tart. Damson is larger and sweeter."},
            {"name": "Bullace", "danger": "EDIBLE", "diff": "Bullace is rounder. Damson has a more oval shape and distinct neck."}
        ],
        "confusion_notes": "Safe. All plum-like hedgerow fruits are edible. Damson is larger than Sloe and Bullace, with a distinctive oval shape."
    },
    {
        "name": "Guelder Rose",
        "latin_name": "Viburnum opulus",
        "category": "Shrub",
        "months": ["June", "July", "September", "October"],
        "habitat": "Hedgerows, Woodlands, Wet areas",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Berries (cooked only)",
        "warnings": "Raw berries are bitter and mildly toxic. MUST be cooked. Only the red berries, NOT the white flowers.",
        "description": "**Identification:** Large shrub with maple-like leaves. Flat clusters of white flowers in June (outer flowers large, inner small). Bright red, translucent berries in autumn.",
        "id_keys": {
            "Leaves": "Maple-like, 3-5 lobes, turn red in autumn",
            "Flowers": "Flat white clusters, outer flowers large, inner small",
            "Berries": "Bright red, translucent, slightly oval"
        },
        "foraging_tips": {
            "where": "Hedgerows, damp woods, wet areas.",
            "when": "Flowers in June, berries in September-October.",
            "sustainable": "Pick some berry clusters, leave plenty for birds.",
            "danger_zone": "CRITICAL: Raw berries are bitter and mildly toxic. Must be COOKED."
        },
        "lookalikes": [
            {"name": "Wayfaring Tree", "danger": "MILDLY TOXIC", "diff": "Wayfaring Tree has oval leaves (not maple-like) and red berries that turn black."}
        ],
        "confusion_notes": "CRITICAL: Guelder Rose berries MUST be cooked. Raw they are bitter and mildly toxic. The maple-like leaves and red translucent berries are distinctive."
    },
        {
        "name": "Blackberry",
        "latin_name": "Rubus fruticosus agg.",
        "category": "Shrub",
        "months": ["August", "September", "October"],
        "habitat": "Hedgerows, woodland edges, waste ground, roadsides, fields",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Ripe fruit (blackberries) and young leaves (for tea)",
        "warnings": "Very thorny — wear gloves and long sleeves when picking. Fruit can harbour insects — soak in salt water briefly before eating. Avoid picking from roadsides with heavy traffic (pollution).",
        "description": "**Identification:** Arching, thorny shrub with compound leaves of 3-5 leaflets. Stems are ridged with sharp thorns. White or pinkish 5-petalled flowers in summer. Fruit starts green, turns red, then black and glossy when ripe. Extremely common in hedges and waste ground. **Uses:** Ripe blackberries eaten raw, in crumbles, pies, jams, jellies, and wine. Young leaves can be dried for a pleasant tea. Fruit freezes well. High in vitamin C and antioxidants.",
        "id_keys": {
            "Fruit": "Aggregate fruit of small drupelets, starting green→red→black and glossy when ripe",
            "Thorns": "Sharp, curved thorns on stems — the defining feature of brambles",
            "Leaves": "Compound, 3-5 leaflets, toothed edges, green with pale underside",
            "Flowers": "White to pink, 5 petals, 2-3cm across, in clusters"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges, wasteland, scrub — virtually everywhere in the UK",
            "when": "August to October — pick when fully black and slightly soft to the touch",
            "sustainable": "Leave plenty for wildlife. Only pick what you will use. Berries further along the cane ripen over weeks",
            "danger_zone": "⚠️ Wear gloves — thorns can cause nasty scratches. Soak berries in salt water to remove insects before eating"
        },
        "lookalikes": [
            {
                "name": "Dewberry (Rubus caesius)",
                "danger": "EDIBLE",
                "diff": "Dewberry has fewer, larger drupelets per fruit, a more trailing habit, and fewer thorns. Both are edible"
            }
        ],
        "confusion_notes": "Blackberries are one of the easiest and safest wild fruits to identify. There are no dangerous lookalikes. The main hazard is the thorns!"
    },
    {
        "name": "Dog Rose",
        "latin_name": "Rosa canina",
        "category": "Shrub",
        "months": ["May", "June", "September", "October", "November"],
        "habitat": "Hedgerows, woodland edges, scrub, roadsides",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Flower petals (spring) and rose hips (autumn)",
        "warnings": "The tiny hairs inside rose hips are an irritant — they must be removed before eating. They were traditionally used as itching powder! Only eat the outer flesh of hips. Do not eat the seeds with their hairy coating.",
        "description": "**Identification:** Climbing shrub with hooked thorns and compound leaves of 5-7 leaflets. Large, pale pink to white flowers with 5 petals in June. Hips are oval, bright red, 1-2cm long, containing seeds with irritating hairs. **Uses:** Flower petals are edible — use in salads, jellies, or to flavour sugar and syrup. Rose hips are extremely rich in Vitamin C — use for syrup, jelly, wine, and tea. Must strain out the irritating hairs.",
        "id_keys": {
            "Thorns": "Hooked, curved thorns along the stems — not straight like blackthorn",
            "Flowers": "Large, pale pink to white, 5 petals, 4-6cm across, sweetly scented",
            "Hips": "Oval, bright red, 1-2cm, smooth surface, containing seeds with irritating hairs",
            "Leaves": "Compound, 5-7 leaflets, toothed edges"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges, scrub — one of the most common hedgerow shrubs",
            "when": "Flowers in May-June; hips in September-November (after first frost for sweetness)",
            "sustainable": "Take a few petals per flower. For hips, take from abundant plants and leave plenty for birds",
            "danger_zone": "⚠️ Remove ALL hairs from inside hips before eating — they are a serious irritant. Strain through a sieve or jelly bag"
        },
        "lookalikes": [
            {
                "name": "Sweet Briar (Rosa rubiginosa)",
                "danger": "EDIBLE",
                "diff": "Sweet Briar has apple-scented leaves and stouter prickles. Also edible with same cautions about hip hairs"
            },
            {
                "name": "Burnet Rose (Rosa spinosissima)",
                "danger": "EDIBLE",
                "diff": "Burnet Rose has smaller, more rounded (globe-shaped) black-purple hips and finer leaves. Also edible"
            }
        ],
        "confusion_notes": "All UK wild roses produce edible petals and hips (with irritating hairs removed). There are no dangerous rose lookalikes. The key safety point is removing the hairs from inside the hips."
    },
    {
        "name": "Bilberry",
        "latin_name": "Vaccinium myrtillus",
        "category": "Shrub",
        "months": ["July", "August", "September"],
        "habitat": "Acidic moorland, heathland, upland woods, conifer forests",
        "regions": ["Northern", "All"],
        "difficulty": 2,
        "parts": "Ripe berries and leaves (for tea)",
        "warnings": "Do not confuse with Bog Bilberry (Vaccinium uliginosum) which is also edible but less common. The berries stain fingers and mouths blue — completely normal and harmless.",
        "description": "**Identification:** Low, deciduous shrub (15-50cm) with angular, green, ridged stems. Leaves are small, oval, finely toothed, turning red in autumn. Flowers are pinkish-green, urn-shaped. Berries are small (5-10mm), blue-black with a flat top, and red-purple flesh inside. **Uses:** Berries eaten raw — sweet and tart. Excellent in pies, crumbles, jams, and muffins. Can be dried. Leaves dried for herbal tea. Very high in antioxidants.",
        "id_keys": {
            "Stems": "Angular, green, ridged (winged) — key distinguishing feature from other berries",
            "Berries": "Small (5-10mm), blue-black, with flat top. Red-purple flesh inside that stains everything blue",
            "Leaves": "Small, oval, finely toothed, bright green turning red in autumn",
            "Size": "Low shrub, 15-50cm — much smaller than a blueberry bush"
        },
        "foraging_tips": {
            "where": "Acidic moorland, heathland, and upland woods — common in northern England, Scotland, Wales",
            "when": "July to September — pick when fully blue-black and slightly soft",
            "sustainable": "Pick only what you need. Leave unripe green berries to mature. Bilberries are vital wildlife food",
            "danger_zone": "Fingers and mouths will stain blue — this is normal and harmless, but don't wear nice clothes!"
        },
        "lookalikes": [
            {
                "name": "Bog Bilberry (Vaccinium uliginosum)",
                "danger": "EDIBLE",
                "diff": "Bog Bilberry has rounder stems (not angular), white flesh inside berries, and grows in wetter bogs. Both are edible"
            },
            {
                "name": "Crowberry (Empetrum nigrum)",
                "danger": "EDIBLE",
                "diff": "Crowberry has needle-like leaves (not broad leaves), round black berries, and white flesh. Also edible but less flavourful"
            }
        ],
        "confusion_notes": "Bilberries are easy to identify by their angular green stems and blue-black berries with red-purple flesh. All common lookalikes on UK moorland are also edible."
    },
    {
        "name": "Gorse",
        "latin_name": "Ulex europaeus",
        "category": "Shrub",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Heathland, moorland, coastal cliffs, hedgebanks, waste ground",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Flower petals only",
        "warnings": "EXTREMELY spiny — wear thick gloves. Do NOT eat the seeds or green parts — they contain toxic alkaloids. Only the flower petals are edible. The flowers have a slight coconut aroma.",
        "description": "**Identification:** Large, dense, evergreen shrub covered in vicious spines. Bright yellow, coconut-scented pea flowers virtually year-round (peak spring). Seed pods are hairy, dark brown, 2-3cm. Extremely common on heathland and moors. **Uses:** Flower petals are edible with a coconut/almond flavour. Use to flavour tea, cordial, wine, and ice cream. Can crystallise petals. Only use the petals — remove from the green base. DO NOT eat seeds or green parts.",
        "id_keys": {
            "Spines": "Every stem is covered in vicious, sharp spines — impossible to mistake",
            "Flowers": "Bright yellow, pea-like, 1-2cm, with a distinct coconut/almond scent",
            "Shape": "Dense, tall shrub (1-3m), virtually impenetrable",
            "Evergreen": "Green all year round (spines are modified leaves)"
        },
        "foraging_tips": {
            "where": "Heathland, moorland, coastal cliffs, hedgebanks — extremely common throughout the UK",
            "when": "Flowers nearly year-round, but best and most abundant in spring (March-May)",
            "sustainable": "Pick only flower petals from a few flowers per bush. Never uproot or damage the plant",
            "danger_zone": "⚠️ WEAR THICK GLOVES — spines are very sharp. ONLY eat flower petals — seeds and green parts are TOXIC"
        },
        "lookalikes": [
            {
                "name": "Western Gorse (Ulex gallii)",
                "danger": "EDIBLE",
                "diff": "Western Gorse is smaller and flowers mainly in autumn. Flower petals are equally edible"
            },
            {
                "name": "Broom (Cytisus scoparius)",
                "danger": "EDIBLE",
                "diff": "Broom has green stems (not spiny), larger flowers, and flowers only in spring. Flower petals also edible in moderation"
            }
        ],
        "confusion_notes": "Gorse is impossible to mistake — the spiny, evergreen, yellow-flowered shrub is unique. The key safety point: ONLY eat the flower petals. Seeds and green parts contain toxic alkaloids."
    },
    {
        "name": "Crowberry",
        "latin_name": "Empetrum nigrum",
        "category": "Shrub",
        "months": ["August", "September", "October"],
        "habitat": "Heathland, moorland, mountain tops, coastal cliffs",
        "regions": ["Northern", "Coastal", "All"],
        "difficulty": 2,
        "parts": "Ripe berries",
        "warnings": "Berries are edible but bland and slightly acidic — best cooked with sugar. Do not confuse with deadly berries on moorland — always confirm ID before eating any moorland berry.",
        "description": "**Identification:** Low, creeping, evergreen shrub (10-30cm). Tiny, needle-like leaves in whorls of 3-4, dark green. Stems are woody and trailing. Small pink/purple flowers in spring. Black, shiny, round berries (4-6mm) in late summer/autumn. **Uses:** Berries are edible but bland — best cooked with sugar in pies, crumbles, and jams. High in vitamin C. Traditionally used in Scotland and Scandinavia. Can be dried. Flavour improves after frost.",
        "id_keys": {
            "Leaves": "Tiny, needle-like, dark green, in whorls of 3-4 — resemble heather but softer",
            "Berries": "Black, shiny, round, 4-6mm, with a small dimple at the tip",
            "Growth": "Low, creeping, mat-forming shrub, 10-30cm tall",
            "Habitat": "Heathland and moorland, often mixed with heather and bilberry"
        },
        "foraging_tips": {
            "where": "Heathland, moorland, and mountain tops — especially common in northern England, Scotland, and Wales",
            "when": "August to October — flavour improves after first frost",
            "sustainable": "Berries are vital for moorland birds. Take only what you need and leave plenty",
            "danger_zone": "⚠️ Moorland has few dangerous berries, but always confirm ID. If in doubt, leave it out"
        },
        "lookalikes": [
            {
                "name": "Bilberry (Vaccinium myrtillus)",
                "danger": "EDIBLE",
                "diff": "Bilberry has broad, deciduous leaves and angular stems; Crowberry has needle-like evergreen leaves and round stems"
            },
            {
                "name": "Heather (Calluna vulgaris)",
                "danger": "SAFE",
                "diff": "Heather has tiny scale-like leaves pressed to the stem and produces dry seed capsules, not fleshy berries"
            }
        ],
        "confusion_notes": "Crowberry's needle-like leaves distinguish it from bilberry (broad leaves) and other moorland berries. There are no deadly lookalikes with this combination of features."
    },
    {
        "name": "Juniper",
        "latin_name": "Juniperus communis",
        "category": "Shrub",
        "months": ["October", "November", "December", "January", "February", "March"],
        "habitat": "Heathland, moorland, rocky hillsides, chalk downland, pine woodland",
        "regions": ["Northern", "All"],
        "difficulty": 2,
        "parts": "Ripe berries (actually fleshy cones)",
        "warnings": "⚠️ Juniper is a CONIFER — do not confuse with yew (TAXUS BACCATA - DEADLY). Yew berries are red; Juniper berries are blue-black. Do not consume large quantities — juniper can cause kidney irritation. Pregnant women should avoid medicinal doses.",
        "description": "**Identification:** Evergreen shrub, variable in height (30cm-3m). Needle-like leaves in whorls of 3, sharp-pointed, dark green with a white band on the upper surface. Berries are actually fleshy cones — green in first year, blue-black and glaucous (with white bloom) when ripe in second/third year. Strong, piney, gin-like aroma. **Uses:** Ripe blue-black berries used as a spice — flavour gin, game dishes, sauerkraut, and marinades. Crush and add sparingly. Sweet-tart, piney, resinous flavour. Can be dried for storage.",
        "id_keys": {
            "Leaves": "Needle-like, in whorls of 3, with a distinctive WHITE BAND on the upper surface",
            "Berries": "Green when young, BLUE-BLACK with white bloom when ripe (second/third year). NOT red",
            "Aroma": "Strong, piney, gin-like scent when berries are crushed",
            "Size": "Variable shrub, 30cm-3m, often spreading and low on moors"
        },
        "foraging_tips": {
            "where": "Heathland, moorland, rocky hillsides — common in Scotland, rare in southern England",
            "when": "Ripe blue-black berries from October to March. Berries take 2-3 years to ripen on the plant",
            "sustainable": "⚠️ Juniper is declining in the UK. Only take a small handful from large, healthy populations. NEVER uproot. Protected in some areas",
            "danger_zone": "⚠️ CRITICAL: Do NOT confuse with YEW (red berries = DEADLY). Juniper berries are BLUE-BLACK. Yew berries are RED. When in doubt, leave it out"
        },
        "lookalikes": [
            {
                "name": "Yew (Taxus baccata)",
                "danger": "DEADLY",
                "diff": "Yew has FLAT, soft needles (not sharp, not in whorls) and RED berries with a single seed. Juniper has SHARP needles in whorls of 3 and BLUE-BLACK berries. ALL parts of yew are DEADLY except the red flesh of the berry (but the seed inside is deadly)"
            }
        ],
        "confusion_notes": "⚠️ CRITICAL: Juniper (blue-black berries, sharp needles in 3s) vs Yew (red berries, flat soft needles) — YEW IS DEADLY. The white band on juniper needles and blue-black berries are key distinguishing features. When in doubt, do NOT consume."
    }
        {
        "name": "Wild Gooseberry",
        "latin_name": "Ribes uva-crispa",
        "category": "Shrub",
        "months": ["June", "July", "August"],
        "habitat": "Hedgerows, woodland edges, scrub, old gardens, feral from cultivation",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Ripe berries (cooked or raw when fully ripe)",
        "warnings": "Extremely thorny — wear thick gloves. Unripe green berries are very tart and can cause stomach upset in quantity. Only eat fully ripe berries raw. Cook unripe or tart berries with sugar.",
        "description": "**Identification:** Straggly, thorny shrub with sharp spines at nodes and along stems. Leaves are 3-5 lobed, toothed, slightly downy. Flowers are small, greenish-pink, hanging in small groups. Berries are green, yellow, or reddish when ripe, 1-2cm, with visible veins and fine hairs. Found in hedges and old gardens gone wild. **Uses:** Ripe berries eaten raw when fully sweet. Unripe/green berries used for cooking — pies, crumbles, jams, chutneys, and gooseberry fool. High in vitamin C.",
        "id_keys": {
            "Spines": "Sharp, vicious spines at leaf nodes and along stems — wear gloves",
            "Berries": "Green, yellow, or red, 1-2cm, with visible veins and often fine hairs",
            "Leaves": "3-5 lobed, toothed, slightly downy/hairy",
            "Habitat": "Hedgerows, woodland edges, and feral from old gardens"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges, and scrub — often feral from old garden escapees",
            "when": "June to August — green berries in June for cooking, fully ripe in July-August",
            "sustainable": "Pick what you need. Leave some for birds. Wear thick gloves!",
            "danger_zone": "⚠️ Extremely thorny — thick gloves essential. Unripe berries are very tart and best cooked with sugar"
        },
        "lookalikes": [
            {
                "name": "Red Currant (Ribes rubrum)",
                "danger": "EDIBLE",
                "diff": "Red Currant has smooth, round, translucent red berries in hanging strings, and no spines on stems. Gooseberry has veined, hairy berries and thorny stems"
            }
        ],
        "confusion_notes": "Wild Gooseberry is easy to identify by its thorny stems and veined, hairy berries. There are no dangerous lookalikes in the UK with this combination of features."
    },
    {
        "name": "Red Currant",
        "latin_name": "Ribes rubrum",
        "category": "Shrub",
        "months": ["July", "August"],
        "habitat": "Hedgerows, woodland edges, stream banks, feral from cultivation",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Ripe berries",
        "warnings": "Very tart — best cooked with sugar. Do not confuse with unripe Black Currant berries. The leaves of some Ribes species can cause mild stomach upset if eaten in quantity.",
        "description": "**Identification:** Upright shrub, 1-1.5m tall, without thorns (unlike gooseberry). Leaves are 3-5 lobed, toothed, and palmate. Flowers are small, greenish-yellow, in hanging clusters. Berries are bright, translucent red, 6-8mm, hanging in long strings (racemes). Found in hedges and near old gardens. **Uses:** Berries are very tart — best cooked with sugar for jelly, jam, summer pudding, and sauces. Can be eaten raw if fully ripe but very sharp. Rich in vitamin C.",
        "id_keys": {
            "Berries": "Bright, translucent red, 6-8mm, hanging in long strings (racemes) — distinctive and unmistakable",
            "Stems": "No thorns or spines — smooth stems (unlike gooseberry)",
            "Leaves": "3-5 lobed, palmate, toothed, similar to gooseberry but on thornless stems",
            "Growth": "Upright shrub, 1-1.5m, often forming small thickets"
        },
        "foraging_tips": {
            "where": "Hedgerows, woodland edges, stream banks — often feral from old gardens",
            "when": "July to August — pick when fully red and slightly soft",
            "sustainable": "Pick strings of berries with scissors. Leave some for birds",
            "danger_zone": "Very tart — best cooked with sugar. No dangerous lookalikes with red berries in strings"
        },
        "lookalikes": [
            {
                "name": "White Currant (Ribes rubrum var. alba)",
                "danger": "EDIBLE",
                "diff": "White/pale yellow berries in strings — a colour variant of Red Currant, equally edible and slightly sweeter"
            },
            {
                "name": "Black Currant (Ribes nigrum)",
                "danger": "EDIBLE",
                "diff": "Black berries with a strong, characteristic blackcurrant scent when crushed. Leaves have resin glands underneath (appear as yellow dots)"
            }
        ],
        "confusion_notes": "Red Currants are easy to identify by their bright red, translucent berries hanging in long strings on a thornless shrub. There are no dangerous lookalikes with this appearance."
    },
    {
        "name": "Barberry",
        "latin_name": "Berberis vulgaris",
        "category": "Shrub",
        "months": ["September", "October"],
        "habitat": "Hedgerows, woodland edges, scrub, naturalised on chalk and limestone",
        "regions": ["Southern", "All"],
        "difficulty": 2,
        "parts": "Ripe berries (cooked, with sugar)",
        "warnings": "Berries are VERY tart and contain seeds — best cooked and strained. Some people are sensitive. Do NOT eat the roots, bark, or leaves — they contain berberine and are medicinal, not food. Avoid during pregnancy without medical advice.",
        "description": "**Identification:** Deciduous shrub, 1-3m, with grey-brown bark and VERY sharp triple spines at each node. Leaves are small, oval, in clusters. Flowers are small, yellow, hanging in clusters. Berries are bright red, oblong, 8-12mm, very tart, hanging in small clusters. **Uses:** Berries are extremely tart but high in vitamin C. Cook with sugar for jelly, jams, and sauces. Traditional accompaniment to mutton. Can be dried. Strain out seeds. Persian and Middle Eastern cooking uses dried barberries extensively.",
        "id_keys": {
            "Spines": "VERY sharp triple spines (3-pronged) at each node — vicious, handle with thick gloves",
            "Berries": "Bright red, oblong, 8-12mm, hanging in small clusters — very tart/sour",
            "Leaves": "Small, oval, in clusters on short shoots between the spines",
            "Flowers": "Small, yellow, hanging in racemes (spring)"
        },
        "foraging_tips": {
            "where": "Hedgerows and scrub on chalk and limestone, especially in southern England. Now uncommon in the wild",
            "when": "September to October — pick when fully red",
            "sustainable": "Pick a few clusters per bush. Barberry is now uncommon in the wild — consider growing your own",
            "danger_zone": "⚠️ Vicious spines — thick gloves essential. Only eat berries. Do NOT eat leaves, bark, or roots"
        },
        "lookalikes": [
            {
                "name": "Ornamental Berberis species (e.g., Berberis darwinii, B. thunbergii)",
                "danger": "EDIBLE",
                "diff": "Ornamental species have similar berries that are also edible when ripe, though varying in palatability. All have the distinctive sharp spines"
            }
        ],
        "confusion_notes": "Barberry is easy to identify by its vicious triple spines and bright red oblong berries. No dangerous lookalikes have this combination. Only eat the ripe berries — leaves, bark, and roots contain berberine."
    },
    {
        "name": "Fuchsia",
        "latin_name": "Fuchsia magellanica",
        "category": "Shrub",
        "months": ["August", "September", "October", "November"],
        "habitat": "Coastal hedges, gardens, naturalised in mild western areas (Cornwall, Wales, Ireland, Scotland)",
        "regions": ["Coastal", "Western"],
        "difficulty": 1,
        "parts": "Ripe berries (dark purple/black)",
        "warnings": "Only eat the berries of Fuchsia magellanica and common garden fuchsias. Avoid all other parts of the plant. Some people may have mild stomach upset from eating large quantities. The flowers are also edible in small quantities.",
        "description": "**Identification:** Deciduous or semi-evergreen shrub, 1-3m, with arching branches. Small, dark green leaves. Iconic pendant flowers with bright red-pink outer petals and purple inner petals. Berries are oblong, dark purple-black when ripe, 8-15mm, with a slightly sweet, mild flavour. Extremely common in western coastal gardens and hedges. **Uses:** Ripe berries eaten raw — mild, slightly sweet, grape-like flavour with a peppery aftertaste. Can be used in jams and jellies. Flowers are also edible — decorative in salads.",
        "id_keys": {
            "Flowers": "Iconic pendant flowers — red-pink outer petals, purple inner petals. Impossible to mistake for anything else",
            "Berries": "Oblong, dark purple-black when ripe, 8-15mm, hanging beneath the flower",
            "Leaves": "Small, dark green, oval, in pairs along arching stems",
            "Growth": "Arching shrub, 1-3m, common in western coastal hedges"
        },
        "foraging_tips": {
            "where": "Coastal hedges and gardens in mild western areas — Cornwall, Wales, western Scotland, Ireland",
            "when": "August to November — pick when berries are dark purple-black and slightly soft",
            "sustainable": "Pick a few berries per bush. Leave plenty for birds and for the plant to look attractive",
            "danger_zone": "Only eat ripe berries. Common garden fuchsias are safe. Avoid other parts of the plant"
        },
        "lookalikes": [
            {
                "name": "Other Fuchsia varieties",
                "danger": "EDIBLE",
                "diff": "Most common garden fuchsias produce edible berries, though some have very small or dry fruit. F. magellanica has the best-flavoured berries"
            }
        ],
        "confusion_notes": "Fuchsia is one of the easiest plants to identify — the pendant red-purple flowers are unmistakable. The berries are safe to eat. No dangerous lookalikes have this flower shape."
    }
]
