# data/edible_trees.py
# Auto-generated by split_plants.py
# 11 Coastal plants

EDIBLE_TREES = [
    {
        "name": "Lime (Leaves)",
        "latin_name": "Tilia cordata",
        "category": "Tree",
        "months": ['April', 'May', 'June', 'July'],
        "habitat": "Woodlands, Parks",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Young leaves",
        "warnings": "Older leaves are tough and can be a choking hazard.",
        "description": "**Identification:** Heart-shaped leaves, slightly serrated edges. **Uses:** Excellent salad green (mild, slightly sweet).",
        "id_keys": {
            "Leaves": "Heart-shaped, hairless on top",
            "Bark": "Smooth, grey",
            "Flowers": "Yellow-white clusters",
        },
        "foraging_tips": {
            "where": "Woodlands and parks. Look for low branches.",
            "when": "Best in Spring (April-June) when leaves are young.",
            "sustainable": "Pick a few leaves from each branch, do not strip.",
            "danger_zone": "Safe. No dangerous lookalikes.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Common Lime is a hybrid. All Lime trees have edible leaves.",
            },
        ],
        "confusion_notes": "Safe. One of the best tree leaves for eating.",
    },
    {
        "name": "Oak (Acorns)",
        "latin_name": "Quercus robur",
        "category": "Tree",
        "months": ['September', 'October', 'November'],
        "habitat": "Woodlands, Hedgerows",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "Nuts (Acorns)",
        "warnings": "MUST BE LEACHED (soaked) to remove tannins. Very bitter raw.",
        "description": "**Identification:** Lobed leaves (like a curved hand). Acorns in rough cups.",
        "id_keys": {
            "Leaves": "Lobed (wavy edges)",
            "Fruit": "Acorn in a rough cup",
            "Bark": "Rough, ridged",
        },
        "foraging_tips": {
            "where": "Woodlands, Hedgerows.",
            "when": "Autumn.",
            "sustainable": "Take only what you need; wildlife depend on them.",
            "danger_zone": "Raw acorns cause stomach upset due to tannins. Must be leached in running water.",
        },
        "lookalikes": [
            {
                "name": "Sessile Oak",
                "danger": "EDIBLE",
                "diff": "Sessile Oak acorns have shorter stalks. Both are edible.",
            },
        ],
        "confusion_notes": "Safe if processed. Tannins cause stomach upset if eaten raw.",
    },
    {
        "name": "Crab Apple",
        "latin_name": "Malus sylvestris",
        "category": "Tree",
        "months": ['September', 'October'],
        "habitat": "Woodlands, Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Fruit",
        "warnings": "Very tart/sour. Best for jams/jellies.",
        "description": "**Identification:** Small, round apples (golf ball size). Yellow/Green/Red. Often spiky look.",
        "id_keys": {
            "Fruit": "Small apples, long stalks",
            "Taste": "Very sour, dry mouth",
            "Leaves": "Oval, serrated",
        },
        "foraging_tips": {
            "where": "Woodlands, hedgerows.",
            "when": "Autumn.",
            "sustainable": "Use fallen fruit or pick sparingly.",
            "danger_zone": "Very tart. May cause stomach upset if eaten raw in quantity.",
        },
        "lookalikes": [
            {
                "name": "Cultivated Apples",
                "danger": "EDIBLE",
                "diff": "Cultivated apples are larger and sweeter.",
            },
        ],
        "confusion_notes": "Safe. Small, sour apples. All apple-like fruits are edible.",
    },
    {
        "name": "Elderflower",
        "latin_name": "Sambucus nigra",
        "category": "Tree",
        "months": ['May', 'June'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Flowers",
        "warnings": "Do not eat raw berries. Flowers must be cooked/brewed.",
        "description": "**Identification:** Flat-topped clusters of tiny, creamy-white, sweet-smelling flowers on a shrubby tree.",
        "id_keys": {
            "Flowers": "Flat, creamy-white clusters, sweet smell",
            "Leaves": "Compound, 5-7 leaflets, opposite",
            "Bark": "Corky, warty",
        },
        "foraging_tips": {
            "where": "Hedgerows, woods.",
            "when": "Late Spring/Early Summer.",
            "sustainable": "Pick clusters, leave plenty for berries.",
            "danger_zone": "Safe. Smells of sweet summer.",
        },
        "lookalikes": [
            {
                "name": "Hemlock",
                "danger": "DEADLY",
                "diff": "Hemlock has white flowers on umbels (spokes) and purple spots on stems. Elder has flat clusters and woody bark.",
            },
        ],
        "confusion_notes": "CRITICAL: Hemlock has purple spots on its stem and smells of mouse urine. Elder has woody bark and smells of sweet flowers.",
    },
    {
        "name": "Hawthorn",
        "latin_name": "Crataegus monogyna",
        "category": "Tree",
        "months": ['May', 'September', 'October'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Flowers, Berries (Haws)",
        "warnings": "Flowers smell faintly of almonds. Seeds contain cyanide, do not eat.",
        "description": "**Identification:** Thorny shrub. Deeply lobed leaves. White 'May' flowers. Red haws in autumn.",
        "id_keys": {
            "Leaves": "Deeply lobed (oak-like but smaller)",
            "Flowers": "White, 5 petals, 'May' blossom",
            "Fruit": "Red haws (single seed inside)",
        },
        "foraging_tips": {
            "where": "Hedgerows.",
            "when": "May for flowers, Autumn for haws.",
            "sustainable": "Very common hedgerow plant.",
            "danger_zone": "Safe. Spit out the seeds.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Look for 'May' flower in spring to identify.",
            },
        ],
        "confusion_notes": "Safe. Look for 'May' flower in spring to identify. The berries (haws) are edible but don't eat the seeds (pips).",
    },
    {
        "name": "Sweet Chestnut",
        "latin_name": "Castanea sativa",
        "category": "Tree",
        "months": ['October', 'November'],
        "habitat": "Woodlands, Parks",
        "regions": ['Southern'],
        "difficulty": 2,
        "parts": "Nuts",
        "warnings": "Must be cooked. Shell is sharp.",
        "description": "**Identification:** Large tree with long, toothed leaves. Nuts are in VERY SPIKY cases.",
        "id_keys": {
            "Leaves": "Long, narrow, toothed",
            "Nut Case": "VERY SPIKY, like a hedgehog",
            "Nuts": "Pointed, dark brown, often 2-3 per case",
        },
        "foraging_tips": {
            "where": "Southern woods, parks.",
            "when": "Autumn.",
            "sustainable": "Take fallen nuts.",
            "danger_zone": "CRITICAL: Case must be VERY SPIKY.",
        },
        "lookalikes": [
            {
                "name": "Horse Chestnut",
                "danger": "POISONOUS",
                "diff": "Conker cases are smooth/warty. Sweet Chestnut cases are VERY SPIKY.",
            },
        ],
        "confusion_notes": "CRITICAL: Sweet Chestnut has a VERY SPIKY case. Horse Chestnut (conkers) has a SMOOTH/WARTY case. If the case isn't spiky, it's NOT Sweet Chestnut.",
    },
    {
        "name": "Pine Needles",
        "latin_name": "Pinus sylvestris",
        "category": "Tree",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Woodlands, Heathlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Needles",
        "warnings": "Good for tea. High in Vitamin C.",
        "description": "**Identification:** Evergreen tree. Needles are ROUND and in bundles (fascicles) of 2-5.",
        "id_keys": {
            "Needles": "ROUND, in bundles of 2-5",
            "Bark": "Reddish-brown, flaky upper bark",
            "Cones": "Woody, round",
        },
        "foraging_tips": {
            "where": "Coniferous woods.",
            "when": "Year-round (best in Spring).",
            "sustainable": "Snip a few needles.",
            "danger_zone": "CRITICAL: Needles must be ROUND and in bundles.",
        },
        "lookalikes": [
            {
                "name": "Yew",
                "danger": "DEADLY",
                "diff": "Yew needles are FLAT and single, not in bundles.",
            },
        ],
        "confusion_notes": "CRITICAL: Pine needles are ROUND and in BUNDLES. Yew needles are FLAT and deadly. If the needles are flat, do NOT make tea from them.",
    },
    {
        "name": "Silver Birch",
        "latin_name": "Betula pendula",
        "category": "Tree",
        "months": ['March', 'April', 'May'],
        "habitat": "Woodlands, Heathlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Sap, Leaves",
        "warnings": "Sap must be collected in Spring. Leaves are diuretic.",
        "description": "**Identification:** White, peeling, papery bark. Small, triangular, toothed leaves.",
        "id_keys": {
            "Bark": "White, peeling, papery",
            "Leaves": "Small, triangular, doubly toothed",
            "Catkins": "Pendulous (hanging)",
        },
        "foraging_tips": {
            "where": "Woods, heaths.",
            "when": "Spring for sap, Summer for leaves.",
            "sustainable": "Tapping sap can harm tree. Only tap large trees.",
            "danger_zone": "Safe. Identify by the white peeling bark.",
        },
        "lookalikes": [
            {
                "name": "Downy Birch",
                "danger": "EDIBLE",
                "diff": "Downy Birch has hairy twigs and less peeling bark. Also edible.",
            },
        ],
        "confusion_notes": "Safe. Identify by the white peeling bark. Downy Birch is also edible.",
    },
    {
        "name": "Beech Leaves",
        "latin_name": "Fagus sylvatica",
        "category": "Tree",
        "months": ['April', 'May', 'June'],
        "habitat": "Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Young leaves",
        "warnings": "Only eat young, transparent leaves. Older leaves are too tough.",
        "description": "**Identification:** Tall tree with smooth grey bark. Leaves are oval with wavy edges and soft hairs.",
        "id_keys": {
            "Bark": "Smooth, grey",
            "Leaves": "Oval, wavy edges, soft hairs when young",
            "Buds": "Pointed, brown",
        },
        "foraging_tips": {
            "where": "Woods.",
            "when": "Spring (only young leaves).",
            "sustainable": "Pick a few leaves from each branch.",
            "danger_zone": "Safe. Best when young and transparent.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive smooth grey bark and oval leaves.",
            },
        ],
        "confusion_notes": "Safe. One of the best tree leaves for eating. Only eat young, transparent leaves.",
    },
    {
        "name": "Elderberry",
        "latin_name": "Sambucus nigra",
        "category": "Tree",
        "months": ['August', 'September'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "MUST be cooked. Raw berries cause vomiting. Red berries are POISONOUS.",
        "description": "**Identification:** Clusters of small, black/purple berries on red stems. Shrub with corky bark.",
        "id_keys": {
            "Fruit": "Black/purple, small, in flat clusters",
            "Stem": "Red/purple stems holding berries",
            "Bark": "Corky, warty",
        },
        "foraging_tips": {
            "where": "Hedgerows, woods.",
            "when": "Autumn.",
            "sustainable": "Leave some for birds.",
            "danger_zone": "CRITICAL: Must be COOKED. Raw berries cause vomiting.",
        },
        "lookalikes": [
            {
                "name": "Dwarf Elder",
                "danger": "POISONOUS",
                "diff": "Dwarf Elder has upright berry clusters and smells unpleasant.",
            },
        ],
        "confusion_notes": "CRITICAL: Elderberries MUST be cooked. Raw berries cause vomiting. Red elderberries are POISONOUS.",
    },
    {
        "name": "Rowan",
        "latin_name": "Sorbus aucuparia",
        "category": "Tree",
        "months": ['August', 'September', 'October'],
        "habitat": "Woodlands, Hillsides, Gardens",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Very bitter raw. Must be cooked. Contains parasorbic acid (cooked = sorbic acid, safe).",
        "description": "**Identification:** Tree with paired leaflets. Bright orange-red berries in large clusters.",
        "id_keys": {
            "Berries": "Orange-red, large clusters",
            "Leaves": "Paired leaflets, serrated",
            "Buds": "Hairy, sticky buds",
        },
        "foraging_tips": {
            "where": "Hills, woods, gardens.",
            "when": "Autumn.",
            "sustainable": "Leave some for birds.",
            "danger_zone": "CRITICAL: Must be COOKED. Raw berries cause stomach upset.",
        },
        "lookalikes": [
            {
                "name": "Whitebeam",
                "danger": "EDIBLE",
                "diff": "Whitebeam has white berries. Rowan has red/orange.",
            },
        ],
        "confusion_notes": "CRITICAL: Rowan berries MUST be cooked. Raw they contain parasorbic acid which causes stomach upset. Cooked they are safe.",
    },
        {
        "name": "Ash (Keys)",
        "latin_name": "Fraxinus excelsior",
        "category": "Tree",
        "months": ["September", "October"],
        "habitat": "Woodlands, Hedgerows, Parks",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Seeds (Keys), Leaves",
        "warnings": "Pickled ash keys are traditional. Do not eat raw in quantity.",
        "description": "**Identification:** Tall tree with compound leaves (9-13 leaflets). Distinctive paddle-shaped seeds in hanging bunches called 'keys'. Grey bark with diamond-shaped ridges.",
        "id_keys": {
            "Seeds": "Paddle-shaped 'keys' in bunches",
            "Bark": "Pale grey, diamond-shaped ridges",
            "Leaves": "Compound, 9-13 leaflets, opposite"
        },
        "foraging_tips": {
            "where": "Woodlands, hedgerows, parks.",
            "when": "Autumn for keys, Spring for young leaves.",
            "sustainable": "Pick keys from the ground. Very common tree.",
            "danger_zone": "Safe. The 'keys' (seeds) can be pickled. Young leaves edible in salads."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Distinctive keys and compound leaves make Ash easy to identify."}
        ],
        "confusion_notes": "Safe. The 'keys' (seeds) are distinctive paddle shapes. Can be pickled like capers."
    },
    {
        "name": "Willow (Bark)",
        "latin_name": "Salix species",
        "category": "Tree",
        "months": ["January", "February", "March", "April"],
        "habitat": "Riverbanks, Wet areas, Lakesides",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Bark (for tea/medicine), Catkins",
        "warnings": "Contains salicin (natural aspirin). Avoid if allergic to aspirin. Do not take with blood thinners.",
        "description": "**Identification:** Tree with long, narrow leaves. Often found near water. Catkins appear in spring. Bark can be chewed or made into tea.",
        "id_keys": {
            "Leaves": "Long, narrow, pale underneath",
            "Habitat": "Always near water",
            "Bark": "Grey-brown, fissured on older trees",
            "Catkins": "Fluffy, appear before leaves in spring"
        },
        "foraging_tips": {
            "where": "Riverbanks, lakesides, damp areas.",
            "when": "Late winter/early spring for bark.",
            "sustainable": "Strip bark from small branches only, never ring the trunk.",
            "danger_zone": "Contains salicin. Avoid if allergic to aspirin."
        },
        "lookalikes": [
            {"name": "Pussy Willow", "danger": "EDIBLE", "diff": "Pussy Willow is a type of willow. All willows contain salicin."}
        ],
        "confusion_notes": "Safe. All willows contain salicin. Identify by location near water and long, narrow leaves."
    },
    {
        "name": "Field Maple",
        "latin_name": "Acer campestre",
        "category": "Tree",
        "months": ["April", "May", "September", "October"],
        "habitat": "Hedgerows, Woodlands, Fields",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Sap, Young leaves",
        "warnings": "Young leaves edible in salads. Sap can be drunk like birch sap.",
        "description": "**Identification:** Small tree with 5-lobed leaves (like a small maple). Leaves turn a beautiful red/gold in autumn. Winged seeds in pairs.",
        "id_keys": {
            "Leaves": "5-lobed, small, rounded lobes",
            "Seeds": "Paired wings (helicopters)",
            "Bark": "Fissured, corky on older trees"
        },
        "foraging_tips": {
            "where": "Hedgerows, field edges, woods.",
            "when": "Spring for leaves, Spring for sap.",
            "sustainable": "Pick a few young leaves. Tap sap carefully.",
            "danger_zone": "Safe. Distinctive small maple-like leaves."
        },
        "lookalikes": [
            {"name": "Sycamore", "danger": "EDIBLE", "diff": "Sycamore is larger with bigger, more pointed leaves. Both have winged seeds."}
        ],
        "confusion_notes": "Safe. Field Maple has small, rounded 5-lobed leaves. Sycamore has larger, more pointed leaves."
    },
    {
        "name": "Wych Elm (Seeds)",
        "latin_name": "Ulmus glabra",
        "category": "Tree",
        "months": ["April", "May"],
        "habitat": "Woodlands, Riverbanks, Hillsides",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Young seeds (samaras)",
        "warnings": "Only eat young, green samaras. Not Dutch Elm (which is rare).",
        "description": "**Identification:** Large, rough leaves with pointed tips. Round, winged seeds (samaras) in spring. Bark is grey-brown with cross-hatching.",
        "id_keys": {
            "Leaves": "Large, rough, pointed tip, asymmetrical base",
            "Seeds": "Round, flat, winged (samaras)",
            "Bark": "Grey-brown, cross-hatched"
        },
        "foraging_tips": {
            "where": "Woodlands, riverbanks, hillsides.",
            "when": "Spring (April-May) for young seeds.",
            "sustainable": "Pick a few samaras from each tree.",
            "danger_zone": "Only eat young, green samaras. They become papery and inedible when dry."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "The round, winged samaras are distinctive."}
        ],
        "confusion_notes": "Safe. The round, flat, winged seeds (samaras) are distinctive. Only eat them when young and green."
    },
    {
        "name": "Walnut",
        "latin_name": "Juglans regia",
        "category": "Tree",
        "months": ["September", "October", "November"],
        "habitat": "Gardens, Parkland, Farmland",
        "regions": ["Southern", "Central"],
        "difficulty": 1,
        "parts": "Nuts",
        "warnings": "Green husks stain everything brown. Wear gloves when handling fresh walnuts.",
        "description": "**Identification:** Large tree with compound leaves (5-9 leaflets). Round, green husks containing walnuts. Bark is grey and fissured.",
        "id_keys": {
            "Leaves": "Compound, 5-9 leaflets, aromatic",
            "Fruit": "Green, round husk containing walnut",
            "Bark": "Grey, broadly fissured"
        },
        "foraging_tips": {
            "where": "Gardens, parkland, farmland.",
            "when": "Autumn.",
            "sustainable": "Pick fallen nuts. Often found near old settlements.",
            "danger_zone": "Green husks stain skin and clothing. Wear gloves."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Large, round green husks containing a walnut are distinctive."}
        ],
        "confusion_notes": "Safe. The large, round green husks containing a walnut inside are distinctive. Wear gloves — the husks stain."
    },
    {
        "name": "Whitebeam",
        "latin_name": "Sorbus aria",
        "category": "Tree",
        "months": ["September", "October"],
        "habitat": "Woodlands, Chalk downs, Parks",
        "regions": ["Southern", "Central"],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "Best after frost or bletted (softened). Astringent raw.",
        "description": "**Identification:** Leaves are white underneath (hence 'white beam'). Red berries in clusters. Oval, toothed leaves with felt-like white undersides.",
        "id_keys": {
            "Leaves": "Green on top, white/felt underneath",
            "Berries": "Red, in clusters",
            "Bark": "Smooth, grey"
        },
        "foraging_tips": {
            "where": "Chalk downs, woodlands, parks.",
            "when": "Autumn.",
            "sustainable": "Leave some for birds.",
            "danger_zone": "Best after frost or bletted. Astringent raw."
        },
        "lookalikes": [
            {"name": "Rowan", "danger": "EDIBLE", "diff": "Rowan has orange-red berries and compound leaves. Whitebeam has red berries and simple leaves."}
        ],
        "confusion_notes": "Safe. Whitebeam has simple leaves that are white underneath. Rowan has compound leaves."
    },
    {
        "name": "Hornbeam (Seeds)",
        "latin_name": "Carpinus betulus",
        "category": "Tree",
        "months": ["September", "October"],
        "habitat": "Woodlands, Hedgerows",
        "regions": ["Southern", "Eastern"],
        "difficulty": 2,
        "parts": "Seeds (small nutlets)",
        "warnings": "Very small yield. More for interest than sustenance.",
        "description": "**Identification:** Fluted, muscular-looking bark. Leaves are oval, double-toothed, with clear veins. Seeds are small, ribbed nutlets in leafy bracts.",
        "id_keys": {
            "Bark": "Smooth, grey, fluted (muscular look)",
            "Leaves": "Oval, double-toothed, prominent veins",
            "Seeds": "Small ribbed nutlets in leafy bracts"
        },
        "foraging_tips": {
            "where": "Hedgerows, woods (especially SE England).",
            "when": "Autumn.",
            "sustainable": "Small yield. More for curiosity.",
            "danger_zone": "Safe but fiddly. Very small nutlets."
        },
        "lookalikes": [
            {"name": "Beech", "danger": "EDIBLE", "diff": "Beech has smooth grey bark (not fluted) and larger, softer leaves."}
        ],
        "confusion_notes": "Safe. The fluted, muscular bark is distinctive. Small nutlets are edible but fiddly."
    },
    {
        "name": "Sea Buckthorn",
        "latin_name": "Hippophae rhamnoides",
        "category": "Shrub",
        "months": ["September", "October"],
        "habitat": "Coastal, Sand dunes",
        "regions": ["Coastal"],
        "difficulty": 2,
        "parts": "Berries",
        "warnings": "Extremely sour. Very high in Vitamin C. Thorny bush!",
        "description": "**Identification:** Thorny shrub with silvery-grey narrow leaves. Bright orange berries clustered tightly along branches. Often found on sand dunes.",
        "id_keys": {
            "Leaves": "Narrow, silvery-grey, willow-like",
            "Berries": "Bright orange, tightly clustered on stems",
            "Thorns": "Sharp thorns on branches"
        },
        "foraging_tips": {
            "where": "Sand dunes, coastal defences.",
            "when": "Autumn (September-October).",
            "sustainable": "Cut berry-laden branches and freeze to shake off berries. Leave most for wildlife.",
            "danger_zone": "Very thorny! Wear thick gloves. Extremely sour — best in juice or syrup."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Distinctive silver leaves and bright orange berries on a thorny coastal shrub."}
        ],
        "confusion_notes": "Safe. The silvery leaves and bright orange berries on thorny branches by the coast are distinctive. Extremely high in Vitamin C."
    },
]
