# data/edible_seaweed.py
# Auto-generated by split_plants.py
# 1 Coastal plants

EDIBLE_SEAWEED = [
    {
        "name": "Dulse",
        "latin_name": "Palmaria palmata",
        "category": "Seaweed",
        "months": ['May', 'June', 'July', 'August', 'September'],
        "habitat": "Coastal Rocks",
        "regions": ['Coastal'],
        "difficulty": 2,
        "parts": "Fronds",
        "warnings": "Wash well. Eat raw or dried.",
        "description": "**Identification:** Dark red, hand-shaped (palmate) fronds. Leathery texture.",
        "id_keys": {
            "Colour": "Dark red / purplish",
            "Shape": "Hand-shaped (lobes)",
            "Texture": "Leathery, soft when wet",
        },
        "foraging_tips": {
            "where": "Rocky shores (attached to rocks).",
            "when": "Summer.",
            "sustainable": "Snip above holdfast.",
            "danger_zone": "Safe. Wash to remove sand.",
        },
        "lookalikes": [
            {
                "name": "Other Red Seaweeds",
                "danger": "EDIBLE",
                "diff": "Most red seaweeds are edible, but Dulse is distinct.",
            },
        ],
        "confusion_notes": "Safe. Very distinct — dark red, hand-shaped, leathery texture. Other seaweeds are mostly edible but check ID.",
    },
]
