# data/poisonous_plants.py
# Auto-generated by split_plants.py
# 26 poisonous plants/fungi

POISONOUS_PLANTS = [
    {
        "name": "Deadly Nightshade",
        "latin_name": "Atropa belladonna",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Woodlands, Gardens, Waste Ground",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "EXTREME. Fatal in small doses. Do not handle without gloves.",
        "description": "**Identification:** A tall, bushy perennial. Bell-shaped purple flowers. Shiny black berries the size of cherries. **Danger:** Causes rapid heartbeat, dilated pupils, hallucinations, and death.",
        "id_keys": {
            "Flowers": "Purple, bell-shaped, nodding",
            "Berries": "Shiny black, cherry-sized, solitary",
            "Leaves": "Oval, pointed, large",
        },
        "danger_tips": {
            "where": "Shady, damp woods and calcareous soils.",
            "when": "Berries appear late summer.",
            "sustainable": "Do not pick. Remove carefully if found in gardens.",
            "danger_zone": "☠️ DEADLY. Just 2-3 berries can kill a child. Do NOT touch.",
        },
        "lookalikes": [
            {
                "name": "Bilberry",
                "danger": "EDIBLE",
                "diff": "Bilberry is a low shrub with small, matte blue-black berries. Deadly Nightshade is a tall leafy plant with large shiny black berries.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Deadly Nightshade has LARGE shiny black berries (cherry-sized) on a TALL leafy plant. Bilberry is a LOW shrub with SMALL matte blue-black berries. If the berries are cherry-sized on a tall plant, do NOT touch it.",
    },
    {
        "name": "Foxglove",
        "latin_name": "Digitalis purpurea",
        "category": "Plant",
        "months": ['June', 'July', 'August'],
        "habitat": "Gardens, Woodlands, Acid Soils",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "All parts",
        "warnings": "HIGH. Can cause heart failure. Toxins can be absorbed through skin.",
        "description": "**Identification:** Tall spikes of pink/purple trumpet flowers. Large, fuzzy leaves at the base. **Danger:** Contains digitalis which affects heart rate.",
        "id_keys": {
            "Flowers": "Pink/Purple trumpets, spotted inside",
            "Stem": "Tall, green, sturdy spike",
            "Leaves": "Large, rosette at base, soft texture",
        },
        "danger_tips": {
            "where": "Common in gardens, woodland clearings, and heaths.",
            "when": "Flowering in summer.",
            "sustainable": "Admire from a distance. Do NOT touch.",
            "danger_zone": "☠️ HIGH. Can cause heart failure. Toxins can be absorbed through skin.",
        },
        "lookalikes": [
            {
                "name": "Comfrey",
                "danger": "EDIBLE",
                "diff": "Comfrey has bell-shaped flowers that hang in loose clusters. Foxglove flowers are distinct trumpets growing up a single tall spike.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Foxglove has tall spikes of PINK/PURPLE trumpet flowers. Comfrey has smaller bell-shaped flowers that hang in loose clusters. Foxglove is a single tall spike with distinct trumpet shapes.",
    },
    {
        "name": "Hemlock",
        "latin_name": "Conium maculatum",
        "category": "Plant",
        "months": ['April', 'May', 'June', 'July'],
        "habitat": "Rivers, Damp areas, Roadsides",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "All parts",
        "warnings": "EXTREME. Deadliest plant in the UK. Mistaken for wild celery/parsley.",
        "description": "**Identification:** Tall plant (up to 2m). Smooth stem with distinctive purple spots. Smells of mouse urine. **Danger:** Causes respiratory paralysis.",
        "id_keys": {
            "Stem": "Smooth, hollow, purple spots (critical ID)",
            "Smell": "Unpleasant, mouse urine smell when crushed",
            "Flowers": "White umbels (flat-topped clusters)",
        },
        "danger_tips": {
            "where": "Damp ditches, riverbanks, waste ground.",
            "when": "Spring and early summer.",
            "sustainable": "Never cut or smell closely.",
            "danger_zone": "☠️ DEADLY. Respiratory failure, death. Toxins can be absorbed through skin. Do NOT touch.",
        },
        "lookalikes": [
            {
                "name": "Wild Carrot",
                "danger": "EDIBLE",
                "diff": "Wild Carrot has HAIRY stems. Hemlock has SMOOTH stems with purple spots.",
            },
            {
                "name": "Cow Parsley",
                "danger": "EDIBLE",
                "diff": "Cow Parsley stems are ridged/grooved and green. Hemlock stems are smooth with purple blotches.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Hemlock has SMOOTH stems with PURPLE SPOTS and smells of MOUSE URINE. Wild Carrot has HAIRY green stems and smells of CARROT. If you see purple spots, do NOT touch it.",
    },
    {
        "name": "Hemlock Water Dropwort",
        "latin_name": "Oenanthe crocata",
        "category": "Plant",
        "months": ['April', 'May', 'June', 'July'],
        "habitat": "Riverbanks, Wet ground, Ditches",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "All parts (Roots deadliest)",
        "warnings": "EXTREME. 'Dead Man's Fingers'. Rapid death.",
        "description": "**Identification:** Grows in water/wet mud. White flowers. Roots are tuberous, resembling a cluster of pale fingers. **Danger:** Causes seizures and death rapidly.",
        "id_keys": {
            "Root": "Tubers like fingers (Dead Man's Fingers)",
            "Habitat": "Wet ground, feet in water",
            "Stem": "Grooved, hollow",
        },
        "danger_tips": {
            "where": "Riverbanks, streams, wet ditches.",
            "when": "Spring and Summer.",
            "sustainable": "Never dig roots in wet areas.",
            "danger_zone": "☠️ DEADLY. Rapid onset seizures, coma, death. Do NOT touch.",
        },
        "lookalikes": [
            {
                "name": "Wild Parsnip",
                "danger": "EDIBLE",
                "diff": "Wild Parsnip has YELLOW flowers. Dropwort has WHITE flowers.",
            },
            {
                "name": "Pignut",
                "danger": "EDIBLE",
                "diff": "Pignut grows in DRY meadows. Dropwort grows in WET ground/ditches. If your feet are wet, stop digging.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Grows in WET ground (feet in water). Roots look like fingers ('Dead Man's Fingers'). Pignut grows in DRY meadows. If your feet are wet, STOP digging.",
    },
    {
        "name": "Lords and Ladies",
        "latin_name": "Arum maculatum",
        "category": "Plant",
        "months": ['March', 'April', 'May', 'August', 'September'],
        "habitat": "Hedgerows, Woods",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts",
        "warnings": "HIGH. Causes immediate burning pain and blisters.",
        "description": "**Identification:** Arrow-shaped leaves (often with black spots). Orange-red berries on a spike. **Danger:** Calcium oxalate crystals needle the tongue/throat.",
        "id_keys": {
            "Leaves": "Arrow-shaped, often spotted black",
            "Berries": "Bright orange cluster on a spike",
            "Flower": "Pale green 'hood' (spathe)",
        },
        "danger_tips": {
            "where": "Shady hedgerows and woods.",
            "when": "Leaves in Spring, Berries in Autumn.",
            "sustainable": "Do NOT touch or taste.",
            "danger_zone": "☠️ HIGH. Instant burning pain and blisters. Do NOT put in your mouth.",
        },
        "lookalikes": [
            {
                "name": "Sorrel",
                "danger": "EDIBLE",
                "diff": "Sorrel leaves are arrow-shaped but smaller, usually unspotted, and taste lemony. Lords & Ladies are large, leathery, and have NO smell.",
            },
            {
                "name": "Wild Garlic",
                "danger": "EDIBLE",
                "diff": "Wild Garlic smells strongly of garlic. Lords & Ladies has NO garlic smell and different leaf texture.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Lords and Ladies has arrow-shaped leaves (often with black spots) and burns your mouth INSTANTLY. Wild Garlic SMELLS of garlic. Sorrel TASTES of lemon. Lords and Ladies does NEITHER.",
    },
    {
        "name": "Yew",
        "latin_name": "Taxus baccata",
        "category": "Tree",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Churchyards, Gardens, Woodlands",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Needles, Seeds",
        "warnings": "EXTREME. All parts deadly except the red berry flesh.",
        "description": "**Identification:** Dark evergreen tree. Flat, dark green needles. Red fleshy 'berries' (arils) with a dark seed inside. **Danger:** Causes cardiac arrest.",
        "id_keys": {
            "Needles": "Flat, dark green, pointed",
            "Fruit": "Red cup (aril) containing a dark seed",
            "Bark": "Reddish-brown, peeling",
        },
        "danger_tips": {
            "where": "Churchyards, gardens, woodlands.",
            "when": "Evergreen all year. Berries in Autumn.",
            "sustainable": "Never eat the seed inside the red berry.",
            "danger_zone": "☠️ DEADLY. Sudden death, no antidote. Do NOT eat any part except the red berry flesh (and even that is risky).",
        },
        "lookalikes": [
            {
                "name": "Pine",
                "danger": "EDIBLE",
                "diff": "Pine needles are ROUND and long. Yew needles are FLAT, short, and darker.",
            },
            {
                "name": "Fir",
                "danger": "EDIBLE",
                "diff": "Fir needles are flat but attach to the stem like a suction cup. Yew needles are distinct dark green.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Yew needles are FLAT. Pine needles are ROUND and in bundles. If the needles are flat, do NOT make tea from them. The red berry flesh is the only safe part — the SEED inside is deadly.",
    },
    {
        "name": "Spindle",
        "latin_name": "Euonymus europaeus",
        "category": "Shrub",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woods",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries, Bark",
        "warnings": "HIGH. Strong laxative, liver damage.",
        "description": "**Identification:** Shrub with distinctive pink berries that split open to reveal orange seeds. Leaves turn red in autumn.",
        "id_keys": {
            "Fruit": "Pink, 4-lobed, orange seeds inside (distinctive)",
            "Leaves": "Opposite, pointed, serrated, turn red",
            "Twigs": "Green, angular",
        },
        "danger_tips": {
            "where": "Hedgerows and woodland edges.",
            "when": "Berries in Autumn.",
            "sustainable": "Admire the colour, do not eat.",
            "danger_zone": "HIGH. Severe stomach upset, liver and kidney damage.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive bright pink/orange fruits are unique among common hedgerow plants. No edible plant has this fruit structure.",
            },
        ],
        "confusion_notes": "Distinctive bright PINK berries with orange seeds inside. No common edible lookalike has this fruit structure. Do NOT eat the berries.",
    },
    {
        "name": "Woody Nightshade (Bittersweet)",
        "latin_name": "Solanum dulcamara",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Hedgerows, Woods",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "MEDIUM to HIGH. Poisonous, causes vomiting.",
        "description": "**Identification:** Climbing plant. Purple flowers with yellow centre cone. Bright red, egg-shaped berries.",
        "id_keys": {
            "Flowers": "Purple star, yellow cone centre",
            "Berries": "Red, egg-shaped, in clusters",
            "Leaves": "Arrow-shaped, often with basal lobes",
        },
        "danger_tips": {
            "where": "Hedgerows, scrambling over plants.",
            "when": "Flowers summer, berries autumn.",
            "sustainable": "Remove from gardens if children present.",
            "danger_zone": "HIGH. Vomiting, dizziness, diarrhoea.",
        },
        "lookalikes": [
            {
                "name": "Deadly Nightshade",
                "danger": "POISONOUS",
                "diff": "Deadly Nightshade has BLACK berries and purple/yellow BELL flowers. Woody Nightshade has RED egg berries and purple STAR flowers.",
            },
        ],
        "confusion_notes": "Woody Nightshade has PURPLE star flowers with a YELLOW cone centre and RED egg-shaped berries. Deadly Nightshade has PURPLE BELL flowers and BLACK shiny berries. Do NOT eat either of them.",
    },
    {
        "name": "White Bryony",
        "latin_name": "Bryonia dioica",
        "category": "Plant",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woodlands",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "HIGH. Severe purgative. Can be fatal.",
        "description": "**Identification:** Climbing plant (creeper). Red berries. Large lobed leaves (ivy-like). Curling tendrils used to climb.",
        "id_keys": {
            "Fruit": "Red berries, size of peas",
            "Leaves": "Lobed, ivy-like, rough texture",
            "Climb": "Climbs using curling tendrils (vital ID)",
        },
        "danger_tips": {
            "where": "Hedgerows, scrambling over bushes.",
            "when": "Berries late summer/autumn.",
            "sustainable": "Do not touch berries.",
            "danger_zone": "HIGH. Severe vomiting, diarrhoea, dehydration.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Distinctive climber with tendrils. No common edible climber has red berries in hedges.",
            },
        ],
        "confusion_notes": "Distinctive climber with red berries. No common edible climber has red berries in hedges. Do NOT eat the berries (irritant).",
    },
    {
        "name": "Black Bryony",
        "latin_name": "Tamus communis",
        "category": "Plant",
        "months": ['August', 'September', 'October'],
        "habitat": "Hedgerows, Woods",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "HIGH. Skin irritant. Poisonous if eaten.",
        "description": "**Identification:** Climbing plant. Shiny black berries. Heart-shaped glossy leaves. Twining stems (no tendrils).",
        "id_keys": {
            "Fruit": "Shiny black berries",
            "Leaves": "Heart-shaped, glossy, shiny",
            "Stem": "Twining climber (wraps around stems)",
        },
        "danger_tips": {
            "where": "Hedgerows, woods, shady places.",
            "when": "Autumn berries.",
            "sustainable": "Avoid skin contact with sap.",
            "danger_zone": "HIGH. Skin irritation, severe stomach pain.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "Shiny black berries and heart-shaped leaves on a twining stem. Unlikely to be confused with edibles.",
            },
        ],
        "confusion_notes": "Distinctive climber with shiny black berries and heart-shaped glossy leaves. No common edible climber has shiny black berries. Do NOT touch the berries (skin irritant).",
    },
    {
        "name": "Giant Hogweed",
        "latin_name": "Heracleum mantegazzianum",
        "category": "Plant",
        "months": ['June', 'July', 'August'],
        "habitat": "Riverbanks, Waste Ground",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Sap (All parts)",
        "warnings": "EXTREME. Sap causes severe burns in sunlight (Phototoxicity).",
        "description": "**Identification:** Massive plant (up to 5m). Thick stems with purple blotches and bristles. Huge flower heads (umbels).",
        "id_keys": {
            "Height": "Giant (3-5m tall)",
            "Stem": "Thick, purple blotches, bristly",
            "Flowers": "Huge white umbels (50cm+)",
        },
        "danger_tips": {
            "where": "Riverbanks, waste ground.",
            "when": "Summer.",
            "sustainable": "Report sightings. Do NOT touch.",
            "danger_zone": "☠️ EXTREME. Sap + Sun = Blisters/Burns. Can cause BLINDNESS if rubbed in eyes. Do NOT touch.",
        },
        "lookalikes": [
            {
                "name": "Common Hogweed",
                "danger": "EDIBLE",
                "diff": "Common Hogweed is smaller (1-2m). Stems are green/pale, less blotchy. Giant is HUGE.",
            },
            {
                "name": "Alexanders",
                "danger": "EDIBLE",
                "diff": "Alexanders has solid green stems (no purple blotches) and smells of celery.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Giant Hogweed is HUGE (3-5m tall) with purple blotches on thick stems. Common Hogweed is smaller (1-2m) with green/pale stems. If it is GIANT with purple spots, do NOT touch it — the sap burns in sunlight.",
    },
    {
        "name": "Meadow Saffron",
        "latin_name": "Colchicum autumnale",
        "category": "Plant",
        "months": ['August', 'September', 'October'],
        "habitat": "Meadows, Woodlands, Damp grassland",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially seeds and corm)",
        "warnings": "EXTREME. Fatal in small doses. No antidote.",
        "description": "**Identification:** Purple, crocus-like flowers appearing in autumn with NO leaves present. Leaves appear in spring. **Danger:** Contains colchicine which causes multi-organ failure.",
        "id_keys": {
            "Flowers": "Purple, crocus-like, 6 petals, no leaves when flowering",
            "Leaves": "Appear in spring, long, lance-shaped",
            "Corm": "Underground bulb, highly toxic",
        },
        "danger_tips": {
            "where": "Damp meadows and woodland clearings.",
            "when": "Flowers in Autumn, leaves in Spring.",
            "sustainable": "Do not pick wild crocus-like flowers.",
            "danger_zone": "☠️ DEADLY. No antidote. Causes organ failure. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Autumn Crocus (Saffron Crocus)",
                "danger": "EDIBLE (Saffron)",
                "diff": "Saffron Crocus has 3 stigmas (red/orange) and leaves appear with flowers. Meadow Saffron has 6 stamens and flowers appear ALONE (no leaves).",
            },
            {
                "name": "Wild Garlic",
                "danger": "EDIBLE",
                "diff": "Wild Garlic has white star flowers and smells strongly of garlic. Meadow Saffron is purple and scentless.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Meadow Saffron flowers appear in AUTUMN with NO LEAVES. Saffron Crocus has leaves and 3 RED stigmas. If a purple crocus-like flower has no leaves, do NOT touch it.",
    },
    {
        "name": "Monkshood",
        "latin_name": "Aconitum napellus",
        "category": "Plant",
        "months": ['June', 'July', 'August'],
        "habitat": "Woodlands, Gardens, Mountain areas",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially roots)",
        "warnings": "EXTREME. Most poisonous plant in UK. Absorbed through skin.",
        "description": "**Identification:** Tall spikes of dark blue/purple hooded flowers. Dark green, glossy, deeply divided leaves. **Danger:** Contains aconitine which affects the heart and nerves.",
        "id_keys": {
            "Flowers": "Blue/Purple, hooded (like a monk's cowl)",
            "Leaves": "Dark green, glossy, palmately lobed",
            "Root": "Tuberous, highly toxic",
        },
        "danger_tips": {
            "where": "Damp woods, stream sides, gardens.",
            "when": "Summer.",
            "sustainable": "Do NOT touch without gloves.",
            "danger_zone": "☠️ DEADLY. Absorbed through skin. Causes heart palpitations and death. Do NOT touch.",
        },
        "lookalikes": [
            {
                "name": "Larkspur",
                "danger": "MILDLY TOXIC",
                "diff": "Larkspur flowers have a backward pointing spur. Monkshood has a distinct helmet/hood shape over the top.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Monkshood has BLUE/PURPLE flowers shaped like a HOOD or helmet. Larkspur has a backward pointing spur. Do NOT touch Monkshood, even skin contact is DEADLY.",
    },
    {
        "name": "Lily of the Valley",
        "latin_name": "Convallaria majalis",
        "category": "Plant",
        "months": ['May', 'June'],
        "habitat": "Woodlands, Gardens",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially red berries)",
        "warnings": "HIGH. Contains cardiac glycosides. Fatal if eaten.",
        "description": "**Identification:** Low growing plant. Two large leaves with curved parallel veins. Drooping bells of white flowers. Orange-red berries in autumn.",
        "id_keys": {
            "Flowers": "White, bell-shaped, drooping on one side of stem",
            "Leaves": "Two large leaves, parallel veins",
            "Berries": "Orange-red, round",
        },
        "danger_tips": {
            "where": "Shady woods, gardens.",
            "when": "Flowers in Spring, Berries in Autumn.",
            "sustainable": "Do not pick for indoor displays.",
            "danger_zone": "☠️ HIGH. Causes heart irregularities and nausea. Do NOT eat the red berries.",
        },
        "lookalikes": [
            {
                "name": "Wild Garlic",
                "danger": "EDIBLE",
                "diff": "Wild Garlic has a distinct garlic smell. Lily of the Valley has NO garlic smell and different leaf veins (curved parallel vs straight).",
            },
            {
                "name": "Solomon's Seal",
                "danger": "EDIBLE",
                "diff": "Solomon's Seal has flowers hanging in pairs along the stem underside. Lily of the Valley flowers are clustered on one side.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Lily of the Valley has WHITE bells on one side of the stem and NO garlic smell. Wild Garlic SMELLS of garlic. If it doesn't smell of garlic, do NOT eat it.",
    },
    {
        "name": "Fool's Parsley",
        "latin_name": "Aethusa cynapium",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Gardens, Arable land, Hedgerows",
        "regions": ['All'],
        "difficulty": 3,
        "parts": "All parts",
        "warnings": "HIGH. Poisonous, causes convulsions.",
        "description": "**Identification:** Looks like flat-leaved parsley. White flowers (umbels). Distinctive long bracts hanging down under the flower head. Smells of mustard/mouse.",
        "id_keys": {
            "Flowers": "White umbels, with long thin bracts underneath",
            "Leaves": "Similar to flat-leaf parsley, but glossy underneath",
            "Smell": "Unpleasant, like mouse or mustard when crushed",
        },
        "danger_tips": {
            "where": "Cultivated ground, gardens, hedgerows.",
            "when": "Summer.",
            "sustainable": "Do not pick wild 'parsley'.",
            "danger_zone": "☠️ HIGH. Burning mouth, vomiting, convulsions. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Cow Parsley",
                "danger": "EDIBLE",
                "diff": "Cow Parsley has hairy stems and no long bracts under the umbel. Fool's Parsley has smooth stems and long dangling bracts.",
            },
            {
                "name": "Flat-leaf Parsley",
                "danger": "EDIBLE",
                "diff": "Cultivated parsley smells of fresh parsley. Fool's Parsley smells like mouse/mustard.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Fool's Parsley has long green bracts hanging DOWN under the flower umbels and smells of MOUSE URINE. Cow Parsley does NOT have long bracts. If it has dangling bracts, do NOT eat it.",
    },
    {
        "name": "Dog's Mercury",
        "latin_name": "Mercurialis perennis",
        "category": "Plant",
        "months": ['February', 'March', 'April', 'May'],
        "habitat": "Woodlands, Hedgerows",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts",
        "warnings": "HIGH. Causes severe vomiting and inflammation.",
        "description": "**Identification:** Low growing, carpeting woodland plant. Dark green, opposite, oval leaves. Separate male and female plants (catkin-like male flowers).",
        "id_keys": {
            "Leaves": "Oval, toothed, opposite, dark green, rough texture",
            "Flowers": "Green, insignificant (male on spikes, female in leaf axils)",
            "Habitat": "Forms large carpets in ancient woodland",
        },
        "danger_tips": {
            "where": "Shady woodland, dominant ground cover.",
            "when": "Spring.",
            "sustainable": "Do not add to wild salads.",
            "danger_zone": "☠️ HIGH. Causes vomiting, dizziness. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Nettle",
                "danger": "EDIBLE",
                "diff": "Nettles have stinging hairs and heart-shaped leaves. Dog's Mercury has smooth, oval, toothed leaves and NO stings.",
            },
            {
                "name": "Mint",
                "danger": "EDIBLE",
                "diff": "Mint smells strongly of mint. Dog's Mercury has no distinct mint smell.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Dog's Mercury has OVAL, non-stinging leaves and NO mint smell. Nettles STING. Mint SMELLS of mint. If you don't know what it is in a carpet, do NOT eat it.",
    },
    {
        "name": "Daffodil",
        "latin_name": "Narcissus pseudonarcissus",
        "category": "Plant",
        "months": ['February', 'March', 'April'],
        "habitat": "Woodlands, Gardens, Meadows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Bulbs (All parts irritant)",
        "warnings": "MEDIUM to HIGH. Causes severe stomach upset. Bulbs mistaken for onions.",
        "description": "**Identification:** Yellow trumpet flowers. Long, flat, strap-like leaves. Underground bulb.",
        "id_keys": {
            "Flowers": "Yellow trumpet with 6 petals",
            "Leaves": "Flat, strap-like, upright, grey-green",
            "Bulb": "Underground, onion-like",
        },
        "danger_tips": {
            "where": "Gardens, woods, roadsides.",
            "when": "Spring.",
            "sustainable": "Do not dig up wild bulbs.",
            "danger_zone": "HIGH. Severe stomach upset and skin irritation. Do NOT eat bulbs.",
        },
        "lookalikes": [
            {
                "name": "Onion/Garlic",
                "danger": "EDIBLE",
                "diff": "Onion/Garlic bulbs smell strongly of onion/garlic. Daffodil bulbs have NO onion/garlic smell.",
            },
            {
                "name": "Snowdrop",
                "danger": "MILDLY TOXIC",
                "diff": "Snowdrops are smaller, white, and have distinct green markings inside. Daffodils are large and yellow.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Daffodil bulbs do NOT smell like ONION. If a bulb doesn't smell of onion or garlic, it is NOT an onion. Do NOT eat mystery bulbs.",
    },
    {
        "name": "Thornapple",
        "latin_name": "Datura stramonium",
        "category": "Plant",
        "months": ['July', 'August', 'September', 'October'],
        "habitat": "Waste ground, Gardens, Arable",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "All parts (especially seeds)",
        "warnings": "EXTREME. Deliriant and toxic. Can be fatal.",
        "description": "**Identification:** Large, trumpet-shaped white/purple flowers. Prickly seed pods (thornapples). Strong unpleasant smell.",
        "id_keys": {
            "Flowers": "Large, white/purple trumpets, 5-lobed",
            "Fruit": "Spiny, egg-shaped seed pod (thornapple)",
            "Smell": "Strong, rank, unpleasant when crushed",
        },
        "danger_tips": {
            "where": "Disturbed ground, warm areas.",
            "when": "Summer to Autumn.",
            "sustainable": "Do not touch or inhale smoke if burning.",
            "danger_zone": "☠️ DEADLY. Intense delirium, amnesia, death. Do NOT consume.",
        },
        "lookalikes": [
            {
                "name": "Angels Trumpet",
                "danger": "POISONOUS",
                "diff": "Angels Trumpet flowers hang DOWN. Thornapple flowers point UP or sideways.",
            },
        ],
        "confusion_notes": "☠️ DEADLY: Thornapple has large trumpet flowers and SPIKY seed pods (thornapples). Angels Trumpet flowers hang DOWN. Do NOT touch or eat any part of this plant.",
    },
    {
        "name": "Ragwort",
        "latin_name": "Senecio jacobaea",
        "category": "Plant",
        "months": ['June', 'July', 'August', 'September'],
        "habitat": "Grassland, Roadsides, Pastures",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "All parts",
        "warnings": "HIGH. Cumulative liver damage (to livestock and humans).",
        "description": "**Identification:** Tall plant with bright yellow daisy-like flowers in flat-topped clusters. Dark green deeply lobed leaves.",
        "id_keys": {
            "Flowers": "Yellow, daisy-like, 13 petals typically",
            "Leaves": "Deeply lobed, ragged appearance",
            "Stem": "Tall, green/purplish",
        },
        "danger_tips": {
            "where": "Pastures, roadsides, wasteland.",
            "when": "Summer.",
            "sustainable": "Control where livestock graze.",
            "danger_zone": "☠️ HIGH. Cumulative liver damage. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "St John's Wort",
                "danger": "EDIBLE/MEDICINAL",
                "diff": "St John's Wort has 5-petalled yellow flowers with black dots. Ragwort has daisy-like flowers (13 petals).",
            },
            {
                "name": "Goldenrod",
                "danger": "EDIBLE",
                "diff": "Goldenrod has tiny yellow flowers on feathery spikes. Ragwort has daisy-like flower heads.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Ragwort has daisy-like YELLOW flowers with 13 petals and ragged, lobed leaves. St John's Wort has 5 petals and black dots. Do NOT eat Ragwort.",
    },
    {
        "name": "Snowberry",
        "latin_name": "Symphoricarpos albus",
        "category": "Shrub",
        "months": ['August', 'September', 'October', 'November'],
        "habitat": "Hedgerows, Woods",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "MEDIUM. Causes vomiting and dizziness.",
        "description": "**Identification:** Deciduous shrub. Small pinkish-white bell flowers. Distinctive large, white, soft berries that look like snowballs.",
        "id_keys": {
            "Fruit": "Large, white, soft, globe-shaped (like a snowball)",
            "Leaves": "Small, oval, green, opposite",
            "Flowers": "Small pink-white bells",
        },
        "danger_tips": {
            "where": "Hedgerows, thickets, gardens.",
            "when": "Autumn/Winter.",
            "sustainable": "Do not eat the white berries.",
            "danger_zone": "MEDIUM. Vomiting, dizziness. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "None dangerous",
                "danger": "SAFE",
                "diff": "No common edible white soft berries in hedgerows. Very distinctive snowball-like berry.",
            },
        ],
        "confusion_notes": "Distinctive large, WHITE, soft berries that look like snowballs. No common edible white soft berries in hedgerows. If you see white snowball berries, do NOT eat them.",
    },
    {
        "name": "Holly",
        "latin_name": "Ilex aquifolium",
        "category": "Tree",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Woodlands, Gardens, Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "MEDIUM to HIGH. Causes severe vomiting.",
        "description": "**Identification:** Evergreen tree. Dark green, glossy, very prickly leaves. Bright red berries in winter.",
        "id_keys": {
            "Leaves": "Dark green, glossy, spiky/prickly edges",
            "Berries": "Bright red, small, in clusters",
            "Bark": "Smooth, grey",
        },
        "danger_tips": {
            "where": "Woods, hedges, gardens.",
            "when": "Berries in Winter.",
            "sustainable": "Admire the berries, do not eat.",
            "danger_zone": "HIGH. Vomiting, diarrhoea, drowsiness. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Spindle",
                "danger": "POISONOUS",
                "diff": "Spindle berries are pink and have orange seeds inside. Holly berries are simple red berries.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Red berries with SPIKY evergreen leaves. Do NOT eat the berries. They are not wild strawberries.",
    },
    {
        "name": "Ivy",
        "latin_name": "Hedera helix",
        "category": "Plant",
        "months": ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        "habitat": "Woodlands, Hedgerows, Gardens",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "Berries, Leaves",
        "warnings": "MEDIUM to HIGH. Skin irritant, toxic berries.",
        "description": "**Identification:** Evergreen climber. Dark green, glossy, 3-5 lobed leaves. Black berries in late winter.",
        "id_keys": {
            "Leaves": "Dark green, glossy, distinct lobes (arrows/stars)",
            "Berries": "Dark purple/black, globular",
            "Growth": "Climbing/trailing woody vine",
        },
        "danger_tips": {
            "where": "Climbing trees, walls, ground cover.",
            "when": "Berries in Winter.",
            "sustainable": "Important for wildlife, do not destroy.",
            "danger_zone": "HIGH. Skin rash from sap, severe stomach upset from berries. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Black Bryony",
                "danger": "POISONOUS",
                "diff": "Black Bryony has heart-shaped leaves and twining stems. Ivy has distinct lobed leaves and woody climbing roots.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Common evergreen climber with LOBED leaves and dark purple/black berries. Do NOT eat the berries (irritant).",
    },
    {
        "name": "Bluebell",
        "latin_name": "Hyacinthoides non-scripta",
        "category": "Plant",
        "months": ['April', 'May', 'June'],
        "habitat": "Woodlands, Hedgerows",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "All parts (especially bulbs)",
        "warnings": "MEDIUM. Causes severe stomach upset.",
        "description": "**Identification:** Iconic spring flower. Violet-blue, bell-shaped flowers that droop/nod on one side of the stem. Distinctive curl-back tips.",
        "id_keys": {
            "Flowers": "Violet-blue, nodding bells, curl-back petals",
            "Leaves": "Long, narrow, strap-like",
            "Smell": "Sweet fragrance",
        },
        "danger_tips": {
            "where": "Ancient woodland, creating blue carpets.",
            "when": "Spring.",
            "sustainable": "Do not pick (protected species). Do not dig bulbs.",
            "danger_zone": "MEDIUM. Nausea, vomiting, low heart rate. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Lily of the Valley",
                "danger": "POISONOUS",
                "diff": "Lily of the Valley has white bell flowers. Bluebell has blue bell flowers.",
            },
            {
                "name": "Spanish Bluebell",
                "danger": "MILDLY TOXIC",
                "diff": "Spanish Bluebells are paler blue, upright, and have broader leaves. Native Bluebells are deep violet, droop, and curl back.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Bluebell bulbs do NOT smell like ONION. If a bulb doesn't smell of onion, it is NOT an onion. Do NOT eat bluebell bulbs.",
    },
    {
        "name": "Bracken",
        "latin_name": "Pteridium aquilinum",
        "category": "Plant",
        "months": ['May', 'June', 'July', 'August', 'September'],
        "habitat": "Woodlands, Heathlands, Hillsides",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "All parts (especially fiddleheads)",
        "warnings": "HIGH. Carcinogenic (cancer-causing).",
        "description": "**Identification:** Large, coarse fern. Triangular fronds that turn rusty brown in autumn. Fiddleheads (crosiers) are hairy and not downy.",
        "id_keys": {
            "Fronds": "Large, triangular, 3 times divided",
            "Fiddleheads": "Hairy, emerge from ground in spring",
            "Colour": "Turns rusty brown in autumn",
        },
        "danger_tips": {
            "where": "Dominates heathlands, hillsides, and woodland edges.",
            "when": "Spring (fiddleheads) to Autumn.",
            "sustainable": "Do not eat fiddleheads or use as bedding.",
            "danger_zone": "☠️ HIGH. Carcinogenic (cancer-causing). Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Ostrich Fern",
                "danger": "EDIBLE",
                "diff": "Ostrich Fern fiddleheads are smooth and have a groove on the stem. Bracken fiddleheads are hairy.",
            },
            {
                "name": "Lady Fern",
                "danger": "INEDIBLE",
                "diff": "Lady Fern is more delicate and lacy. Bracken is coarse and large.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Bracken fiddleheads are HAIRY. Edible Ostrich Fern fiddleheads are SMOOTH with a groove. If the fiddlehead is hairy, do NOT eat it.",
    },
    {
        "name": "Buttercup",
        "latin_name": "Ranunculus species",
        "category": "Plant",
        "months": ['May', 'June', 'July', 'August'],
        "habitat": "Meadows, Gardens, Grassland",
        "regions": ['All'],
        "difficulty": 1,
        "parts": "All parts",
        "warnings": "MEDIUM. Causes blistering and stomach upset.",
        "description": "**Identification:** Glossy yellow cup-shaped flowers. Deeply lobed leaves. Sap is acrid and blistering.",
        "id_keys": {
            "Flowers": "Glossy yellow, 5 petals, cup-shaped",
            "Leaves": "Deeply lobed or cut, hairy",
            "Sap": "Acrid, causes blistering on skin",
        },
        "danger_tips": {
            "where": "Lawns, meadows, wet ground.",
            "when": "Spring and Summer.",
            "sustainable": "Do not eat. Drying destroys the toxin.",
            "danger_zone": "MEDIUM. Blisters in mouth, stomach cramps. Do NOT eat.",
        },
        "lookalikes": [
            {
                "name": "Lesser Celandine",
                "danger": "EDIBLE (Roots/Leaves cooked)",
                "diff": "Lesser Celandine has 8-12 petals and is a low-growing plant. Buttercup has exactly 5 petals and is taller.",
            },
        ],
        "confusion_notes": "☠️ DANGER: Buttercups have GLOSSY yellow flowers with exactly 5 petals. Lesser Celandine has 8-12 petals. Do NOT eat fresh buttercups, they burn the mouth.",
    },
    {
        "name": "Spurge",
        "latin_name": "Euphorbia species",
        "category": "Plant",
        "months": ['April', 'May', 'June', 'July', 'August'],
        "habitat": "Gardens, Woodlands, Waste ground",
        "regions": ['All'],
        "difficulty": 2,
        "parts": "Sap (All parts)",
        "warnings": "HIGH. Sap is severely irritant and can cause blindness.",
        "description": "**Identification:** Variable plant. Green/yellow flowers (cyathia). Leaves are alternate or whorled. The key ID is the milky white sap when cut.",
        "id_keys": {
            "Sap": "Milky white sap that flows when cut",
            "Flowers": "Inconspicuous green/yellow, cup-like",
            "Leaves": "Often blue-green, alternate",
        },
        "danger_tips": {
            "where": "Gardens, waste ground, woods.",
            "when": "Spring and Summer.",
            "sustainable": "Do not break stems. Wash hands if sap contacts skin.",
            "danger_zone": "☠️ HIGH. Skin blistering, eye damage. Do NOT touch the sap.",
        },
        "lookalikes": [
            {
                "name": "Dog's Mercury",
                "danger": "POISONOUS",
                "diff": "Dog's Mercury does not produce milky white sap. Spurge always exudes white sap when cut.",
            },
        ],
        "confusion_notes": "☠️ DANGER: If a plant exudes MILKY WHITE SAP when cut, it is likely Spurge and highly toxic. Do NOT touch the sap, it can cause BLINDNESS.",
    },
        {
        "name": "Laburnum",
        "latin_name": "Laburnum anagyroides",
        "category": "Tree",
        "months": ["May", "June"],
        "habitat": "Gardens, Parks, Roadsides",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "All parts (especially seeds)",
        "warnings": "EXTREME. Seeds look like small peas. Highly toxic to children.",
        "description": "**Identification:** Small tree with chains of yellow pea-like flowers. Clover-like leaves (3 leaflets). Pea-pod seeds.",
        "id_keys": {
            "Flowers": "Yellow, pea-like, hanging in long chains (laburnums)",
            "Seeds": "Small pea pods, look like peas",
            "Leaves": "Clover-like, 3 leaflets"
        },
        "danger_tips": {
            "where": "Gardens, parks, roadsides. Often planted as ornamental.",
            "when": "Flowers in May-June. Seeds in summer.",
            "sustainable": "Do not touch or eat. Remove from gardens with children.",
            "danger_zone": "☠️ DEADLY. All parts toxic. Seeds look like peas and are especially dangerous for children."
        },
        "lookalikes": [
            {"name": "Wisteria", "danger": "MILDLY TOXIC", "diff": "Wisteria has purple/lilac hanging flowers. Laburnum has YELLOW hanging flowers."}
        ],
        "confusion_notes": "☠️ DEADLY: Laburnum has chains of YELLOW pea-like flowers and pea-pod seeds. The seeds look like peas and are very dangerous for children. Do NOT touch or eat."
    },
    {
        "name": "Horse Chestnut",
        "latin_name": "Aesculus hippocastanum",
        "category": "Tree",
        "months": ["September", "October"],
        "habitat": "Parks, Gardens, Streets",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Nuts (Conkers)",
        "warnings": "HIGH. Not edible. Commonly confused with Sweet Chestnut.",
        "description": "**Identification:** Large tree with 5-7 leaflets (palmate leaves). White candle-like flowers in spring. Smooth/warty green cases containing conkers.",
        "id_keys": {
            "Leaves": "5-7 large leaflets (palmate)",
            "Fruit case": "Smooth/warty green case, NOT spiky",
            "Nuts": "Large, round, glossy brown conkers"
        },
        "danger_tips": {
            "where": "Parks, gardens, streets. Very common.",
            "when": "Nuts in autumn.",
            "sustainable": "Do not eat. Conkers are for playing, not eating!",
            "danger_zone": "☠️ HIGH. Conkers are NOT edible. Can cause stomach upset, vomiting, and in rare cases more serious symptoms."
        },
        "lookalikes": [
            {"name": "Sweet Chestnut", "danger": "EDIBLE", "diff": "Sweet Chestnut cases are VERY SPIKY (like a hedgehog). Horse Chestnut cases are SMOOTH or WARTY."}
        ],
        "confusion_notes": "☠️ DANGER: Horse Chestnut (conkers) are NOT edible. Sweet Chestnut cases are VERY SPIKY. Horse Chestnut cases are SMOOTH or WARTY. If the case is not spiky, it is NOT a Sweet Chestnut."
    },
    {
        "name": "Deadly Webcap",
        "latin_name": "Cortinarius rubellus",
        "category": "Fungi",
        "months": ["August", "September", "October"],
        "habitat": "Woodlands (Pine, Birch)",
        "regions": ["All"],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "EXTREME. Causes irreversible kidney failure. Symptoms delayed 2-14 days.",
        "description": "**Identification:** Rusty orange-brown cap. Rusty brown gills. Has a cortina (web-like veil) covering the gills when young. Found in coniferous woodland.",
        "id_keys": {
            "Cap": "Rusty orange-brown",
            "Gills": "Rusty brown, covered by cortina when young",
            "Stem": "Pale yellow with rusty ring zone",
            "Habitat": "Coniferous woodland, especially pine/birch"
        },
        "danger_tips": {
            "where": "Pine and birch woodlands.",
            "when": "Autumn.",
            "sustainable": "Do NOT pick. Do NOT smell spores.",
            "danger_zone": "☠️ DEADLY. Causes IRREVERSIBLE kidney failure. Symptoms may not appear for 2-14 days. Do NOT eat any mushroom with a cortina."
        },
        "lookalikes": [
            {"name": "Chestnut Bolete", "danger": "EDIBLE", "diff": "Boletes have PORES (spongy underside), not gills. Webcaps have GILLS and a cortina."}
        ],
        "confusion_notes": "☠️ DEADLY: If a mushroom has a cortina (web-like veil) and rusty gills, do NOT eat it. Deadly Webcap causes IRREVERSIBLE kidney failure."
    },
    {
        "name": "Panther Cap",
        "latin_name": "Amanita pantherina",
        "category": "Fungi",
        "months": ["July", "August", "September"],
        "habitat": "Woodlands (Oak, Beech)",
        "regions": ["Southern"],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "EXTREME. More toxic than Fly Agaric. Can be fatal.",
        "description": "**Identification:** Brown cap with white warts/patches. White gills. White stem with ring and bulbous base with volva (cup).",
        "id_keys": {
            "Cap": "Brown with white warts/patches (can wash off)",
            "Gills": "White, free from stem",
            "Stem": "White, with ring and bulbous base",
            "Base": "Volva (cup) at base underground"
        },
        "danger_tips": {
            "where": "Broadleaf woodland (oak, beech).",
            "when": "Summer to Autumn.",
            "sustainable": "Do NOT touch. Do NOT pick.",
            "danger_zone": "☠️ DEADLY. More toxic than Fly Agaric. Do NOT eat any Amanita unless you are 100% certain."
        },
        "lookalikes": [
            {"name": "Blusher", "danger": "EDIBLE (if cooked)", "diff": "The Blusher bruises PINK when touched. Panther Cap does NOT change colour."}
        ],
        "confusion_notes": "☠️ DEADLY: Brown cap with white warts. Does NOT bruise pink. If you are not 100% sure, do NOT eat any Amanita mushroom."
    },
    {
        "name": "Sulphur Tuft",
        "latin_name": "Hypholoma fasciculare",
        "category": "Fungi",
        "months": ["September", "October", "November"],
        "habitat": "Woodlands (Dead wood)",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "Whole mushroom",
        "warnings": "HIGH. Causes severe gastric distress.",
        "description": "**Identification:** Grows in dense clusters on dead wood. Sulphur-yellow cap with darker centre. Yellow-green gills that turn olive-brown. Yellow stem.",
        "id_keys": {
            "Cap": "Sulphur yellow, darker centre",
            "Gills": "Yellow-green, then olive-brown",
            "Stem": "Yellow, curved",
            "Habitat": "Clusters on dead wood"
        },
        "danger_tips": {
            "where": "Dead wood, stumps, fallen trees.",
            "when": "Autumn.",
            "sustainable": "Do NOT eat. Very common.",
            "danger_zone": "☠️ HIGH. Severe vomiting, sweating, stomach cramps. Do NOT eat."
        },
        "lookalikes": [
            {"name": "Honey Fungus", "danger": "EDIBLE (some people)", "diff": "Honey Fungus has a distinct ring, honey-coloured cap, and white spore print. Sulphur Tuft has greenish gills and no persistent ring."}
        ],
        "confusion_notes": "☠️ DANGER: Sulphur Tuft grows in CLUSTERS on dead wood, has sulphur-yellow caps, and greenish gills. Do NOT eat."
    },
    {
        "name": "Snowdrop",
        "latin_name": "Galanthus nivalis",
        "category": "Plant",
        "months": ["January", "February", "March"],
        "habitat": "Woodlands, Gardens",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Bulbs (All parts)",
        "warnings": "MEDIUM. Bulbs can be confused with onions.",
        "description": "**Identification:** Small white nodding flowers with 3 outer and 3 inner petals. Inner petals have green markings. Grey-green strap-like leaves.",
        "id_keys": {
            "Flowers": "White, nodding, 3 outer petals, 3 inner with green marks",
            "Leaves": "Grey-green, strap-like",
            "Bulb": "Underground, could be confused with onion"
        },
        "danger_tips": {
            "where": "Woodlands, gardens, churchyards.",
            "when": "Late Winter/Early Spring.",
            "sustainable": "Protected in the wild. Do not dig up.",
            "danger_zone": "☠️ MEDIUM. Bulbs can be confused with onions. Do NOT eat."
        },
        "lookalikes": [
            {"name": "Onion/Garlic", "danger": "EDIBLE", "diff": "Onion and garlic bulbs SMELL strongly of onion/garlic. Snowdrop bulbs do NOT smell."}
        ],
        "confusion_notes": "☠️ DANGER: Snowdrop bulbs do NOT smell like ONION. If a bulb doesn't smell of onion or garlic, it is NOT an onion. Do NOT eat mystery bulbs."
    },
    {
        "name": "Winter Aconite",
        "latin_name": "Eranthis hyemalis",
        "category": "Plant",
        "months": ["January", "February", "March"],
        "habitat": "Gardens, Parks, Woodlands",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "All parts",
        "warnings": "HIGH. Contains cardiac glycosides.",
        "description": "**Identification:** Bright yellow cup-shaped flowers surrounded by a ruff of green bracts. One of the first flowers of the year, often appearing through snow.",
        "id_keys": {
            "Flowers": "Yellow, cup-shaped, surrounded by green ruff",
            "Leaves": "Lobed, basal, green ruff around flower",
            "Habitat": "Early spring gardens and woods"
        },
        "danger_tips": {
            "where": "Gardens, parks, deciduous woods.",
            "when": "Late winter / early spring.",
            "sustainable": "Do not pick. Admire from a distance.",
            "danger_zone": "☠️ HIGH. Contains cardiac glycosides. Do NOT eat."
        },
        "lookalikes": [
            {"name": "Lesser Celandine", "danger": "EDIBLE (when cooked)", "diff": "Lesser Celandine has shiny yellow star-like flowers with many petals. Winter Aconite has a cup shape with a green ruff."}
        ],
        "confusion_notes": "☠️ DANGER: Winter Aconite has a yellow CUP-shaped flower surrounded by a GREEN RUFF. Lesser Celandine has star-like flowers with many petals. Do NOT eat Winter Aconite."
    },
    {
        "name": "Box",
        "latin_name": "Buxus sempervirens",
        "category": "Shrub",
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "habitat": "Gardens, Parks, Hedgerows",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "All parts (especially leaves)",
        "warnings": "HIGH. Common hedge plant. Causes severe vomiting and seizures.",
        "description": "**Identification:** Evergreen shrub with small, glossy, oval leaves. Very commonly used as hedging. Distinctive smell when cut.",
        "id_keys": {
            "Leaves": "Small, oval, glossy, dark green, OPPOSITE pairs",
            "Habitat": "Formal hedges, topiary in gardens",
            "Smell": "Distinctive smell when cut/clipped"
        },
        "danger_tips": {
            "where": "Gardens, parks, formal hedging.",
            "when": "Evergreen all year.",
            "sustainable": "Do not eat. Common garden plant.",
            "danger_zone": "☠️ HIGH. Severe vomiting, seizures. Do NOT add to salads."
        },
        "lookalikes": [
            {"name": "None common", "danger": "SAFE", "diff": "Small, glossy, opposite leaves make Box distinctive."}
        ],
        "confusion_notes": "☠️ DANGER: Common garden hedge with small, glossy, oval leaves in OPPOSITE pairs. Do NOT eat the leaves."
    },
        {
        "name": "Dropwort",
        "latin_name": "Filipendula vulgaris",
        "category": "Plant",
        "months": ["May", "June", "July"],
        "habitat": "Dry Grassland, Meadows",
        "regions": ["Southern", "Central"],
        "difficulty": 3,
        "parts": "All parts (especially roots)",
        "warnings": "HIGH. Confused with Meadowsweet. Grows on DRY ground.",
        "description": "**Identification:** Very similar to Meadowsweet but grows on DRY ground. White flower clusters. Finely divided leaves. Smells different (less sweet).",
        "id_keys": {
            "Habitat": "DRY grassland and meadows (key difference from Meadowsweet)",
            "Leaves": "Finely divided, more fern-like than Meadowsweet",
            "Flowers": "White, in clusters (similar to Meadowsweet)"
        },
        "danger_tips": {
            "where": "Dry grassland, chalk downs.",
            "when": "Late Spring/Summer.",
            "sustainable": "Do not pick. Admire from a distance.",
            "danger_zone": "☠️ HIGH. Can cause stomach upset and other symptoms. Do NOT eat."
        },
        "lookalikes": [
            {"name": "Meadowsweet", "danger": "EDIBLE", "diff": "Meadowsweet grows in DAMP places and smells of almond/honey. Dropwort grows in DRY places and smells less sweet."}
        ],
        "confusion_notes": "☠️ DANGER: Dropwort grows on DRY ground. Meadowsweet grows on DAMP ground and smells of almond/honey. If you are on dry ground and see a Meadowsweet-like plant, it may be Dropwort."
    },
    {
        "name": "Herb Paris",
        "latin_name": "Paris quadrifolia",
        "category": "Plant",
        "months": ["May", "June", "July"],
        "habitat": "Woodlands, Damp shaded areas",
        "regions": ["Southern", "Central"],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "HIGH. Causes nausea, vomiting, and diarrhoea.",
        "description": "**Identification:** Single whorl of 4 (sometimes 5-8) leaves. Single green/yellow flower with 4 narrow petals. One dark berry in autumn.",
        "id_keys": {
            "Leaves": "4 (sometimes 5-8) leaves in a single whorl",
            "Flower": "Single, greenish-yellow, 4 narrow petals",
            "Berry": "Single, dark blue/black berry in autumn"
        },
        "danger_tips": {
            "where": "Ancient woodland, damp shady places.",
            "when": "Flowers May-July, Berry in Autumn.",
            "sustainable": "Do not pick or eat.",
            "danger_zone": "☠️ HIGH. Causes nausea, vomiting, and diarrhoea. Do NOT eat the berry."
        },
        "lookalikes": [
            {"name": "Lily of the Valley", "danger": "POISONOUS", "diff": "Lily of the Valley has 2 large leaves and white bell flowers. Herb Paris has 4+ leaves in a whorl."}
        ],
        "confusion_notes": "☠️ DANGER: Herb Paris has 4 (or more) leaves in a single whorl and a single green/yellow flower. Nothing else in UK woodlands looks like this."
    },
    {
        "name": "Cowbane (Water Hemlock)",
        "latin_name": "Cicuta virosa",
        "category": "Plant",
        "months": ["June", "July", "August"],
        "habitat": "Ponds, Ditches, Wet meadows",
        "regions": ["Southern", "Central"],
        "difficulty": 3,
        "parts": "All parts (especially roots)",
        "warnings": "EXTREME. One of the deadliest plants in the UK. Often confused with edible water plants.",
        "description": "**Identification:** Tall plant with white umbel flowers. Grows IN or near water. Roots are chambered (hollow). Purple-streaked stems. Smells unpleasant.",
        "id_keys": {
            "Habitat": "IN water or very wet ground (CRITICAL)",
            "Stem": "Purple-streaked, hollow",
            "Roots": "Chambered (hollow sections)",
            "Flowers": "White umbels (flat-topped clusters)"
        },
        "danger_tips": {
            "where": "Ponds, ditches, wet meadows.",
            "when": "Summer.",
            "sustainable": "Do NOT approach. Do NOT touch.",
            "danger_zone": "☠️ DEADLY. Even small amounts can be fatal. Do NOT dig roots near water."
        },
        "lookalikes": [
            {"name": "Watercress", "danger": "EDIBLE", "diff": "Watercress grows in CLEAN running water and has peppery leaves. Cowbane grows in still/dirty water and has an unpleasant smell."},
            {"name": "Water Dropwort", "danger": "DEADLY", "diff": "Both are deadly plants near water. Cowbane has chambered roots and purple-streaked stems."}
        ],
        "confusion_notes": "☠️ DEADLY: Do NOT dig up any plant near water unless you are 100% certain of its identity. Cowbane has chambered roots and purple-streaked stems."
    },
    {
        "name": "Green Hellebore",
        "latin_name": "Helleborus viridis",
        "category": "Plant",
        "months": ["February", "March", "April", "May"],
        "habitat": "Woodlands, Gardens, Limestone",
        "regions": ["Southern", "Central"],
        "difficulty": 2,
        "parts": "All parts",
        "warnings": "HIGH. Contains cardiac glycosides. Causes vomiting and heart problems.",
        "description": "**Identification:** Low-growing plant with large, deeply divided, leathery leaves. Green cup-shaped flowers appear very early in spring.",
        "id_keys": {
            "Leaves": "Large, deeply divided, leathery, dark green",
            "Flowers": "Green, cup-shaped, appear in late winter/early spring",
            "Habitat": "Woodland, gardens, limestone areas"
        },
        "danger_tips": {
            "where": "Woodlands, gardens, limestone areas.",
            "when": "Very early spring (Feb-May).",
            "sustainable": "Do not pick. Admire from a distance.",
            "danger_zone": "☠️ HIGH. Contains cardiac glycosides. Do NOT eat."
        },
        "lookalikes": [
            {"name": "Christmas Rose", "danger": "POISONOUS", "diff": "Christmas Rose (Helleborus niger) has WHITE flowers in winter. Green Hellebore has GREEN flowers in spring."}
        ],
        "confusion_notes": "☠️ DANGER: Green Hellebore has GREEN cup-shaped flowers very early in spring. All hellebores are POISONOUS."
    },
    {
        "name": "Henbane",
        "latin_name": "Hyoscyamus niger",
        "category": "Plant",
        "months": ["June", "July", "August"],
        "habitat": "Waste ground, Sandy soils, Roadsides",
        "regions": ["Southern", "Eastern"],
        "difficulty": 2,
        "parts": "All parts",
        "warnings": "EXTREME. Contains hyoscyamine and scopolamine. Causes hallucinations, delirium, and can be fatal.",
        "description": "**Identification:** Hairy, sticky plant with pale yellow flowers veined with purple. Unpleasant smell. Oval, lobed leaves.",
        "id_keys": {
            "Flowers": "Pale yellow with purple veins inside",
            "Leaves": "Hairy, sticky, oval, lobed",
            "Smell": "Unpleasant, musty"
        },
        "danger_tips": {
            "where": "Waste ground, sandy soils, disturbed areas.",
            "when": "Summer.",
            "sustainable": "Do NOT touch or inhale smoke.",
            "danger_zone": "☠️ DEADLY. Causes hallucinations, delirium, and death. Do NOT touch."
        },
        "lookalikes": [
            {"name": "Thornapple", "danger": "DEADLY", "diff": "Thornapple has large trumpet flowers and spiny seed pods. Henbane has smaller flowers with purple veins."}
        ],
        "confusion_notes": "☠️ DEADLY: Henbane has pale yellow flowers with purple veins and is covered in sticky hairs. Unpleasant smell. Do NOT touch."
    },
    {
        "name": "Broom",
        "latin_name": "Cytisus scoparius",
        "category": "Shrub",
        "months": ["May", "June"],
        "habitat": "Heathland, Roadsides, Sandy soils",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Seeds (All parts toxic)",
        "warnings": "HIGH. Seeds are toxic. Contains alkaloids that affect the heart.",
        "description": "**Identification:** Tall shrub with green, ribbed, angled stems (no leaves when mature). Bright yellow pea-like flowers. Flat, hairy seed pods.",
        "id_keys": {
            "Flowers": "Bright yellow, pea-like, large and showy",
            "Stem": "Green, ribbed, angled (5-sided), leafless when mature",
            "Seeds": "Flat, hairy pods"
        },
        "danger_tips": {
            "where": "Heathland, roadsides, sandy soils.",
            "when": "Flowers in May-June.",
            "sustainable": "Do not eat any part.",
            "danger_zone": "☠️ HIGH. All parts are toxic, especially seeds. Causes nausea, vomiting, and heart problems."
        },
        "lookalikes": [
            {"name": "Gorse", "danger": "EDIBLE (flowers)", "diff": "Gorse has spiny, prickly branches and coconut-smelling flowers. Broom has smooth, green, ribbed stems and no thorns."}
        ],
        "confusion_notes": "☠️ DANGER: Broom has smooth green ribbed stems with NO thorns. Gorse has spiny, prickly branches. Broom seeds are TOXIC."
    },
    {
        "name": "Privet",
        "latin_name": "Ligustrum vulgare",
        "category": "Shrub",
        "months": ["June", "July", "August", "September", "October"],
        "habitat": "Hedgerows, Gardens, Woods",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "All parts (especially berries)",
        "warnings": "HIGH. Very common hedge plant. Causes severe stomach upset.",
        "description": "**Identification:** Common hedge plant with small, oval, glossy, dark green leaves in opposite pairs. White flowers in clusters. Black berries in autumn.",
        "id_keys": {
            "Leaves": "Small, oval, glossy, dark green, OPPOSITE pairs",
            "Flowers": "White, small, in pyramidal clusters",
            "Berries": "Black, small, in clusters",
            "Habitat": "Hedges, gardens, VERY common"
        },
        "danger_tips": {
            "where": "Gardens, hedgerows (very common hedge plant).",
            "when": "Flowers in summer, berries in autumn.",
            "sustainable": "Do not eat. Very common hedge.",
            "danger_zone": "☠️ HIGH. All parts toxic. Causes severe stomach upset. Do NOT eat the berries."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Small, glossy, opposite leaves on a common hedge. No edible plant looks exactly like privet."}
        ],
        "confusion_notes": "☠️ DANGER: Common garden hedge with small, glossy, OPPOSITE leaves and black berries. Do NOT eat the berries."
    },
    {
        "name": "Cotoneaster",
        "latin_name": "Cotoneaster species",
        "category": "Shrub",
        "months": ["August", "September", "October", "November"],
        "habitat": "Gardens, Walls, Escaped to wild",
        "regions": ["All"],
        "difficulty": 1,
        "parts": "Berries",
        "warnings": "MEDIUM to HIGH. Causes nausea, vomiting and diarrhoea.",
        "description": "**Identification:** Garden shrub with small, round, shiny leaves. Bright red or orange berries in autumn. Some are deciduous, some evergreen.",
        "id_keys": {
            "Leaves": "Small, round, shiny, often evergreen",
            "Berries": "Red or orange, small, in clusters",
            "Habitat": "Gardens, walls, car parks (very common)"
        },
        "danger_tips": {
            "where": "Gardens, walls, car parks, bird-sown in the wild.",
            "when": "Berries in autumn.",
            "sustainable": "Do not eat. Very common garden plant.",
            "danger_zone": "☠️ MEDIUM to HIGH. Causes stomach upset. Keep children away from berries."
        },
        "lookalikes": [
            {"name": "None dangerous", "danger": "SAFE", "diff": "Small, round leaves with red/orange berries on a garden shrub."}
        ],
        "confusion_notes": "☠️ DANGER: Common garden shrub with small, round leaves and red/orange berries. Do NOT eat the berries. Very common in gardens and car parks."
    },
    {
        "name": "Dwarf Elder",
        "latin_name": "Sambucus ebulus",
        "category": "Plant",
        "months": ["June", "July", "August", "September"],
        "habitat": "Waste ground, Damp places, Field edges",
        "regions": ["Southern", "Eastern"],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "HIGH. More toxic than Elderberry. Upright berry clusters (different from Elder's flat clusters).",
        "description": "**Identification:** Tall herbaceous plant (NOT woody like Elder). White flower umbels. Upright clusters of black berries (NOT flat like Elder). Unpleasant smell.",
        "id_keys": {
            "Stem": "Herbaceous (green, NOT woody like Elder)",
            "Berries": "Upright clusters (NOT flat like Elder)",
            "Smell": "Unpleasant (unlike Elder's sweet smell)",
            "Leaves": "Similar to Elder but plant is herbaceous"
        },
        "danger_tips": {
            "where": "Waste ground, damp places, field edges.",
            "when": "Summer/Autumn.",
            "sustainable": "Do not eat any part.",
            "danger_zone": "☠️ HIGH. More toxic than Elderberry. Causes severe vomiting and diarrhoea."
        },
        "lookalikes": [
            {"name": "Elderflower/Elderberry", "danger": "EDIBLE (when cooked)", "diff": "Elder has WOODY stems and FLAT berry clusters. Dwarf Elder has HERBACEOUS stems and UPRIGHT berry clusters."}
        ],
        "confusion_notes": "☠️ DANGER: Dwarf Elder has HERBACEOUS (green, non-woody) stems and UPRIGHT berry clusters. True Elder has WOODY stems and FLAT berry clusters. Dwarf Elder is MORE toxic."
    },
    {
        "name": "Tutsan",
        "latin_name": "Hypericum androsaemum",
        "category": "Shrub",
        "months": ["June", "July", "August", "September", "October"],
        "habitat": "Woodlands, Hedgerows, Damp places",
        "regions": ["All"],
        "difficulty": 2,
        "parts": "All parts (especially berries)",
        "warnings": "HIGH. Berries change from red to black. Causes photosensitivity.",
        "description": "**Identification:** Shrub with oval, opposite leaves. Yellow flowers with prominent stamens. Berries turn from red to glossy black.",
        "id_keys": {
            "Leaves": "Oval, opposite, with translucent dots",
            "Flowers": "Yellow, 5 petals, prominent stamens",
            "Berries": "Start red, turn black, in small clusters"
        },
        "danger_tips": {
            "where": "Woodland, hedgerows, damp places.",
            "when": "Flowers summer, berries autumn.",
            "sustainable": "Do not eat. Admire the berries.",
            "danger_zone": "☠️ HIGH. Causes photosensitivity and stomach upset. Do NOT eat."
        },
        "lookalikes": [
            {"name": "St John's Wort", "danger": "MILDLY TOXIC (medicinal)", "diff": "St John's Wort has smaller leaves and is a taller, slimmer plant. Tutsan has broader leaves and is shrubbier."}
        ],
        "confusion_notes": "☠️ DANGER: Tutsan has broad, oval opposite leaves and berries that turn from RED to BLACK. Related to St John's Wort but MORE toxic."
    },
    {
        "name": "Angel's Wings",
        "latin_name": "Pleurocybella porrigens",
        "category": "Fungi",
        "months": ["September", "October", "November"],
        "habitat": "Woodlands (Conifers, Pine)",
        "regions": ["Southern"],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "EXTREME. Grows on conifers. Can cause fatal brain disease.",
        "description": "**Identification:** White, fan-shaped, thin and fragile. Grows in tiers on dead conifer wood. Looks similar to Oyster Mushroom but grows on CONIFERS.",
        "id_keys": {
            "Cap": "White, fan-shaped, very thin and fragile",
            "Gills": "White, running down (decurrent)",
            "Habitat": "On DEAD CONIFER wood (pine, spruce)",
            "Smell": "Mushroomy, not distinctive"
        },
        "danger_tips": {
            "where": "Dead conifer wood.",
            "when": "Autumn.",
            "sustainable": "Do NOT pick.",
            "danger_zone": "☠️ DEADLY. Can cause fatal brain disease. Do NOT eat any white mushroom growing on conifers."
        },
        "lookalikes": [
            {"name": "Oyster Mushroom", "danger": "EDIBLE", "diff": "Oyster Mushroom grows on HARDWOOD (broadleaf trees). Angel's Wings grow on CONIFERS. If a white oyster-like mushroom is on a conifer, do NOT eat it."}
        ],
        "confusion_notes": "☠️ DEADLY: Angel's Wings grow on CONIFERS (pine, spruce). Oyster Mushrooms grow on HARDWOOD. If a white, fan-shaped mushroom is growing on a conifer, do NOT eat it."
    },
    {
        "name": "Deadly Fibrecap",
        "latin_name": "Inocybe erubescens",
        "category": "Fungi",
        "months": ["May", "June", "July", "August"],
        "habitat": "Woodlands, Parks, Gardens",
        "regions": ["Southern", "Central"],
        "difficulty": 3,
        "parts": "Whole mushroom",
        "warnings": "EXTREME. Contains muscarine. Can be fatal. Stains red when bruised.",
        "description": "**Identification:** Small to medium mushroom with a white/cream cap that develops reddish staining when bruised. White gills. Fibrous cap surface. Often found in parks and gardens.",
        "id_keys": {
            "Cap": "White/cream, fibrous surface, STAINS RED when bruised",
            "Gills": "White, crowded",
            "Stem": "White, fibrous",
            "Bruising": "Turns RED when cut or bruised (KEY ID)"
        },
        "danger_tips": {
            "where": "Woodlands, parks, gardens.",
            "when": "Spring and Summer.",
            "sustainable": "Do NOT touch. Do NOT smell spores.",
            "danger_zone": "☠️ DEADLY. Contains muscarine. Causes sweating, salivation, and can be fatal."
        },
        "lookalikes": [
            {"name": "Field Mushroom", "danger": "EDIBLE", "diff": "Field mushroom has a smooth cap and pink then brown gills. Deadly Fibrecap has a fibrous cap, white gills, and STAINS RED."}
        ],
        "confusion_notes": "☠️ DEADLY: Deadly Fibrecap has a FIBROUS cap surface and STAINS RED when bruised. If a small mushroom stains red when cut, do NOT eat it."
    },
]
